// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/account.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAccountRequest, CreateAccountResponse, DeleteAccountRequest, DeleteAccountResponse, ListAccountsRequest, ListAccountsResponse, UpdateAccountRequest, UpdateAccountResponse } from "./account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.AccountService
 */
export declare const AccountService: {
  readonly typeName: "v1.AccountService",
  readonly methods: {
    /**
     * @generated from rpc v1.AccountService.ListAccounts
     */
    readonly listAccounts: {
      readonly name: "ListAccounts",
      readonly I: typeof ListAccountsRequest,
      readonly O: typeof ListAccountsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.AccountService.CreateAccount
     */
    readonly createAccount: {
      readonly name: "CreateAccount",
      readonly I: typeof CreateAccountRequest,
      readonly O: typeof CreateAccountResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.AccountService.UpdateAccount
     */
    readonly updateAccount: {
      readonly name: "UpdateAccount",
      readonly I: typeof UpdateAccountRequest,
      readonly O: typeof UpdateAccountResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.AccountService.DeleteAccount
     */
    readonly deleteAccount: {
      readonly name: "DeleteAccount",
      readonly I: typeof DeleteAccountRequest,
      readonly O: typeof DeleteAccountResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

