// @generated by protoc-gen-es v2.16.0
// @generated from file v1/account.proto (package v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file v1/account.proto.
 */
export const file_v1_account = /*@__PURE__*/
  fileDesc("ChB2MS9hY2NvdW50LnByb3RvEgJ2MSL6AQoMSW50ZXJlc3RUaWVyEg8KAmlkGAEgASgDSACIAQESGAoLdXBfdG9fbWlub3IYAiABKANIAYgBARIbCg5maXhlZF9yYXRlX2JwcxgDIAEoA0gCiAEBEhsKDnJlZmVyZW5jZV9jb2RlGAQgASgJSAOIAQESEgoKc3ByZWFkX2JwcxgFIAEoAxIeChFyZXNvbHZlZF9yYXRlX2JwcxgGIAEoA0gEiAEBQgUKA19pZEIOCgxfdXBfdG9fbWlub3JCEQoPX2ZpeGVkX3JhdGVfYnBzQhEKD19yZWZlcmVuY2VfY29kZUIUChJfcmVzb2x2ZWRfcmF0ZV9icHMipQMKB0FjY291bnQSCgoCaWQYASABKAMSDAoEbmFtZRgCIAEoCRITCgtpbnN0aXR1dGlvbhgDIAEoCRIMCgR0eXBlGAQgASgJEhEKCXByZWZlcnJlZBgFIAEoCBIQCghhcmNoaXZlZBgGIAEoCBIQCghjdXJyZW5jeRgHIAEoCRIVCg1iYWxhbmNlX21pbm9yGAggASgDEg8KB3RheF9icHMYCSABKAMSGAoQYW5udWFsX2ZlZV9taW5vchgKIAEoAxIfCgV0aWVycxgLIAMoCzIQLnYxLkludGVyZXN0VGllchIbChNncm9zc19yZXZlbnVlX21pbm9yGAwgASgDEhEKCXRheF9taW5vchgNIAEoAxIZChFuZXRfcmV2ZW51ZV9taW5vchgOIAEoAxIVCg1ob2xkaW5nX2NvdW50GA8gASgDEhwKFGhvbGRpbmdzX3ZhbHVlX21pbm9yGBAgASgDEhoKEnRvdGFsX2Fzc2V0c19taW5vchgRIAEoAxIYChBwYWNfYW1vdW50X21pbm9yGBIgASgDEg0KBW5vdGVzGBMgASgJIjEKE0xpc3RBY2NvdW50c1JlcXVlc3QSEQoEc29ydBgBIAEoCUgAiAEBQgcKBV9zb3J0IjUKFExpc3RBY2NvdW50c1Jlc3BvbnNlEh0KCGFjY291bnRzGAEgAygLMgsudjEuQWNjb3VudCI0ChRDcmVhdGVBY2NvdW50UmVxdWVzdBIcCgdhY2NvdW50GAEgASgLMgsudjEuQWNjb3VudCI1ChVDcmVhdGVBY2NvdW50UmVzcG9uc2USHAoHYWNjb3VudBgBIAEoCzILLnYxLkFjY291bnQiQAoUVXBkYXRlQWNjb3VudFJlcXVlc3QSCgoCaWQYASABKAMSHAoHYWNjb3VudBgCIAEoCzILLnYxLkFjY291bnQiNQoVVXBkYXRlQWNjb3VudFJlc3BvbnNlEhwKB2FjY291bnQYASABKAsyCy52MS5BY2NvdW50IiIKFERlbGV0ZUFjY291bnRSZXF1ZXN0EgoKAmlkGAEgASgDIhcKFURlbGV0ZUFjY291bnRSZXNwb25zZTKlAgoOQWNjb3VudFNlcnZpY2USQQoMTGlzdEFjY291bnRzEhcudjEuTGlzdEFjY291bnRzUmVxdWVzdBoYLnYxLkxpc3RBY2NvdW50c1Jlc3BvbnNlEkQKDUNyZWF0ZUFjY291bnQSGC52MS5DcmVhdGVBY2NvdW50UmVxdWVzdBoZLnYxLkNyZWF0ZUFjY291bnRSZXNwb25zZRJECg1VcGRhdGVBY2NvdW50EhgudjEuVXBkYXRlQWNjb3VudFJlcXVlc3QaGS52MS5VcGRhdGVBY2NvdW50UmVzcG9uc2USRAoNRGVsZXRlQWNjb3VudBIYLnYxLkRlbGV0ZUFjY291bnRSZXF1ZXN0GhkudjEuRGVsZXRlQWNjb3VudFJlc3BvbnNlQjNaMWdpdGh1Yi5jb20vcm9hcmMwL3NxdWlycmVsL3Byb3RvL2dlbi9nby92MTtwb3J0djFiBnByb3RvMw");

/**
 * Describes the message v1.InterestTier.
 * Use `create(InterestTierSchema)` to create a new message.
 */
export const InterestTierSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 0);

/**
 * Describes the message v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 1);

/**
 * Describes the message v1.ListAccountsRequest.
 * Use `create(ListAccountsRequestSchema)` to create a new message.
 */
export const ListAccountsRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 2);

/**
 * Describes the message v1.ListAccountsResponse.
 * Use `create(ListAccountsResponseSchema)` to create a new message.
 */
export const ListAccountsResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 3);

/**
 * Describes the message v1.CreateAccountRequest.
 * Use `create(CreateAccountRequestSchema)` to create a new message.
 */
export const CreateAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 4);

/**
 * Describes the message v1.CreateAccountResponse.
 * Use `create(CreateAccountResponseSchema)` to create a new message.
 */
export const CreateAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 5);

/**
 * Describes the message v1.UpdateAccountRequest.
 * Use `create(UpdateAccountRequestSchema)` to create a new message.
 */
export const UpdateAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 6);

/**
 * Describes the message v1.UpdateAccountResponse.
 * Use `create(UpdateAccountResponseSchema)` to create a new message.
 */
export const UpdateAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 7);

/**
 * Describes the message v1.DeleteAccountRequest.
 * Use `create(DeleteAccountRequestSchema)` to create a new message.
 */
export const DeleteAccountRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 8);

/**
 * Describes the message v1.DeleteAccountResponse.
 * Use `create(DeleteAccountResponseSchema)` to create a new message.
 */
export const DeleteAccountResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_account, 9);

/**
 * AccountService handles financial account management, interest yield calculations, and PAC budgets.
 *
 * @generated from service v1.AccountService
 */
export const AccountService = /*@__PURE__*/
  serviceDesc(file_v1_account, 0);

