// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/account.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateAccountRequest, CreateAccountResponse, DeleteAccountRequest, DeleteAccountResponse, ListAccountsRequest, ListAccountsResponse, UpdateAccountRequest, UpdateAccountResponse } from "./account_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AccountService handles financial account management, interest yield calculations, and PAC budgets.
 *
 * @generated from service v1.AccountService
 */
export const AccountService = {
  typeName: "v1.AccountService",
  methods: {
    /**
     * List all bank, broker, and cash accounts with calculated yields and balances.
     *
     * @generated from rpc v1.AccountService.ListAccounts
     */
    listAccounts: {
      name: "ListAccounts",
      I: ListAccountsRequest,
      O: ListAccountsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Create a new bank or broker account.
     *
     * @generated from rpc v1.AccountService.CreateAccount
     */
    createAccount: {
      name: "CreateAccount",
      I: CreateAccountRequest,
      O: CreateAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update an existing account and recalculate interest tiers.
     *
     * @generated from rpc v1.AccountService.UpdateAccount
     */
    updateAccount: {
      name: "UpdateAccount",
      I: UpdateAccountRequest,
      O: UpdateAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an account and its associated holdings.
     *
     * @generated from rpc v1.AccountService.DeleteAccount
     */
    deleteAccount: {
      name: "DeleteAccount",
      I: DeleteAccountRequest,
      O: DeleteAccountResponse,
      kind: MethodKind.Unary,
    },
  }
};

