// @generated by protoc-gen-es v2.16.0
// @generated from file v1/backtest.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { InstrumentRiskMetrics } from "./instrument_pb";

/**
 * Describes the file v1/backtest.proto.
 */
export declare const file_v1_backtest: GenFile;

/**
 * @generated from message v1.BacktestAllocation
 */
export declare type BacktestAllocation = Message<"v1.BacktestAllocation"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: int32 weight_bps = 2;
   */
  weightBps: number;
};

/**
 * Describes the message v1.BacktestAllocation.
 * Use `create(BacktestAllocationSchema)` to create a new message.
 */
export declare const BacktestAllocationSchema: GenMessage<BacktestAllocation>;

/**
 * Unsaved simulation inputs; IDs are local labels, never database references.
 *
 * @generated from message v1.BacktestDraftPlan
 */
export declare type BacktestDraftPlan = Message<"v1.BacktestDraftPlan"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int64 monthly_minor = 3;
   */
  monthlyMinor: bigint;

  /**
   * @generated from field: repeated v1.BacktestAllocation allocations = 4;
   */
  allocations: BacktestAllocation[];
};

/**
 * Describes the message v1.BacktestDraftPlan.
 * Use `create(BacktestDraftPlanSchema)` to create a new message.
 */
export declare const BacktestDraftPlanSchema: GenMessage<BacktestDraftPlan>;

/**
 * @generated from message v1.RunBacktestRequest
 */
export declare type RunBacktestRequest = Message<"v1.RunBacktestRequest"> & {
  /**
   * Select owned, active EUR PAC accounts, a custom allocation, or draft plans.
   *
   * @generated from field: repeated int64 account_ids = 1;
   */
  accountIds: bigint[];

  /**
   * @generated from field: repeated v1.BacktestAllocation allocations = 2;
   */
  allocations: BacktestAllocation[];

  /**
   * @generated from field: string start_date = 3;
   */
  startDate: string;

  /**
   * @generated from field: string end_date = 4;
   */
  endDate: string;

  /**
   * EUR cents. For PACs the initial sum is split in proportion to monthly budgets.
   *
   * @generated from field: int64 initial_minor = 5;
   */
  initialMinor: bigint;

  /**
   * Only for custom allocations; PACs use their saved account budgets.
   *
   * @generated from field: int64 monthly_minor = 6;
   */
  monthlyMinor: bigint;

  /**
   * none (default), monthly, annually
   *
   * @generated from field: string rebalance = 7;
   */
  rebalance: string;

  /**
   * @generated from field: double risk_free_rate = 8;
   */
  riskFreeRate: number;

  /**
   * @generated from field: double target_return = 9;
   */
  targetReturn: number;

  /**
   * Alternative to account_ids or allocations. Each draft remains a separate PAC.
   *
   * @generated from field: repeated v1.BacktestDraftPlan draft_plans = 10;
   */
  draftPlans: BacktestDraftPlan[];
};

/**
 * Describes the message v1.RunBacktestRequest.
 * Use `create(RunBacktestRequestSchema)` to create a new message.
 */
export declare const RunBacktestRequestSchema: GenMessage<RunBacktestRequest>;

/**
 * @generated from message v1.BacktestObservation
 */
export declare type BacktestObservation = Message<"v1.BacktestObservation"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * EUR, fractional index units, no cent rounding during simulation
   *
   * @generated from field: double value = 2;
   */
  value: number;

  /**
   * @generated from field: double contributed = 3;
   */
  contributed: number;

  /**
   * unitized time-weighted level, starting at 1
   *
   * @generated from field: double index = 4;
   */
  index: number;

  /**
   * positive fraction
   *
   * @generated from field: double drawdown = 5;
   */
  drawdown: number;
};

/**
 * Describes the message v1.BacktestObservation.
 * Use `create(BacktestObservationSchema)` to create a new message.
 */
export declare const BacktestObservationSchema: GenMessage<BacktestObservation>;

/**
 * @generated from message v1.BacktestMonth
 */
export declare type BacktestMonth = Message<"v1.BacktestMonth"> & {
  /**
   * @generated from field: int32 year = 1;
   */
  year: number;

  /**
   * @generated from field: int32 month = 2;
   */
  month: number;

  /**
   * @generated from field: double return_value = 3;
   */
  returnValue: number;

  /**
   * @generated from field: bool partial = 4;
   */
  partial: boolean;
};

/**
 * Describes the message v1.BacktestMonth.
 * Use `create(BacktestMonthSchema)` to create a new message.
 */
export declare const BacktestMonthSchema: GenMessage<BacktestMonth>;

/**
 * @generated from message v1.BacktestYear
 */
export declare type BacktestYear = Message<"v1.BacktestYear"> & {
  /**
   * @generated from field: int32 year = 1;
   */
  year: number;

  /**
   * @generated from field: double return_value = 2;
   */
  returnValue: number;

  /**
   * @generated from field: bool partial = 3;
   */
  partial: boolean;
};

/**
 * Describes the message v1.BacktestYear.
 * Use `create(BacktestYearSchema)` to create a new message.
 */
export declare const BacktestYearSchema: GenMessage<BacktestYear>;

/**
 * @generated from message v1.BacktestReturnPoint
 */
export declare type BacktestReturnPoint = Message<"v1.BacktestReturnPoint"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: double return_value = 2;
   */
  returnValue: number;
};

/**
 * Describes the message v1.BacktestReturnPoint.
 * Use `create(BacktestReturnPointSchema)` to create a new message.
 */
export declare const BacktestReturnPointSchema: GenMessage<BacktestReturnPoint>;

/**
 * @generated from message v1.BacktestRollingWindow
 */
export declare type BacktestRollingWindow = Message<"v1.BacktestRollingWindow"> & {
  /**
   * @generated from field: int32 years = 1;
   */
  years: number;

  /**
   * @generated from field: repeated v1.BacktestReturnPoint points = 2;
   */
  points: BacktestReturnPoint[];
};

/**
 * Describes the message v1.BacktestRollingWindow.
 * Use `create(BacktestRollingWindowSchema)` to create a new message.
 */
export declare const BacktestRollingWindowSchema: GenMessage<BacktestRollingWindow>;

/**
 * @generated from message v1.BacktestHoldingPeriod
 */
export declare type BacktestHoldingPeriod = Message<"v1.BacktestHoldingPeriod"> & {
  /**
   * @generated from field: int32 years = 1;
   */
  years: number;

  /**
   * @generated from field: int32 samples = 2;
   */
  samples: number;

  /**
   * @generated from field: optional double worst_return = 3;
   */
  worstReturn?: number | undefined;

  /**
   * @generated from field: optional double nonnegative_fraction = 4;
   */
  nonnegativeFraction?: number | undefined;
};

/**
 * Describes the message v1.BacktestHoldingPeriod.
 * Use `create(BacktestHoldingPeriodSchema)` to create a new message.
 */
export declare const BacktestHoldingPeriodSchema: GenMessage<BacktestHoldingPeriod>;

/**
 * @generated from message v1.BacktestPortfolio
 */
export declare type BacktestPortfolio = Message<"v1.BacktestPortfolio"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated v1.BacktestObservation series = 3;
   */
  series: BacktestObservation[];

  /**
   * @generated from field: v1.InstrumentRiskMetrics metrics = 4;
   */
  metrics?: InstrumentRiskMetrics | undefined;

  /**
   * @generated from field: optional double xirr = 5;
   */
  xirr?: number | undefined;

  /**
   * @generated from field: repeated v1.BacktestMonth months = 6;
   */
  months: BacktestMonth[];

  /**
   * @generated from field: repeated v1.BacktestYear years = 7;
   */
  years: BacktestYear[];

  /**
   * @generated from field: int32 complete_months = 8;
   */
  completeMonths: number;

  /**
   * @generated from field: optional double positive_months = 9;
   */
  positiveMonths?: number | undefined;

  /**
   * @generated from field: optional double monthly_var95 = 10;
   */
  monthlyVar95?: number | undefined;

  /**
   * @generated from field: optional double monthly_var99 = 11;
   */
  monthlyVar99?: number | undefined;

  /**
   * @generated from field: repeated v1.BacktestRollingWindow rolling = 12;
   */
  rolling: BacktestRollingWindow[];

  /**
   * @generated from field: repeated v1.BacktestHoldingPeriod holding_periods = 13;
   */
  holdingPeriods: BacktestHoldingPeriod[];

  /**
   * @generated from field: double average_drawdown = 14;
   */
  averageDrawdown: number;

  /**
   * @generated from field: int32 longest_drawdown_days = 15;
   */
  longestDrawdownDays: number;

  /**
   * @generated from field: string longest_drawdown_start = 16;
   */
  longestDrawdownStart: string;

  /**
   * @generated from field: string longest_drawdown_end = 17;
   */
  longestDrawdownEnd: string;

  /**
   * @generated from field: bool longest_drawdown_unrecovered = 18;
   */
  longestDrawdownUnrecovered: boolean;

  /**
   * @generated from field: repeated string notes = 19;
   */
  notes: string[];

  /**
   * @generated from field: double max_drawdown = 20;
   */
  maxDrawdown: number;

  /**
   * elapsed calendar days / 365.25, not observation count
   *
   * @generated from field: double duration_years = 21;
   */
  durationYears: number;
};

/**
 * Describes the message v1.BacktestPortfolio.
 * Use `create(BacktestPortfolioSchema)` to create a new message.
 */
export declare const BacktestPortfolioSchema: GenMessage<BacktestPortfolio>;

/**
 * @generated from message v1.BacktestCoverage
 */
export declare type BacktestCoverage = Message<"v1.BacktestCoverage"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string start_date = 3;
   */
  startDate: string;

  /**
   * @generated from field: string end_date = 4;
   */
  endDate: string;

  /**
   * @generated from field: string fetched_at = 5;
   */
  fetchedAt: string;
};

/**
 * Describes the message v1.BacktestCoverage.
 * Use `create(BacktestCoverageSchema)` to create a new message.
 */
export declare const BacktestCoverageSchema: GenMessage<BacktestCoverage>;

/**
 * @generated from message v1.BacktestCorrelation
 */
export declare type BacktestCorrelation = Message<"v1.BacktestCorrelation"> & {
  /**
   * @generated from field: string left = 1;
   */
  left: string;

  /**
   * @generated from field: string right = 2;
   */
  right: string;

  /**
   * @generated from field: optional double value = 3;
   */
  value?: number | undefined;
};

/**
 * Describes the message v1.BacktestCorrelation.
 * Use `create(BacktestCorrelationSchema)` to create a new message.
 */
export declare const BacktestCorrelationSchema: GenMessage<BacktestCorrelation>;

/**
 * @generated from message v1.BacktestCorrelationWindow
 */
export declare type BacktestCorrelationWindow = Message<"v1.BacktestCorrelationWindow"> & {
  /**
   * zero = entire effective window
   *
   * @generated from field: int32 years = 1;
   */
  years: number;

  /**
   * @generated from field: int32 observations = 2;
   */
  observations: number;

  /**
   * @generated from field: repeated v1.BacktestCorrelation pairs = 3;
   */
  pairs: BacktestCorrelation[];
};

/**
 * Describes the message v1.BacktestCorrelationWindow.
 * Use `create(BacktestCorrelationWindowSchema)` to create a new message.
 */
export declare const BacktestCorrelationWindowSchema: GenMessage<BacktestCorrelationWindow>;

/**
 * @generated from message v1.BacktestPlan
 */
export declare type BacktestPlan = Message<"v1.BacktestPlan"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: double initial = 3;
   */
  initial: number;

  /**
   * @generated from field: double monthly = 4;
   */
  monthly: number;

  /**
   * @generated from field: repeated v1.BacktestAllocation allocations = 5;
   */
  allocations: BacktestAllocation[];
};

/**
 * Describes the message v1.BacktestPlan.
 * Use `create(BacktestPlanSchema)` to create a new message.
 */
export declare const BacktestPlanSchema: GenMessage<BacktestPlan>;

/**
 * @generated from message v1.RunBacktestResponse
 */
export declare type RunBacktestResponse = Message<"v1.RunBacktestResponse"> & {
  /**
   * @generated from field: string start_date = 1;
   */
  startDate: string;

  /**
   * @generated from field: string end_date = 2;
   */
  endDate: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency: string;

  /**
   * @generated from field: string rebalance = 4;
   */
  rebalance: string;

  /**
   * @generated from field: double risk_free_rate = 5;
   */
  riskFreeRate: number;

  /**
   * @generated from field: double target_return = 6;
   */
  targetReturn: number;

  /**
   * @generated from field: v1.BacktestPortfolio combined = 7;
   */
  combined?: BacktestPortfolio | undefined;

  /**
   * @generated from field: repeated v1.BacktestPortfolio portfolios = 8;
   */
  portfolios: BacktestPortfolio[];

  /**
   * @generated from field: repeated v1.BacktestCoverage coverage = 9;
   */
  coverage: BacktestCoverage[];

  /**
   * @generated from field: repeated v1.BacktestCorrelationWindow correlations = 10;
   */
  correlations: BacktestCorrelationWindow[];

  /**
   * @generated from field: repeated v1.BacktestPlan plans = 11;
   */
  plans: BacktestPlan[];

  /**
   * @generated from field: repeated string notes = 12;
   */
  notes: string[];
};

/**
 * Describes the message v1.RunBacktestResponse.
 * Use `create(RunBacktestResponseSchema)` to create a new message.
 */
export declare const RunBacktestResponseSchema: GenMessage<RunBacktestResponse>;

/**
 * @generated from service v1.BacktestService
 */
export declare const BacktestService: GenService<{
  /**
   * Stateless historical replay of the selected allocations. Resolves saved history
   * (fetching on first use); never changes holdings, budgets or trades.
   *
   * @generated from rpc v1.BacktestService.RunBacktest
   */
  runBacktest: {
    methodKind: "unary";
    input: typeof RunBacktestRequestSchema;
    output: typeof RunBacktestResponseSchema;
  },
}>;
