// @generated by protoc-gen-es v2.16.0
// @generated from file v1/btp.proto (package v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file v1/btp.proto.
 */
export const file_v1_btp = /*@__PURE__*/
  fileDesc("Cgx2MS9idHAucHJvdG8SAnYxIuwDCgdCdHBCb25kEgwKBGlzaW4YASABKAkSDAoEbmFtZRgCIAEoCRIRCglib25kX3R5cGUYAyABKAkSDQoFcHJpY2UYBCABKAESDgoGY291cG9uGAUgASgBEhMKC2V4cGlyeV9kYXRlGAYgASgJEhYKDm1hdHVyaXR5X3llYXJzGAcgASgBEhQKDGR1cmF0aW9uX21hYxgIIAEoARIUCgxkdXJhdGlvbl9tb2QYCSABKAESGAoQcmF0ZV9oaWtlX2ltcGFjdBgKIAEoARIYChBzaW1wbGVfeWllbGRfbmV0GAsgASgBEhoKEnNpbXBsZV95aWVsZF9ncm9zcxgMIAEoARIRCgl5dG1fZ3Jvc3MYDSABKAESDwoHeXRtX25ldBgOIAEoARIYChB0b3RhbF9yZXR1cm5fbmV0GA8gASgBEhoKEnRvdGFsX3JldHVybl9ncm9zcxgQIAEoARINCgVzY29yZRgRIAEoARIRCgl0aWVyX3JhbmsYEiABKAkSEQoJaXNfdHJhZGVkGBMgASgIEhIKCnNjcmFwZWRfYXQYFCABKAkSEgoKaXNfc3RhcnJlZBgVIAEoCBIbChNhbmFseXRpY3NfYXZhaWxhYmxlGBYgASgIEhYKDmFuYWx5dGljc19ub3RlGBcgASgJImcKD0xpc3RCdHBzUmVxdWVzdBINCgVxdWVyeRgBIAEoCRIRCglib25kX3R5cGUYAiABKAkSFAoMc3RhcnJlZF9vbmx5GAMgASgIEhwKFHRhcmdldF9tYXR1cml0eV95ZWFyGAQgASgFIlgKEExpc3RCdHBzUmVzcG9uc2USGQoEYnRwcxgBIAMoCzILLnYxLkJ0cEJvbmQSFAoMbGFzdF91cGRhdGVkGAIgASgJEhMKC3RvdGFsX2NvdW50GAMgASgFIjIKElJlZnJlc2hCdHBzUmVxdWVzdBIcChR0YXJnZXRfbWF0dXJpdHlfeWVhchgBIAEoBSI6ChNSZWZyZXNoQnRwc1Jlc3BvbnNlEg0KBWNvdW50GAEgASgFEhQKDGxhc3RfdXBkYXRlZBgCIAEoCSI1ChRUb2dnbGVTdGFyQnRwUmVxdWVzdBIMCgRpc2luGAEgASgJEg8KB3N0YXJyZWQYAiABKAgiKAoVVG9nZ2xlU3RhckJ0cFJlc3BvbnNlEg8KB3N0YXJyZWQYASABKAgyyQEKCkJ0cFNlcnZpY2USNQoITGlzdEJ0cHMSEy52MS5MaXN0QnRwc1JlcXVlc3QaFC52MS5MaXN0QnRwc1Jlc3BvbnNlEj4KC1JlZnJlc2hCdHBzEhYudjEuUmVmcmVzaEJ0cHNSZXF1ZXN0GhcudjEuUmVmcmVzaEJ0cHNSZXNwb25zZRJECg1Ub2dnbGVTdGFyQnRwEhgudjEuVG9nZ2xlU3RhckJ0cFJlcXVlc3QaGS52MS5Ub2dnbGVTdGFyQnRwUmVzcG9uc2VCM1oxZ2l0aHViLmNvbS9yb2FyYzAvc3F1aXJyZWwvcHJvdG8vZ2VuL2dvL3YxO3BvcnR2MWIGcHJvdG8z");

/**
 * Describes the message v1.BtpBond.
 * Use `create(BtpBondSchema)` to create a new message.
 */
export const BtpBondSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 0);

/**
 * Describes the message v1.ListBtpsRequest.
 * Use `create(ListBtpsRequestSchema)` to create a new message.
 */
export const ListBtpsRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 1);

/**
 * Describes the message v1.ListBtpsResponse.
 * Use `create(ListBtpsResponseSchema)` to create a new message.
 */
export const ListBtpsResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 2);

/**
 * Describes the message v1.RefreshBtpsRequest.
 * Use `create(RefreshBtpsRequestSchema)` to create a new message.
 */
export const RefreshBtpsRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 3);

/**
 * Describes the message v1.RefreshBtpsResponse.
 * Use `create(RefreshBtpsResponseSchema)` to create a new message.
 */
export const RefreshBtpsResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 4);

/**
 * Describes the message v1.ToggleStarBtpRequest.
 * Use `create(ToggleStarBtpRequestSchema)` to create a new message.
 */
export const ToggleStarBtpRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 5);

/**
 * Describes the message v1.ToggleStarBtpResponse.
 * Use `create(ToggleStarBtpResponseSchema)` to create a new message.
 */
export const ToggleStarBtpResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_btp, 6);

/**
 * BtpService manages Italian government bond rankings and analytics.
 *
 * @generated from service v1.BtpService
 */
export const BtpService = /*@__PURE__*/
  serviceDesc(file_v1_btp, 0);

