// @generated by protoc-gen-es v1.10.0
// @generated from file v1/btp.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * BtpBond defines the metrics and scoring data for an Italian government bond (BTP).
 *
 * @generated from message v1.BtpBond
 */
export const BtpBond = /*@__PURE__*/ proto3.makeMessageType(
  "v1.BtpBond",
  () => [
    { no: 1, name: "isin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "bond_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "price", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "coupon", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "expiry_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "maturity_years", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "duration_mac", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 9, name: "duration_mod", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 10, name: "rate_hike_impact", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 11, name: "simple_yield_net", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 12, name: "simple_yield_gross", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 13, name: "ytm_gross", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 14, name: "ytm_net", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 15, name: "total_return_net", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 16, name: "total_return_gross", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 17, name: "score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 18, name: "tier_rank", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 19, name: "is_traded", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 20, name: "scraped_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 21, name: "is_starred", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message v1.ListBtpsRequest
 */
export const ListBtpsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListBtpsRequest",
  () => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "bond_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "starred_only", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "target_maturity_year", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.ListBtpsResponse
 */
export const ListBtpsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListBtpsResponse",
  () => [
    { no: 1, name: "btps", kind: "message", T: BtpBond, repeated: true },
    { no: 2, name: "last_updated", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.RefreshBtpsRequest
 */
export const RefreshBtpsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RefreshBtpsRequest",
  () => [
    { no: 1, name: "target_maturity_year", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.RefreshBtpsResponse
 */
export const RefreshBtpsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RefreshBtpsResponse",
  () => [
    { no: 1, name: "count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "last_updated", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.ToggleStarBtpRequest
 */
export const ToggleStarBtpRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ToggleStarBtpRequest",
  () => [
    { no: 1, name: "isin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "starred", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message v1.ToggleStarBtpResponse
 */
export const ToggleStarBtpResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ToggleStarBtpResponse",
  () => [
    { no: 1, name: "starred", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

