// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/btp.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListBtpsRequest, ListBtpsResponse, RefreshBtpsRequest, RefreshBtpsResponse, ToggleStarBtpRequest, ToggleStarBtpResponse } from "./btp_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * BtpService manages Italian government bond rankings and analytics.
 *
 * @generated from service v1.BtpService
 */
export declare const BtpService: {
  readonly typeName: "v1.BtpService",
  readonly methods: {
    /**
     * List BTP bonds with optional search, type filtering, and starred status.
     *
     * @generated from rpc v1.BtpService.ListBtps
     */
    readonly listBtps: {
      readonly name: "ListBtps",
      readonly I: typeof ListBtpsRequest,
      readonly O: typeof ListBtpsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Re-scrape and recalculate all BTP bond metrics and scores.
     *
     * @generated from rpc v1.BtpService.RefreshBtps
     */
    readonly refreshBtps: {
      readonly name: "RefreshBtps",
      readonly I: typeof RefreshBtpsRequest,
      readonly O: typeof RefreshBtpsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Toggle the starred status of a specific BTP bond.
     *
     * @generated from rpc v1.BtpService.ToggleStarBtp
     */
    readonly toggleStarBtp: {
      readonly name: "ToggleStarBtp",
      readonly I: typeof ToggleStarBtpRequest,
      readonly O: typeof ToggleStarBtpResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

