// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/btp.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListBtpsRequest, ListBtpsResponse, RefreshBtpsRequest, RefreshBtpsResponse, ToggleStarBtpRequest, ToggleStarBtpResponse } from "./btp_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * BtpService manages Italian government bond rankings and analytics.
 *
 * @generated from service v1.BtpService
 */
export const BtpService = {
  typeName: "v1.BtpService",
  methods: {
    /**
     * List BTP bonds with optional search, type filtering, and starred status.
     *
     * @generated from rpc v1.BtpService.ListBtps
     */
    listBtps: {
      name: "ListBtps",
      I: ListBtpsRequest,
      O: ListBtpsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Re-scrape and recalculate all BTP bond metrics and scores.
     *
     * @generated from rpc v1.BtpService.RefreshBtps
     */
    refreshBtps: {
      name: "RefreshBtps",
      I: RefreshBtpsRequest,
      O: RefreshBtpsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Toggle the starred status of a specific BTP bond.
     *
     * @generated from rpc v1.BtpService.ToggleStarBtp
     */
    toggleStarBtp: {
      name: "ToggleStarBtp",
      I: ToggleStarBtpRequest,
      O: ToggleStarBtpResponse,
      kind: MethodKind.Unary,
    },
  }
};

