// @generated by protoc-gen-es v2.16.0
// @generated from file v1/btp.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/btp.proto.
 */
export declare const file_v1_btp: GenFile;

/**
 * BtpBond defines the metrics and scoring data for an Italian government bond (BTP).
 *
 * @generated from message v1.BtpBond
 */
export declare type BtpBond = Message<"v1.BtpBond"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string bond_type = 3;
   */
  bondType: string;

  /**
   * @generated from field: double price = 4;
   */
  price: number;

  /**
   * @generated from field: double coupon = 5;
   */
  coupon: number;

  /**
   * @generated from field: string expiry_date = 6;
   */
  expiryDate: string;

  /**
   * @generated from field: double maturity_years = 7;
   */
  maturityYears: number;

  /**
   * @generated from field: double duration_mac = 8;
   */
  durationMac: number;

  /**
   * @generated from field: double duration_mod = 9;
   */
  durationMod: number;

  /**
   * @generated from field: double rate_hike_impact = 10;
   */
  rateHikeImpact: number;

  /**
   * @generated from field: double simple_yield_net = 11;
   */
  simpleYieldNet: number;

  /**
   * @generated from field: double simple_yield_gross = 12;
   */
  simpleYieldGross: number;

  /**
   * @generated from field: double ytm_gross = 13;
   */
  ytmGross: number;

  /**
   * @generated from field: double ytm_net = 14;
   */
  ytmNet: number;

  /**
   * @generated from field: double total_return_net = 15;
   */
  totalReturnNet: number;

  /**
   * @generated from field: double total_return_gross = 16;
   */
  totalReturnGross: number;

  /**
   * @generated from field: double score = 17;
   */
  score: number;

  /**
   * @generated from field: string tier_rank = 18;
   */
  tierRank: string;

  /**
   * @generated from field: bool is_traded = 19;
   */
  isTraded: boolean;

  /**
   * @generated from field: string scraped_at = 20;
   */
  scrapedAt: string;

  /**
   * @generated from field: bool is_starred = 21;
   */
  isStarred: boolean;

  /**
   * @generated from field: bool analytics_available = 22;
   */
  analyticsAvailable: boolean;

  /**
   * @generated from field: string analytics_note = 23;
   */
  analyticsNote: string;
};

/**
 * Describes the message v1.BtpBond.
 * Use `create(BtpBondSchema)` to create a new message.
 */
export declare const BtpBondSchema: GenMessage<BtpBond>;

/**
 * @generated from message v1.ListBtpsRequest
 */
export declare type ListBtpsRequest = Message<"v1.ListBtpsRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: string bond_type = 2;
   */
  bondType: string;

  /**
   * @generated from field: bool starred_only = 3;
   */
  starredOnly: boolean;

  /**
   * @generated from field: int32 target_maturity_year = 4;
   */
  targetMaturityYear: number;
};

/**
 * Describes the message v1.ListBtpsRequest.
 * Use `create(ListBtpsRequestSchema)` to create a new message.
 */
export declare const ListBtpsRequestSchema: GenMessage<ListBtpsRequest>;

/**
 * @generated from message v1.ListBtpsResponse
 */
export declare type ListBtpsResponse = Message<"v1.ListBtpsResponse"> & {
  /**
   * @generated from field: repeated v1.BtpBond btps = 1;
   */
  btps: BtpBond[];

  /**
   * @generated from field: string last_updated = 2;
   */
  lastUpdated: string;

  /**
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message v1.ListBtpsResponse.
 * Use `create(ListBtpsResponseSchema)` to create a new message.
 */
export declare const ListBtpsResponseSchema: GenMessage<ListBtpsResponse>;

/**
 * @generated from message v1.RefreshBtpsRequest
 */
export declare type RefreshBtpsRequest = Message<"v1.RefreshBtpsRequest"> & {
  /**
   * @generated from field: int32 target_maturity_year = 1;
   */
  targetMaturityYear: number;
};

/**
 * Describes the message v1.RefreshBtpsRequest.
 * Use `create(RefreshBtpsRequestSchema)` to create a new message.
 */
export declare const RefreshBtpsRequestSchema: GenMessage<RefreshBtpsRequest>;

/**
 * @generated from message v1.RefreshBtpsResponse
 */
export declare type RefreshBtpsResponse = Message<"v1.RefreshBtpsResponse"> & {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;

  /**
   * @generated from field: string last_updated = 2;
   */
  lastUpdated: string;
};

/**
 * Describes the message v1.RefreshBtpsResponse.
 * Use `create(RefreshBtpsResponseSchema)` to create a new message.
 */
export declare const RefreshBtpsResponseSchema: GenMessage<RefreshBtpsResponse>;

/**
 * @generated from message v1.ToggleStarBtpRequest
 */
export declare type ToggleStarBtpRequest = Message<"v1.ToggleStarBtpRequest"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: bool starred = 2;
   */
  starred: boolean;
};

/**
 * Describes the message v1.ToggleStarBtpRequest.
 * Use `create(ToggleStarBtpRequestSchema)` to create a new message.
 */
export declare const ToggleStarBtpRequestSchema: GenMessage<ToggleStarBtpRequest>;

/**
 * @generated from message v1.ToggleStarBtpResponse
 */
export declare type ToggleStarBtpResponse = Message<"v1.ToggleStarBtpResponse"> & {
  /**
   * @generated from field: bool starred = 1;
   */
  starred: boolean;
};

/**
 * Describes the message v1.ToggleStarBtpResponse.
 * Use `create(ToggleStarBtpResponseSchema)` to create a new message.
 */
export declare const ToggleStarBtpResponseSchema: GenMessage<ToggleStarBtpResponse>;

/**
 * BtpService manages Italian government bond rankings and analytics.
 *
 * @generated from service v1.BtpService
 */
export declare const BtpService: GenService<{
  /**
   * List BTP bonds with optional search, type filtering, and starred status.
   *
   * @generated from rpc v1.BtpService.ListBtps
   */
  listBtps: {
    methodKind: "unary";
    input: typeof ListBtpsRequestSchema;
    output: typeof ListBtpsResponseSchema;
  },
  /**
   * Re-scrape and recalculate all BTP bond metrics and scores.
   *
   * @generated from rpc v1.BtpService.RefreshBtps
   */
  refreshBtps: {
    methodKind: "unary";
    input: typeof RefreshBtpsRequestSchema;
    output: typeof RefreshBtpsResponseSchema;
  },
  /**
   * Toggle the starred status of a specific BTP bond.
   *
   * @generated from rpc v1.BtpService.ToggleStarBtp
   */
  toggleStarBtp: {
    methodKind: "unary";
    input: typeof ToggleStarBtpRequestSchema;
    output: typeof ToggleStarBtpResponseSchema;
  },
}>;

