// @generated by protoc-gen-es v1.10.0
// @generated from file v1/btp.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * BtpBond defines the metrics and scoring data for an Italian government bond (BTP).
 *
 * @generated from message v1.BtpBond
 */
export declare class BtpBond extends Message<BtpBond> {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string bond_type = 3;
   */
  bondType: string;

  /**
   * @generated from field: double price = 4;
   */
  price: number;

  /**
   * @generated from field: double coupon = 5;
   */
  coupon: number;

  /**
   * @generated from field: string expiry_date = 6;
   */
  expiryDate: string;

  /**
   * @generated from field: double maturity_years = 7;
   */
  maturityYears: number;

  /**
   * @generated from field: double duration_mac = 8;
   */
  durationMac: number;

  /**
   * @generated from field: double duration_mod = 9;
   */
  durationMod: number;

  /**
   * @generated from field: double rate_hike_impact = 10;
   */
  rateHikeImpact: number;

  /**
   * @generated from field: double simple_yield_net = 11;
   */
  simpleYieldNet: number;

  /**
   * @generated from field: double simple_yield_gross = 12;
   */
  simpleYieldGross: number;

  /**
   * @generated from field: double ytm_gross = 13;
   */
  ytmGross: number;

  /**
   * @generated from field: double ytm_net = 14;
   */
  ytmNet: number;

  /**
   * @generated from field: double total_return_net = 15;
   */
  totalReturnNet: number;

  /**
   * @generated from field: double total_return_gross = 16;
   */
  totalReturnGross: number;

  /**
   * @generated from field: double score = 17;
   */
  score: number;

  /**
   * @generated from field: string tier_rank = 18;
   */
  tierRank: string;

  /**
   * @generated from field: bool is_traded = 19;
   */
  isTraded: boolean;

  /**
   * @generated from field: string scraped_at = 20;
   */
  scrapedAt: string;

  /**
   * @generated from field: bool is_starred = 21;
   */
  isStarred: boolean;

  constructor(data?: PartialMessage<BtpBond>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.BtpBond";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BtpBond;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BtpBond;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BtpBond;

  static equals(a: BtpBond | PlainMessage<BtpBond> | undefined, b: BtpBond | PlainMessage<BtpBond> | undefined): boolean;
}

/**
 * @generated from message v1.ListBtpsRequest
 */
export declare class ListBtpsRequest extends Message<ListBtpsRequest> {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * @generated from field: string bond_type = 2;
   */
  bondType: string;

  /**
   * @generated from field: bool starred_only = 3;
   */
  starredOnly: boolean;

  /**
   * @generated from field: int32 target_maturity_year = 4;
   */
  targetMaturityYear: number;

  constructor(data?: PartialMessage<ListBtpsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListBtpsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBtpsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBtpsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBtpsRequest;

  static equals(a: ListBtpsRequest | PlainMessage<ListBtpsRequest> | undefined, b: ListBtpsRequest | PlainMessage<ListBtpsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListBtpsResponse
 */
export declare class ListBtpsResponse extends Message<ListBtpsResponse> {
  /**
   * @generated from field: repeated v1.BtpBond btps = 1;
   */
  btps: BtpBond[];

  /**
   * @generated from field: string last_updated = 2;
   */
  lastUpdated: string;

  /**
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;

  constructor(data?: PartialMessage<ListBtpsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListBtpsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBtpsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBtpsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBtpsResponse;

  static equals(a: ListBtpsResponse | PlainMessage<ListBtpsResponse> | undefined, b: ListBtpsResponse | PlainMessage<ListBtpsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.RefreshBtpsRequest
 */
export declare class RefreshBtpsRequest extends Message<RefreshBtpsRequest> {
  /**
   * @generated from field: int32 target_maturity_year = 1;
   */
  targetMaturityYear: number;

  constructor(data?: PartialMessage<RefreshBtpsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RefreshBtpsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshBtpsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshBtpsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshBtpsRequest;

  static equals(a: RefreshBtpsRequest | PlainMessage<RefreshBtpsRequest> | undefined, b: RefreshBtpsRequest | PlainMessage<RefreshBtpsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.RefreshBtpsResponse
 */
export declare class RefreshBtpsResponse extends Message<RefreshBtpsResponse> {
  /**
   * @generated from field: int32 count = 1;
   */
  count: number;

  /**
   * @generated from field: string last_updated = 2;
   */
  lastUpdated: string;

  constructor(data?: PartialMessage<RefreshBtpsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RefreshBtpsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshBtpsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshBtpsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshBtpsResponse;

  static equals(a: RefreshBtpsResponse | PlainMessage<RefreshBtpsResponse> | undefined, b: RefreshBtpsResponse | PlainMessage<RefreshBtpsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.ToggleStarBtpRequest
 */
export declare class ToggleStarBtpRequest extends Message<ToggleStarBtpRequest> {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: bool starred = 2;
   */
  starred: boolean;

  constructor(data?: PartialMessage<ToggleStarBtpRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ToggleStarBtpRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ToggleStarBtpRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ToggleStarBtpRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ToggleStarBtpRequest;

  static equals(a: ToggleStarBtpRequest | PlainMessage<ToggleStarBtpRequest> | undefined, b: ToggleStarBtpRequest | PlainMessage<ToggleStarBtpRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ToggleStarBtpResponse
 */
export declare class ToggleStarBtpResponse extends Message<ToggleStarBtpResponse> {
  /**
   * @generated from field: bool starred = 1;
   */
  starred: boolean;

  constructor(data?: PartialMessage<ToggleStarBtpResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ToggleStarBtpResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ToggleStarBtpResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ToggleStarBtpResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ToggleStarBtpResponse;

  static equals(a: ToggleStarBtpResponse | PlainMessage<ToggleStarBtpResponse> | undefined, b: ToggleStarBtpResponse | PlainMessage<ToggleStarBtpResponse> | undefined): boolean;
}

