// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/holding.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateHoldingRequest, CreateHoldingResponse, DeleteHoldingRequest, DeleteHoldingResponse, ListHoldingsRequest, ListHoldingsResponse, UpdateHoldingRequest, UpdateHoldingResponse } from "./holding_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.HoldingService
 */
export const HoldingService = {
  typeName: "v1.HoldingService",
  methods: {
    /**
     * @generated from rpc v1.HoldingService.ListHoldings
     */
    listHoldings: {
      name: "ListHoldings",
      I: ListHoldingsRequest,
      O: ListHoldingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.HoldingService.CreateHolding
     */
    createHolding: {
      name: "CreateHolding",
      I: CreateHoldingRequest,
      O: CreateHoldingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.HoldingService.UpdateHolding
     */
    updateHolding: {
      name: "UpdateHolding",
      I: UpdateHoldingRequest,
      O: UpdateHoldingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.HoldingService.DeleteHolding
     */
    deleteHolding: {
      name: "DeleteHolding",
      I: DeleteHoldingRequest,
      O: DeleteHoldingResponse,
      kind: MethodKind.Unary,
    },
  }
};

