// @generated by protoc-gen-es v1.10.0
// @generated from file v1/holding.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.Holding
 */
export const Holding = /*@__PURE__*/ proto3.makeMessageType(
  "v1.Holding",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "account_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "instrument_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "account_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 6, name: "instrument_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "instrument_isin", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "instrument_ticker", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "instrument_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "asset_class", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "invested_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 12, name: "value_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 13, name: "tax_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 14, name: "planned_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 15, name: "actual_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 16, name: "ter_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 17, name: "is_pac", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 18, name: "pac_amount_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 19, name: "pac_frequency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.ListHoldingsRequest
 */
export const ListHoldingsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListHoldingsRequest",
  () => [
    { no: 1, name: "sort", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message v1.ListHoldingsResponse
 */
export const ListHoldingsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListHoldingsResponse",
  () => [
    { no: 1, name: "holdings", kind: "message", T: Holding, repeated: true },
  ],
);

/**
 * @generated from message v1.CreateHoldingRequest
 */
export const CreateHoldingRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CreateHoldingRequest",
  () => [
    { no: 1, name: "holding", kind: "message", T: Holding },
  ],
);

/**
 * @generated from message v1.CreateHoldingResponse
 */
export const CreateHoldingResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CreateHoldingResponse",
  () => [
    { no: 1, name: "holding", kind: "message", T: Holding },
  ],
);

/**
 * @generated from message v1.UpdateHoldingRequest
 */
export const UpdateHoldingRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.UpdateHoldingRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "holding", kind: "message", T: Holding },
  ],
);

/**
 * @generated from message v1.UpdateHoldingResponse
 */
export const UpdateHoldingResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.UpdateHoldingResponse",
  () => [
    { no: 1, name: "holding", kind: "message", T: Holding },
  ],
);

/**
 * @generated from message v1.DeleteHoldingRequest
 */
export const DeleteHoldingRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DeleteHoldingRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.DeleteHoldingResponse
 */
export const DeleteHoldingResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DeleteHoldingResponse",
  [],
);

