// @generated by protoc-gen-es v1.10.0
// @generated from file v1/holding.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Holding represents an asset position held within a specific account.
 *
 * @generated from message v1.Holding
 */
export declare class Holding extends Message<Holding> {
  /**
   * Unique holding ID.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Associated account ID.
   *
   * @generated from field: int64 account_id = 2;
   */
  accountId: bigint;

  /**
   * Associated instrument ID.
   *
   * @generated from field: int64 instrument_id = 3;
   */
  instrumentId: bigint;

  /**
   * Name of the account holding this position.
   *
   * @generated from field: optional string account_name = 4;
   */
  accountName?: string;

  /**
   * Base currency code (e.g. "EUR", "USD").
   *
   * @generated from field: optional string currency = 5;
   */
  currency?: string;

  /**
   * Full name of the instrument (e.g. "iShares Core MSCI World UCITS ETF").
   *
   * @generated from field: optional string instrument_name = 6;
   */
  instrumentName?: string;

  /**
   * International Securities Identification Number (ISIN, e.g. "IE00B4L5Y983").
   *
   * @generated from field: optional string instrument_isin = 7;
   */
  instrumentIsin?: string;

  /**
   * Ticker symbol (e.g. "SWDA").
   *
   * @generated from field: optional string instrument_ticker = 8;
   */
  instrumentTicker?: string;

  /**
   * Instrument type (e.g. "etf", "etc", "stock", "bond").
   *
   * @generated from field: optional string instrument_type = 9;
   */
  instrumentType?: string;

  /**
   * Asset class (e.g. "equity", "bond", "commodity", "cash").
   *
   * @generated from field: optional string asset_class = 10;
   */
  assetClass?: string;

  /**
   * Total cost basis / invested capital in minor units (cents).
   *
   * @generated from field: int64 invested_minor = 11;
   */
  investedMinor: bigint;

  /**
   * Current market value in minor units (cents). May be 0 for new PAC accumulation plans.
   *
   * @generated from field: int64 value_minor = 12;
   */
  valueMinor: bigint;

  /**
   * Applicable capital gains tax rate in basis points (e.g. 2600 bps = 26.00%).
   *
   * @generated from field: int64 tax_bps = 13;
   */
  taxBps: bigint;

  /**
   * Target planned portfolio allocation weight in basis points (e.g. 8000 bps = 80.00%).
   *
   * @generated from field: int64 planned_bps = 14;
   */
  plannedBps: bigint;

  /**
   * Calculated actual weight of this holding relative to total currency wealth in basis points.
   *
   * @generated from field: int64 actual_bps = 15;
   */
  actualBps: bigint;

  /**
   * Total Expense Ratio (TER) of the instrument in basis points (e.g. 20 bps = 0.20%).
   *
   * @generated from field: int64 ter_bps = 16;
   */
  terBps: bigint;

  /**
   * Whether this holding is part of an active PAC dollar-cost averaging plan.
   *
   * @generated from field: bool is_pac = 17;
   */
  isPac: boolean;

  /**
   * Share of account monthly PAC budget allocated to this holding in basis points (e.g. 6400 bps = 64.00%).
   *
   * @generated from field: int64 pac_bps = 18;
   */
  pacBps: bigint;

  /**
   * PAC deposit frequency (e.g. "monthly", "weekly", "biweekly", "quarterly").
   *
   * @generated from field: string pac_frequency = 19;
   */
  pacFrequency: string;

  /**
   * User strategic notes and context explaining the role of this holding to the AI Assistant.
   *
   * @generated from field: string notes = 20;
   */
  notes: string;

  constructor(data?: PartialMessage<Holding>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Holding";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Holding;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Holding;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Holding;

  static equals(a: Holding | PlainMessage<Holding> | undefined, b: Holding | PlainMessage<Holding> | undefined): boolean;
}

/**
 * @generated from message v1.ListHoldingsRequest
 */
export declare class ListHoldingsRequest extends Message<ListHoldingsRequest> {
  /**
   * Optional sorting parameter e.g. "value:desc" or "name:asc".
   *
   * @generated from field: optional string sort = 1;
   */
  sort?: string;

  constructor(data?: PartialMessage<ListHoldingsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListHoldingsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListHoldingsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListHoldingsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListHoldingsRequest;

  static equals(a: ListHoldingsRequest | PlainMessage<ListHoldingsRequest> | undefined, b: ListHoldingsRequest | PlainMessage<ListHoldingsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListHoldingsResponse
 */
export declare class ListHoldingsResponse extends Message<ListHoldingsResponse> {
  /**
   * @generated from field: repeated v1.Holding holdings = 1;
   */
  holdings: Holding[];

  constructor(data?: PartialMessage<ListHoldingsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListHoldingsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListHoldingsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListHoldingsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListHoldingsResponse;

  static equals(a: ListHoldingsResponse | PlainMessage<ListHoldingsResponse> | undefined, b: ListHoldingsResponse | PlainMessage<ListHoldingsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.CreateHoldingRequest
 */
export declare class CreateHoldingRequest extends Message<CreateHoldingRequest> {
  /**
   * @generated from field: v1.Holding holding = 1;
   */
  holding?: Holding;

  constructor(data?: PartialMessage<CreateHoldingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CreateHoldingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateHoldingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateHoldingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateHoldingRequest;

  static equals(a: CreateHoldingRequest | PlainMessage<CreateHoldingRequest> | undefined, b: CreateHoldingRequest | PlainMessage<CreateHoldingRequest> | undefined): boolean;
}

/**
 * @generated from message v1.CreateHoldingResponse
 */
export declare class CreateHoldingResponse extends Message<CreateHoldingResponse> {
  /**
   * @generated from field: v1.Holding holding = 1;
   */
  holding?: Holding;

  constructor(data?: PartialMessage<CreateHoldingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CreateHoldingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateHoldingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateHoldingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateHoldingResponse;

  static equals(a: CreateHoldingResponse | PlainMessage<CreateHoldingResponse> | undefined, b: CreateHoldingResponse | PlainMessage<CreateHoldingResponse> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateHoldingRequest
 */
export declare class UpdateHoldingRequest extends Message<UpdateHoldingRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: v1.Holding holding = 2;
   */
  holding?: Holding;

  constructor(data?: PartialMessage<UpdateHoldingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateHoldingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateHoldingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateHoldingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateHoldingRequest;

  static equals(a: UpdateHoldingRequest | PlainMessage<UpdateHoldingRequest> | undefined, b: UpdateHoldingRequest | PlainMessage<UpdateHoldingRequest> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateHoldingResponse
 */
export declare class UpdateHoldingResponse extends Message<UpdateHoldingResponse> {
  /**
   * @generated from field: v1.Holding holding = 1;
   */
  holding?: Holding;

  constructor(data?: PartialMessage<UpdateHoldingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateHoldingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateHoldingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateHoldingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateHoldingResponse;

  static equals(a: UpdateHoldingResponse | PlainMessage<UpdateHoldingResponse> | undefined, b: UpdateHoldingResponse | PlainMessage<UpdateHoldingResponse> | undefined): boolean;
}

/**
 * @generated from message v1.DeleteHoldingRequest
 */
export declare class DeleteHoldingRequest extends Message<DeleteHoldingRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<DeleteHoldingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DeleteHoldingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteHoldingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteHoldingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteHoldingRequest;

  static equals(a: DeleteHoldingRequest | PlainMessage<DeleteHoldingRequest> | undefined, b: DeleteHoldingRequest | PlainMessage<DeleteHoldingRequest> | undefined): boolean;
}

/**
 * @generated from message v1.DeleteHoldingResponse
 */
export declare class DeleteHoldingResponse extends Message<DeleteHoldingResponse> {
  constructor(data?: PartialMessage<DeleteHoldingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DeleteHoldingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteHoldingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteHoldingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteHoldingResponse;

  static equals(a: DeleteHoldingResponse | PlainMessage<DeleteHoldingResponse> | undefined, b: DeleteHoldingResponse | PlainMessage<DeleteHoldingResponse> | undefined): boolean;
}

