// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/holding.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateHoldingRequest, CreateHoldingResponse, DeleteHoldingRequest, DeleteHoldingResponse, ListHoldingsRequest, ListHoldingsResponse, UpdateHoldingRequest, UpdateHoldingResponse } from "./holding_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.HoldingService
 */
export declare const HoldingService: {
  readonly typeName: "v1.HoldingService",
  readonly methods: {
    /**
     * @generated from rpc v1.HoldingService.ListHoldings
     */
    readonly listHoldings: {
      readonly name: "ListHoldings",
      readonly I: typeof ListHoldingsRequest,
      readonly O: typeof ListHoldingsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.HoldingService.CreateHolding
     */
    readonly createHolding: {
      readonly name: "CreateHolding",
      readonly I: typeof CreateHoldingRequest,
      readonly O: typeof CreateHoldingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.HoldingService.UpdateHolding
     */
    readonly updateHolding: {
      readonly name: "UpdateHolding",
      readonly I: typeof UpdateHoldingRequest,
      readonly O: typeof UpdateHoldingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.HoldingService.DeleteHolding
     */
    readonly deleteHolding: {
      readonly name: "DeleteHolding",
      readonly I: typeof DeleteHoldingRequest,
      readonly O: typeof DeleteHoldingResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

