// @generated by protoc-gen-es v2.16.0
// @generated from file v1/holding.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/holding.proto.
 */
export declare const file_v1_holding: GenFile;

/**
 * Holding represents an asset position held within a specific account.
 *
 * @generated from message v1.Holding
 */
export declare type Holding = Message<"v1.Holding"> & {
  /**
   * Unique holding ID.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Associated account ID.
   *
   * @generated from field: int64 account_id = 2;
   */
  accountId: bigint;

  /**
   * Associated instrument ID.
   *
   * @generated from field: int64 instrument_id = 3;
   */
  instrumentId: bigint;

  /**
   * Name of the account holding this position.
   *
   * @generated from field: optional string account_name = 4;
   */
  accountName?: string | undefined;

  /**
   * Base currency code (e.g. "EUR", "USD").
   *
   * @generated from field: optional string currency = 5;
   */
  currency?: string | undefined;

  /**
   * Full name of the instrument (e.g. "iShares Core MSCI World UCITS ETF").
   *
   * @generated from field: optional string instrument_name = 6;
   */
  instrumentName?: string | undefined;

  /**
   * International Securities Identification Number (ISIN, e.g. "IE00B4L5Y983").
   *
   * @generated from field: optional string instrument_isin = 7;
   */
  instrumentIsin?: string | undefined;

  /**
   * Ticker symbol (e.g. "SWDA").
   *
   * @generated from field: optional string instrument_ticker = 8;
   */
  instrumentTicker?: string | undefined;

  /**
   * Instrument type (e.g. "etf", "etc", "stock", "bond").
   *
   * @generated from field: optional string instrument_type = 9;
   */
  instrumentType?: string | undefined;

  /**
   * Asset class (e.g. "equity", "bond", "commodity", "cash").
   *
   * @generated from field: optional string asset_class = 10;
   */
  assetClass?: string | undefined;

  /**
   * Total cost basis / invested capital in minor units (cents).
   *
   * @generated from field: int64 invested_minor = 11;
   */
  investedMinor: bigint;

  /**
   * Current market value in minor units (cents). May be 0 for new PAC accumulation plans.
   *
   * @generated from field: int64 value_minor = 12;
   */
  valueMinor: bigint;

  /**
   * Applicable capital gains tax rate in basis points (e.g. 2600 bps = 26.00%).
   *
   * @generated from field: int64 tax_bps = 13;
   */
  taxBps: bigint;

  /**
   * Calculated actual weight of this holding relative to total currency wealth in basis points.
   *
   * @generated from field: int64 actual_bps = 15;
   */
  actualBps: bigint;

  /**
   * Total Expense Ratio (TER) of the instrument in basis points (e.g. 20 bps = 0.20%).
   *
   * @generated from field: int64 ter_bps = 16;
   */
  terBps: bigint;

  /**
   * Whether this holding is part of an active PAC dollar-cost averaging plan.
   *
   * @generated from field: bool is_pac = 17;
   */
  isPac: boolean;

  /**
   * Share of account monthly PAC budget allocated to this holding in basis points (e.g. 6400 bps = 64.00%).
   *
   * @generated from field: int64 pac_bps = 18;
   */
  pacBps: bigint;

  /**
   * PAC deposit frequency (e.g. "monthly", "weekly", "biweekly", "quarterly").
   *
   * @generated from field: string pac_frequency = 19;
   */
  pacFrequency: string;

  /**
   * User strategic notes and context explaining the role of this holding to the AI Assistant.
   *
   * @generated from field: string notes = 20;
   */
  notes: string;
};

/**
 * Describes the message v1.Holding.
 * Use `create(HoldingSchema)` to create a new message.
 */
export declare const HoldingSchema: GenMessage<Holding>;

/**
 * @generated from message v1.ListHoldingsRequest
 */
export declare type ListHoldingsRequest = Message<"v1.ListHoldingsRequest"> & {
  /**
   * Optional sorting parameter e.g. "value:desc" or "name:asc".
   *
   * @generated from field: optional string sort = 1;
   */
  sort?: string | undefined;
};

/**
 * Describes the message v1.ListHoldingsRequest.
 * Use `create(ListHoldingsRequestSchema)` to create a new message.
 */
export declare const ListHoldingsRequestSchema: GenMessage<ListHoldingsRequest>;

/**
 * @generated from message v1.ListHoldingsResponse
 */
export declare type ListHoldingsResponse = Message<"v1.ListHoldingsResponse"> & {
  /**
   * @generated from field: repeated v1.Holding holdings = 1;
   */
  holdings: Holding[];
};

/**
 * Describes the message v1.ListHoldingsResponse.
 * Use `create(ListHoldingsResponseSchema)` to create a new message.
 */
export declare const ListHoldingsResponseSchema: GenMessage<ListHoldingsResponse>;

/**
 * @generated from message v1.CreateHoldingRequest
 */
export declare type CreateHoldingRequest = Message<"v1.CreateHoldingRequest"> & {
  /**
   * @generated from field: v1.Holding holding = 1;
   */
  holding?: Holding | undefined;
};

/**
 * Describes the message v1.CreateHoldingRequest.
 * Use `create(CreateHoldingRequestSchema)` to create a new message.
 */
export declare const CreateHoldingRequestSchema: GenMessage<CreateHoldingRequest>;

/**
 * @generated from message v1.CreateHoldingResponse
 */
export declare type CreateHoldingResponse = Message<"v1.CreateHoldingResponse"> & {
  /**
   * @generated from field: v1.Holding holding = 1;
   */
  holding?: Holding | undefined;
};

/**
 * Describes the message v1.CreateHoldingResponse.
 * Use `create(CreateHoldingResponseSchema)` to create a new message.
 */
export declare const CreateHoldingResponseSchema: GenMessage<CreateHoldingResponse>;

/**
 * HoldingPatch contains only fields that may be changed on an existing holding.
 * Optional presence distinguishes an omitted field from an explicit zero/false value.
 *
 * @generated from message v1.HoldingPatch
 */
export declare type HoldingPatch = Message<"v1.HoldingPatch"> & {
  /**
   * @generated from field: optional int64 id = 1;
   */
  id?: bigint | undefined;

  /**
   * @generated from field: optional int64 account_id = 2;
   */
  accountId?: bigint | undefined;

  /**
   * @generated from field: optional int64 instrument_id = 3;
   */
  instrumentId?: bigint | undefined;

  /**
   * @generated from field: optional int64 invested_minor = 11;
   */
  investedMinor?: bigint | undefined;

  /**
   * @generated from field: optional int64 value_minor = 12;
   */
  valueMinor?: bigint | undefined;

  /**
   * @generated from field: optional int64 tax_bps = 13;
   */
  taxBps?: bigint | undefined;

  /**
   * @generated from field: optional bool is_pac = 17;
   */
  isPac?: boolean | undefined;

  /**
   * @generated from field: optional int64 pac_bps = 18;
   */
  pacBps?: bigint | undefined;

  /**
   * @generated from field: optional string pac_frequency = 19;
   */
  pacFrequency?: string | undefined;

  /**
   * @generated from field: optional string notes = 20;
   */
  notes?: string | undefined;
};

/**
 * Describes the message v1.HoldingPatch.
 * Use `create(HoldingPatchSchema)` to create a new message.
 */
export declare const HoldingPatchSchema: GenMessage<HoldingPatch>;

/**
 * @generated from message v1.UpdateHoldingRequest
 */
export declare type UpdateHoldingRequest = Message<"v1.UpdateHoldingRequest"> & {
  /**
   * ID of the holding to update. If zero, holding.id is used instead.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Fields to update — only set what you want to change (e.g. pac_bps=0, is_pac=false).
   * All percentage/monetary values are in basis points: 10000=100%, 5000=50%, 0=0%.
   *
   * @generated from field: v1.HoldingPatch holding = 2;
   */
  holding?: HoldingPatch | undefined;
};

/**
 * Describes the message v1.UpdateHoldingRequest.
 * Use `create(UpdateHoldingRequestSchema)` to create a new message.
 */
export declare const UpdateHoldingRequestSchema: GenMessage<UpdateHoldingRequest>;

/**
 * @generated from message v1.UpdateHoldingResponse
 */
export declare type UpdateHoldingResponse = Message<"v1.UpdateHoldingResponse"> & {
  /**
   * @generated from field: v1.Holding holding = 1;
   */
  holding?: Holding | undefined;
};

/**
 * Describes the message v1.UpdateHoldingResponse.
 * Use `create(UpdateHoldingResponseSchema)` to create a new message.
 */
export declare const UpdateHoldingResponseSchema: GenMessage<UpdateHoldingResponse>;

/**
 * @generated from message v1.DeleteHoldingRequest
 */
export declare type DeleteHoldingRequest = Message<"v1.DeleteHoldingRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message v1.DeleteHoldingRequest.
 * Use `create(DeleteHoldingRequestSchema)` to create a new message.
 */
export declare const DeleteHoldingRequestSchema: GenMessage<DeleteHoldingRequest>;

/**
 * @generated from message v1.DeleteHoldingResponse
 */
export declare type DeleteHoldingResponse = Message<"v1.DeleteHoldingResponse"> & {
};

/**
 * Describes the message v1.DeleteHoldingResponse.
 * Use `create(DeleteHoldingResponseSchema)` to create a new message.
 */
export declare const DeleteHoldingResponseSchema: GenMessage<DeleteHoldingResponse>;

/**
 * HoldingService handles portfolio holding positions, allocation weights, and PAC plans.
 *
 * @generated from service v1.HoldingService
 */
export declare const HoldingService: GenService<{
  /**
   * List all asset holdings across accounts with calculated allocation percentages.
   *
   * @generated from rpc v1.HoldingService.ListHoldings
   */
  listHoldings: {
    methodKind: "unary";
    input: typeof ListHoldingsRequestSchema;
    output: typeof ListHoldingsResponseSchema;
  },
  /**
   * Add a new holding position or active PAC accumulation plan.
   *
   * @generated from rpc v1.HoldingService.CreateHolding
   */
  createHolding: {
    methodKind: "unary";
    input: typeof CreateHoldingRequestSchema;
    output: typeof CreateHoldingResponseSchema;
  },
  /**
   * Update an existing holding's allocation, PAC share, or flags. Pass id + a holding object with only the fields to change. To remove a holding from PAC: set is_pac=false and pac_bps=0.
   *
   * @generated from rpc v1.HoldingService.UpdateHolding
   */
  updateHolding: {
    methodKind: "unary";
    input: typeof UpdateHoldingRequestSchema;
    output: typeof UpdateHoldingResponseSchema;
  },
  /**
   * Delete a holding position.
   *
   * @generated from rpc v1.HoldingService.DeleteHolding
   */
  deleteHolding: {
    methodKind: "unary";
    input: typeof DeleteHoldingRequestSchema;
    output: typeof DeleteHoldingResponseSchema;
  },
}>;

