// @generated by protoc-gen-es v1.10.0
// @generated from file v1/instrument.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.Instrument
 */
export declare class Instrument extends Message<Instrument> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string isin = 2;
   */
  isin: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: optional string ticker = 4;
   */
  ticker?: string;

  /**
   * @generated from field: string instrument_type = 5;
   */
  instrumentType: string;

  /**
   * @generated from field: optional string provider = 6;
   */
  provider?: string;

  /**
   * @generated from field: optional string index_name = 7;
   */
  indexName?: string;

  /**
   * @generated from field: optional string investment_focus = 8;
   */
  investmentFocus?: string;

  /**
   * @generated from field: optional string asset_class = 9;
   */
  assetClass?: string;

  /**
   * @generated from field: optional string strategy = 10;
   */
  strategy?: string;

  /**
   * @generated from field: bool currency_hedged = 11;
   */
  currencyHedged: boolean;

  /**
   * @generated from field: bool starred = 12;
   */
  starred: boolean;

  /**
   * @generated from field: string data_status = 13;
   */
  dataStatus: string;

  /**
   * @generated from field: string distribution = 14;
   */
  distribution: string;

  /**
   * @generated from field: string replication = 15;
   */
  replication: string;

  /**
   * @generated from field: optional string domicile = 16;
   */
  domicile?: string;

  /**
   * @generated from field: string fund_currency = 17;
   */
  fundCurrency: string;

  /**
   * @generated from field: int64 ter_bps = 18;
   */
  terBps: bigint;

  /**
   * @generated from field: int64 fund_size_million = 19;
   */
  fundSizeMillion: bigint;

  /**
   * @generated from field: optional string inception_date = 20;
   */
  inceptionDate?: string;

  /**
   * @generated from field: optional int64 tracking_difference_bps = 21;
   */
  trackingDifferenceBps?: bigint;

  /**
   * @generated from field: optional int64 tracking_error_bps = 22;
   */
  trackingErrorBps?: bigint;

  /**
   * @generated from field: bool ucits = 23;
   */
  ucits: boolean;

  /**
   * @generated from field: optional string source_url = 24;
   */
  sourceUrl?: string;

  /**
   * @generated from field: optional string refreshed_at = 25;
   */
  refreshedAt?: string;

  /**
   * @generated from field: optional string enriched_at = 26;
   */
  enrichedAt?: string;

  constructor(data?: PartialMessage<Instrument>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Instrument";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Instrument;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Instrument;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Instrument;

  static equals(a: Instrument | PlainMessage<Instrument> | undefined, b: Instrument | PlainMessage<Instrument> | undefined): boolean;
}

/**
 * @generated from message v1.InstrumentAlternative
 */
export declare class InstrumentAlternative extends Message<InstrumentAlternative> {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument;

  /**
   * @generated from field: string match = 2;
   */
  match: string;

  /**
   * @generated from field: bool better = 3;
   */
  better: boolean;

  /**
   * @generated from field: double score = 4;
   */
  score: number;

  /**
   * @generated from field: repeated string reasons = 5;
   */
  reasons: string[];

  constructor(data?: PartialMessage<InstrumentAlternative>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.InstrumentAlternative";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InstrumentAlternative;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InstrumentAlternative;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InstrumentAlternative;

  static equals(a: InstrumentAlternative | PlainMessage<InstrumentAlternative> | undefined, b: InstrumentAlternative | PlainMessage<InstrumentAlternative> | undefined): boolean;
}

/**
 * @generated from message v1.RankWeights
 */
export declare class RankWeights extends Message<RankWeights> {
  /**
   * @generated from field: double cost = 1;
   */
  cost: number;

  /**
   * @generated from field: double tracking_difference = 2;
   */
  trackingDifference: number;

  /**
   * @generated from field: double tracking_error = 3;
   */
  trackingError: number;

  /**
   * @generated from field: double size = 4;
   */
  size: number;

  /**
   * @generated from field: double age = 5;
   */
  age: number;

  constructor(data?: PartialMessage<RankWeights>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RankWeights";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankWeights;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankWeights;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankWeights;

  static equals(a: RankWeights | PlainMessage<RankWeights> | undefined, b: RankWeights | PlainMessage<RankWeights> | undefined): boolean;
}

/**
 * @generated from message v1.RankCriteria
 */
export declare class RankCriteria extends Message<RankCriteria> {
  /**
   * @generated from field: string index_query = 1;
   */
  indexQuery: string;

  /**
   * @generated from field: string distribution = 2;
   */
  distribution: string;

  /**
   * @generated from field: repeated string replications = 3;
   */
  replications: string[];

  /**
   * @generated from field: repeated string domiciles = 4;
   */
  domiciles: string[];

  /**
   * @generated from field: optional int64 max_ter_bps = 5;
   */
  maxTerBps?: bigint;

  /**
   * @generated from field: int64 min_fund_size_million = 6;
   */
  minFundSizeMillion: bigint;

  /**
   * @generated from field: double min_age_years = 7;
   */
  minAgeYears: number;

  /**
   * @generated from field: v1.RankWeights weights = 8;
   */
  weights?: RankWeights;

  constructor(data?: PartialMessage<RankCriteria>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RankCriteria";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankCriteria;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankCriteria;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankCriteria;

  static equals(a: RankCriteria | PlainMessage<RankCriteria> | undefined, b: RankCriteria | PlainMessage<RankCriteria> | undefined): boolean;
}

/**
 * @generated from message v1.RankedInstrument
 */
export declare class RankedInstrument extends Message<RankedInstrument> {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument;

  /**
   * @generated from field: double total = 2;
   */
  total: number;

  /**
   * @generated from field: double cost = 3;
   */
  cost: number;

  /**
   * @generated from field: double tracking_difference = 4;
   */
  trackingDifference: number;

  /**
   * @generated from field: double tracking_error = 5;
   */
  trackingError: number;

  /**
   * @generated from field: double size = 6;
   */
  size: number;

  /**
   * @generated from field: double age = 7;
   */
  age: number;

  constructor(data?: PartialMessage<RankedInstrument>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RankedInstrument";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankedInstrument;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankedInstrument;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankedInstrument;

  static equals(a: RankedInstrument | PlainMessage<RankedInstrument> | undefined, b: RankedInstrument | PlainMessage<RankedInstrument> | undefined): boolean;
}

/**
 * @generated from message v1.EnrichmentProgress
 */
export declare class EnrichmentProgress extends Message<EnrichmentProgress> {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;

  /**
   * @generated from field: string phase = 2;
   */
  phase: string;

  /**
   * @generated from field: optional string current = 3;
   */
  current?: string;

  /**
   * @generated from field: int32 processed = 4;
   */
  processed: number;

  /**
   * @generated from field: int32 total = 5;
   */
  total: number;

  /**
   * @generated from field: optional int32 available = 6;
   */
  available?: number;

  /**
   * @generated from field: int32 enriched = 7;
   */
  enriched: number;

  /**
   * @generated from field: int32 skipped = 8;
   */
  skipped: number;

  /**
   * @generated from field: int32 failed = 9;
   */
  failed: number;

  /**
   * @generated from field: bool done = 10;
   */
  done: boolean;

  /**
   * @generated from field: optional string error = 11;
   */
  error?: string;

  constructor(data?: PartialMessage<EnrichmentProgress>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.EnrichmentProgress";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrichmentProgress;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrichmentProgress;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrichmentProgress;

  static equals(a: EnrichmentProgress | PlainMessage<EnrichmentProgress> | undefined, b: EnrichmentProgress | PlainMessage<EnrichmentProgress> | undefined): boolean;
}

/**
 * @generated from message v1.ListInstrumentsRequest
 */
export declare class ListInstrumentsRequest extends Message<ListInstrumentsRequest> {
  /**
   * @generated from field: optional string sort = 1;
   */
  sort?: string;

  constructor(data?: PartialMessage<ListInstrumentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListInstrumentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListInstrumentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListInstrumentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListInstrumentsRequest;

  static equals(a: ListInstrumentsRequest | PlainMessage<ListInstrumentsRequest> | undefined, b: ListInstrumentsRequest | PlainMessage<ListInstrumentsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListInstrumentsResponse
 */
export declare class ListInstrumentsResponse extends Message<ListInstrumentsResponse> {
  /**
   * @generated from field: repeated v1.Instrument instruments = 1;
   */
  instruments: Instrument[];

  constructor(data?: PartialMessage<ListInstrumentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListInstrumentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListInstrumentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListInstrumentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListInstrumentsResponse;

  static equals(a: ListInstrumentsResponse | PlainMessage<ListInstrumentsResponse> | undefined, b: ListInstrumentsResponse | PlainMessage<ListInstrumentsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.SearchInstrumentsRequest
 */
export declare class SearchInstrumentsRequest extends Message<SearchInstrumentsRequest> {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  constructor(data?: PartialMessage<SearchInstrumentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.SearchInstrumentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchInstrumentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchInstrumentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchInstrumentsRequest;

  static equals(a: SearchInstrumentsRequest | PlainMessage<SearchInstrumentsRequest> | undefined, b: SearchInstrumentsRequest | PlainMessage<SearchInstrumentsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.SearchInstrumentsResponse
 */
export declare class SearchInstrumentsResponse extends Message<SearchInstrumentsResponse> {
  /**
   * @generated from field: repeated v1.Instrument instruments = 1;
   */
  instruments: Instrument[];

  constructor(data?: PartialMessage<SearchInstrumentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.SearchInstrumentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SearchInstrumentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SearchInstrumentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SearchInstrumentsResponse;

  static equals(a: SearchInstrumentsResponse | PlainMessage<SearchInstrumentsResponse> | undefined, b: SearchInstrumentsResponse | PlainMessage<SearchInstrumentsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.SyncInstrumentCatalogRequest
 */
export declare class SyncInstrumentCatalogRequest extends Message<SyncInstrumentCatalogRequest> {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  constructor(data?: PartialMessage<SyncInstrumentCatalogRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.SyncInstrumentCatalogRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SyncInstrumentCatalogRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SyncInstrumentCatalogRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SyncInstrumentCatalogRequest;

  static equals(a: SyncInstrumentCatalogRequest | PlainMessage<SyncInstrumentCatalogRequest> | undefined, b: SyncInstrumentCatalogRequest | PlainMessage<SyncInstrumentCatalogRequest> | undefined): boolean;
}

/**
 * @generated from message v1.SyncInstrumentCatalogResponse
 */
export declare class SyncInstrumentCatalogResponse extends Message<SyncInstrumentCatalogResponse> {
  /**
   * @generated from field: int32 saved = 1;
   */
  saved: number;

  /**
   * @generated from field: int32 available = 2;
   */
  available: number;

  constructor(data?: PartialMessage<SyncInstrumentCatalogResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.SyncInstrumentCatalogResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SyncInstrumentCatalogResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SyncInstrumentCatalogResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SyncInstrumentCatalogResponse;

  static equals(a: SyncInstrumentCatalogResponse | PlainMessage<SyncInstrumentCatalogResponse> | undefined, b: SyncInstrumentCatalogResponse | PlainMessage<SyncInstrumentCatalogResponse> | undefined): boolean;
}

/**
 * @generated from message v1.EnrichInstrumentCatalogRequest
 */
export declare class EnrichInstrumentCatalogRequest extends Message<EnrichInstrumentCatalogRequest> {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;

  constructor(data?: PartialMessage<EnrichInstrumentCatalogRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.EnrichInstrumentCatalogRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrichInstrumentCatalogRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrichInstrumentCatalogRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrichInstrumentCatalogRequest;

  static equals(a: EnrichInstrumentCatalogRequest | PlainMessage<EnrichInstrumentCatalogRequest> | undefined, b: EnrichInstrumentCatalogRequest | PlainMessage<EnrichInstrumentCatalogRequest> | undefined): boolean;
}

/**
 * @generated from message v1.EnrichInstrumentCatalogResponse
 */
export declare class EnrichInstrumentCatalogResponse extends Message<EnrichInstrumentCatalogResponse> {
  /**
   * @generated from field: int32 enriched = 1;
   */
  enriched: number;

  /**
   * @generated from field: int32 failed = 2;
   */
  failed: number;

  constructor(data?: PartialMessage<EnrichInstrumentCatalogResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.EnrichInstrumentCatalogResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnrichInstrumentCatalogResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnrichInstrumentCatalogResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnrichInstrumentCatalogResponse;

  static equals(a: EnrichInstrumentCatalogResponse | PlainMessage<EnrichInstrumentCatalogResponse> | undefined, b: EnrichInstrumentCatalogResponse | PlainMessage<EnrichInstrumentCatalogResponse> | undefined): boolean;
}

/**
 * @generated from message v1.StreamInstrumentCatalogRequest
 */
export declare class StreamInstrumentCatalogRequest extends Message<StreamInstrumentCatalogRequest> {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;

  constructor(data?: PartialMessage<StreamInstrumentCatalogRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.StreamInstrumentCatalogRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamInstrumentCatalogRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamInstrumentCatalogRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamInstrumentCatalogRequest;

  static equals(a: StreamInstrumentCatalogRequest | PlainMessage<StreamInstrumentCatalogRequest> | undefined, b: StreamInstrumentCatalogRequest | PlainMessage<StreamInstrumentCatalogRequest> | undefined): boolean;
}

/**
 * @generated from message v1.CreateInstrumentRequest
 */
export declare class CreateInstrumentRequest extends Message<CreateInstrumentRequest> {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument;

  constructor(data?: PartialMessage<CreateInstrumentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CreateInstrumentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateInstrumentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateInstrumentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateInstrumentRequest;

  static equals(a: CreateInstrumentRequest | PlainMessage<CreateInstrumentRequest> | undefined, b: CreateInstrumentRequest | PlainMessage<CreateInstrumentRequest> | undefined): boolean;
}

/**
 * @generated from message v1.CreateInstrumentResponse
 */
export declare class CreateInstrumentResponse extends Message<CreateInstrumentResponse> {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument;

  constructor(data?: PartialMessage<CreateInstrumentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CreateInstrumentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateInstrumentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateInstrumentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateInstrumentResponse;

  static equals(a: CreateInstrumentResponse | PlainMessage<CreateInstrumentResponse> | undefined, b: CreateInstrumentResponse | PlainMessage<CreateInstrumentResponse> | undefined): boolean;
}

/**
 * @generated from message v1.LookupInstrumentRequest
 */
export declare class LookupInstrumentRequest extends Message<LookupInstrumentRequest> {
  /**
   * @generated from field: string query = 1;
   */
  query: string;

  constructor(data?: PartialMessage<LookupInstrumentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.LookupInstrumentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LookupInstrumentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LookupInstrumentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LookupInstrumentRequest;

  static equals(a: LookupInstrumentRequest | PlainMessage<LookupInstrumentRequest> | undefined, b: LookupInstrumentRequest | PlainMessage<LookupInstrumentRequest> | undefined): boolean;
}

/**
 * @generated from message v1.LookupInstrumentResponse
 */
export declare class LookupInstrumentResponse extends Message<LookupInstrumentResponse> {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument;

  constructor(data?: PartialMessage<LookupInstrumentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.LookupInstrumentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LookupInstrumentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LookupInstrumentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LookupInstrumentResponse;

  static equals(a: LookupInstrumentResponse | PlainMessage<LookupInstrumentResponse> | undefined, b: LookupInstrumentResponse | PlainMessage<LookupInstrumentResponse> | undefined): boolean;
}

/**
 * @generated from message v1.ImportInstrumentsRequest
 */
export declare class ImportInstrumentsRequest extends Message<ImportInstrumentsRequest> {
  /**
   * @generated from field: repeated string isins = 1;
   */
  isins: string[];

  constructor(data?: PartialMessage<ImportInstrumentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ImportInstrumentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportInstrumentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportInstrumentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportInstrumentsRequest;

  static equals(a: ImportInstrumentsRequest | PlainMessage<ImportInstrumentsRequest> | undefined, b: ImportInstrumentsRequest | PlainMessage<ImportInstrumentsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ImportInstrumentsResponse
 */
export declare class ImportInstrumentsResponse extends Message<ImportInstrumentsResponse> {
  /**
   * @generated from field: repeated v1.Instrument instruments = 1;
   */
  instruments: Instrument[];

  constructor(data?: PartialMessage<ImportInstrumentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ImportInstrumentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImportInstrumentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImportInstrumentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImportInstrumentsResponse;

  static equals(a: ImportInstrumentsResponse | PlainMessage<ImportInstrumentsResponse> | undefined, b: ImportInstrumentsResponse | PlainMessage<ImportInstrumentsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.DeleteInstrumentRequest
 */
export declare class DeleteInstrumentRequest extends Message<DeleteInstrumentRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<DeleteInstrumentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DeleteInstrumentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteInstrumentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteInstrumentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteInstrumentRequest;

  static equals(a: DeleteInstrumentRequest | PlainMessage<DeleteInstrumentRequest> | undefined, b: DeleteInstrumentRequest | PlainMessage<DeleteInstrumentRequest> | undefined): boolean;
}

/**
 * @generated from message v1.DeleteInstrumentResponse
 */
export declare class DeleteInstrumentResponse extends Message<DeleteInstrumentResponse> {
  constructor(data?: PartialMessage<DeleteInstrumentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DeleteInstrumentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteInstrumentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteInstrumentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteInstrumentResponse;

  static equals(a: DeleteInstrumentResponse | PlainMessage<DeleteInstrumentResponse> | undefined, b: DeleteInstrumentResponse | PlainMessage<DeleteInstrumentResponse> | undefined): boolean;
}

/**
 * @generated from message v1.StarInstrumentRequest
 */
export declare class StarInstrumentRequest extends Message<StarInstrumentRequest> {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: bool starred = 2;
   */
  starred: boolean;

  constructor(data?: PartialMessage<StarInstrumentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.StarInstrumentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StarInstrumentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StarInstrumentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StarInstrumentRequest;

  static equals(a: StarInstrumentRequest | PlainMessage<StarInstrumentRequest> | undefined, b: StarInstrumentRequest | PlainMessage<StarInstrumentRequest> | undefined): boolean;
}

/**
 * @generated from message v1.StarInstrumentResponse
 */
export declare class StarInstrumentResponse extends Message<StarInstrumentResponse> {
  constructor(data?: PartialMessage<StarInstrumentResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.StarInstrumentResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StarInstrumentResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StarInstrumentResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StarInstrumentResponse;

  static equals(a: StarInstrumentResponse | PlainMessage<StarInstrumentResponse> | undefined, b: StarInstrumentResponse | PlainMessage<StarInstrumentResponse> | undefined): boolean;
}

/**
 * @generated from message v1.GetInstrumentAlternativesRequest
 */
export declare class GetInstrumentAlternativesRequest extends Message<GetInstrumentAlternativesRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<GetInstrumentAlternativesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetInstrumentAlternativesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetInstrumentAlternativesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetInstrumentAlternativesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetInstrumentAlternativesRequest;

  static equals(a: GetInstrumentAlternativesRequest | PlainMessage<GetInstrumentAlternativesRequest> | undefined, b: GetInstrumentAlternativesRequest | PlainMessage<GetInstrumentAlternativesRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GetInstrumentAlternativesResponse
 */
export declare class GetInstrumentAlternativesResponse extends Message<GetInstrumentAlternativesResponse> {
  /**
   * @generated from field: repeated v1.InstrumentAlternative alternatives = 1;
   */
  alternatives: InstrumentAlternative[];

  constructor(data?: PartialMessage<GetInstrumentAlternativesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetInstrumentAlternativesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetInstrumentAlternativesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetInstrumentAlternativesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetInstrumentAlternativesResponse;

  static equals(a: GetInstrumentAlternativesResponse | PlainMessage<GetInstrumentAlternativesResponse> | undefined, b: GetInstrumentAlternativesResponse | PlainMessage<GetInstrumentAlternativesResponse> | undefined): boolean;
}

/**
 * @generated from message v1.RankInstrumentsRequest
 */
export declare class RankInstrumentsRequest extends Message<RankInstrumentsRequest> {
  /**
   * @generated from field: v1.RankCriteria criteria = 1;
   */
  criteria?: RankCriteria;

  constructor(data?: PartialMessage<RankInstrumentsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RankInstrumentsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankInstrumentsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankInstrumentsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankInstrumentsRequest;

  static equals(a: RankInstrumentsRequest | PlainMessage<RankInstrumentsRequest> | undefined, b: RankInstrumentsRequest | PlainMessage<RankInstrumentsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.RankInstrumentsResponse
 */
export declare class RankInstrumentsResponse extends Message<RankInstrumentsResponse> {
  /**
   * @generated from field: repeated v1.RankedInstrument ranked_instruments = 1;
   */
  rankedInstruments: RankedInstrument[];

  constructor(data?: PartialMessage<RankInstrumentsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RankInstrumentsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RankInstrumentsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RankInstrumentsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RankInstrumentsResponse;

  static equals(a: RankInstrumentsResponse | PlainMessage<RankInstrumentsResponse> | undefined, b: RankInstrumentsResponse | PlainMessage<RankInstrumentsResponse> | undefined): boolean;
}

