// @generated by protoc-gen-es v1.10.0
// @generated from file v1/instrument.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.Instrument
 */
export const Instrument = /*@__PURE__*/ proto3.makeMessageType(
  "v1.Instrument",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "isin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "ticker", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "instrument_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 7, name: "index_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "investment_focus", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "asset_class", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "strategy", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 11, name: "currency_hedged", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 12, name: "starred", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "data_status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "distribution", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 15, name: "replication", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "domicile", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 17, name: "fund_currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 18, name: "ter_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 19, name: "fund_size_million", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 20, name: "inception_date", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 21, name: "tracking_difference_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 22, name: "tracking_error_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 23, name: "ucits", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 24, name: "source_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 25, name: "refreshed_at", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 26, name: "enriched_at", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message v1.InstrumentAlternative
 */
export const InstrumentAlternative = /*@__PURE__*/ proto3.makeMessageType(
  "v1.InstrumentAlternative",
  () => [
    { no: 1, name: "instrument", kind: "message", T: Instrument },
    { no: 2, name: "match", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "better", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "score", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "reasons", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message v1.RankWeights
 */
export const RankWeights = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RankWeights",
  () => [
    { no: 1, name: "cost", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "tracking_difference", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "tracking_error", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "size", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "age", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message v1.RankCriteria
 */
export const RankCriteria = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RankCriteria",
  () => [
    { no: 1, name: "index_query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "distribution", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "replications", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "domiciles", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 5, name: "max_ter_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    { no: 6, name: "min_fund_size_million", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "min_age_years", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "weights", kind: "message", T: RankWeights },
  ],
);

/**
 * @generated from message v1.RankedInstrument
 */
export const RankedInstrument = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RankedInstrument",
  () => [
    { no: 1, name: "instrument", kind: "message", T: Instrument },
    { no: 2, name: "total", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "cost", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "tracking_difference", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "tracking_error", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "size", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "age", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message v1.EnrichmentProgress
 */
export const EnrichmentProgress = /*@__PURE__*/ proto3.makeMessageType(
  "v1.EnrichmentProgress",
  () => [
    { no: 1, name: "mode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "phase", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "current", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "processed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "total", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "available", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true },
    { no: 7, name: "enriched", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "skipped", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "failed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "done", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 11, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message v1.ListInstrumentsRequest
 */
export const ListInstrumentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListInstrumentsRequest",
  () => [
    { no: 1, name: "sort", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message v1.ListInstrumentsResponse
 */
export const ListInstrumentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListInstrumentsResponse",
  () => [
    { no: 1, name: "instruments", kind: "message", T: Instrument, repeated: true },
  ],
);

/**
 * @generated from message v1.SearchInstrumentsRequest
 */
export const SearchInstrumentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.SearchInstrumentsRequest",
  () => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.SearchInstrumentsResponse
 */
export const SearchInstrumentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.SearchInstrumentsResponse",
  () => [
    { no: 1, name: "instruments", kind: "message", T: Instrument, repeated: true },
  ],
);

/**
 * @generated from message v1.SyncInstrumentCatalogRequest
 */
export const SyncInstrumentCatalogRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.SyncInstrumentCatalogRequest",
  () => [
    { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.SyncInstrumentCatalogResponse
 */
export const SyncInstrumentCatalogResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.SyncInstrumentCatalogResponse",
  () => [
    { no: 1, name: "saved", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "available", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.EnrichInstrumentCatalogRequest
 */
export const EnrichInstrumentCatalogRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.EnrichInstrumentCatalogRequest",
  () => [
    { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.EnrichInstrumentCatalogResponse
 */
export const EnrichInstrumentCatalogResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.EnrichInstrumentCatalogResponse",
  () => [
    { no: 1, name: "enriched", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "failed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.StreamInstrumentCatalogRequest
 */
export const StreamInstrumentCatalogRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StreamInstrumentCatalogRequest",
  () => [
    { no: 1, name: "mode", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.CreateInstrumentRequest
 */
export const CreateInstrumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CreateInstrumentRequest",
  () => [
    { no: 1, name: "instrument", kind: "message", T: Instrument },
  ],
);

/**
 * @generated from message v1.CreateInstrumentResponse
 */
export const CreateInstrumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CreateInstrumentResponse",
  () => [
    { no: 1, name: "instrument", kind: "message", T: Instrument },
  ],
);

/**
 * @generated from message v1.LookupInstrumentRequest
 */
export const LookupInstrumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.LookupInstrumentRequest",
  () => [
    { no: 1, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.LookupInstrumentResponse
 */
export const LookupInstrumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.LookupInstrumentResponse",
  () => [
    { no: 1, name: "instrument", kind: "message", T: Instrument },
  ],
);

/**
 * @generated from message v1.ImportInstrumentsRequest
 */
export const ImportInstrumentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ImportInstrumentsRequest",
  () => [
    { no: 1, name: "isins", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message v1.ImportInstrumentsResponse
 */
export const ImportInstrumentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ImportInstrumentsResponse",
  () => [
    { no: 1, name: "instruments", kind: "message", T: Instrument, repeated: true },
  ],
);

/**
 * @generated from message v1.DeleteInstrumentRequest
 */
export const DeleteInstrumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DeleteInstrumentRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.DeleteInstrumentResponse
 */
export const DeleteInstrumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DeleteInstrumentResponse",
  [],
);

/**
 * @generated from message v1.StarInstrumentRequest
 */
export const StarInstrumentRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StarInstrumentRequest",
  () => [
    { no: 1, name: "isin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "starred", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message v1.StarInstrumentResponse
 */
export const StarInstrumentResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StarInstrumentResponse",
  [],
);

/**
 * @generated from message v1.GetInstrumentAlternativesRequest
 */
export const GetInstrumentAlternativesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GetInstrumentAlternativesRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.GetInstrumentAlternativesResponse
 */
export const GetInstrumentAlternativesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GetInstrumentAlternativesResponse",
  () => [
    { no: 1, name: "alternatives", kind: "message", T: InstrumentAlternative, repeated: true },
  ],
);

/**
 * @generated from message v1.RankInstrumentsRequest
 */
export const RankInstrumentsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RankInstrumentsRequest",
  () => [
    { no: 1, name: "criteria", kind: "message", T: RankCriteria },
  ],
);

/**
 * @generated from message v1.RankInstrumentsResponse
 */
export const RankInstrumentsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RankInstrumentsResponse",
  () => [
    { no: 1, name: "ranked_instruments", kind: "message", T: RankedInstrument, repeated: true },
  ],
);

