// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/instrument.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateInstrumentRequest, CreateInstrumentResponse, DeleteInstrumentRequest, DeleteInstrumentResponse, EnrichInstrumentCatalogRequest, EnrichInstrumentCatalogResponse, EnrichmentProgress, GetInstrumentAlternativesRequest, GetInstrumentAlternativesResponse, ImportInstrumentsRequest, ImportInstrumentsResponse, ListInstrumentsRequest, ListInstrumentsResponse, LookupInstrumentRequest, LookupInstrumentResponse, RankInstrumentsRequest, RankInstrumentsResponse, SearchInstrumentsRequest, SearchInstrumentsResponse, StarInstrumentRequest, StarInstrumentResponse, StreamInstrumentCatalogRequest, SyncInstrumentCatalogRequest, SyncInstrumentCatalogResponse } from "./instrument_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * InstrumentService provides access to the 4,000+ ETF catalog, searching, enrichment, and ETF alternative ranking.
 *
 * @generated from service v1.InstrumentService
 */
export const InstrumentService = {
  typeName: "v1.InstrumentService",
  methods: {
    /**
     * List saved instruments in the user catalog.
     *
     * @generated from rpc v1.InstrumentService.ListInstruments
     */
    listInstruments: {
      name: "ListInstruments",
      I: ListInstrumentsRequest,
      O: ListInstrumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Search the 4,000+ ETF catalog by ISIN, ticker, name, or index.
     *
     * @generated from rpc v1.InstrumentService.SearchInstruments
     */
    searchInstruments: {
      name: "SearchInstruments",
      I: SearchInstrumentsRequest,
      O: SearchInstrumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Sync the latest instrument catalog list from justETF.
     *
     * @generated from rpc v1.InstrumentService.SyncInstrumentCatalog
     */
    syncInstrumentCatalog: {
      name: "SyncInstrumentCatalog",
      I: SyncInstrumentCatalogRequest,
      O: SyncInstrumentCatalogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Enrich catalog items with TER, AUM, tracking error, and replication profile data.
     *
     * @generated from rpc v1.InstrumentService.EnrichInstrumentCatalog
     */
    enrichInstrumentCatalog: {
      name: "EnrichInstrumentCatalog",
      I: EnrichInstrumentCatalogRequest,
      O: EnrichInstrumentCatalogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stream catalog enrichment progress events over gRPC server streaming.
     *
     * @generated from rpc v1.InstrumentService.StreamInstrumentCatalog
     */
    streamInstrumentCatalog: {
      name: "StreamInstrumentCatalog",
      I: StreamInstrumentCatalogRequest,
      O: EnrichmentProgress,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * Manually add a custom instrument.
     *
     * @generated from rpc v1.InstrumentService.CreateInstrument
     */
    createInstrument: {
      name: "CreateInstrument",
      I: CreateInstrumentRequest,
      O: CreateInstrumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lookup security details by ISIN or query.
     *
     * @generated from rpc v1.InstrumentService.LookupInstrument
     */
    lookupInstrument: {
      name: "LookupInstrument",
      I: LookupInstrumentRequest,
      O: LookupInstrumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Batch import securities by ISIN list.
     *
     * @generated from rpc v1.InstrumentService.ImportInstruments
     */
    importInstruments: {
      name: "ImportInstruments",
      I: ImportInstrumentsRequest,
      O: ImportInstrumentsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an instrument from the catalog.
     *
     * @generated from rpc v1.InstrumentService.DeleteInstrument
     */
    deleteInstrument: {
      name: "DeleteInstrument",
      I: DeleteInstrumentRequest,
      O: DeleteInstrumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Star or unstar an instrument for quick tracking.
     *
     * @generated from rpc v1.InstrumentService.StarInstrument
     */
    starInstrument: {
      name: "StarInstrument",
      I: StarInstrumentRequest,
      O: StarInstrumentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Find cheaper or better-performing alternative ETFs for a target instrument.
     *
     * @generated from rpc v1.InstrumentService.GetInstrumentAlternatives
     */
    getInstrumentAlternatives: {
      name: "GetInstrumentAlternatives",
      I: GetInstrumentAlternativesRequest,
      O: GetInstrumentAlternativesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Rank ETF candidates according to TER cost, tracking metrics, AUM size, and fund age.
     *
     * @generated from rpc v1.InstrumentService.RankInstruments
     */
    rankInstruments: {
      name: "RankInstruments",
      I: RankInstrumentsRequest,
      O: RankInstrumentsResponse,
      kind: MethodKind.Unary,
    },
  }
};

