// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/instrument.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateInstrumentRequest, CreateInstrumentResponse, DeleteInstrumentRequest, DeleteInstrumentResponse, EnrichInstrumentCatalogRequest, EnrichInstrumentCatalogResponse, EnrichmentProgress, GetInstrumentAlternativesRequest, GetInstrumentAlternativesResponse, ImportInstrumentsRequest, ImportInstrumentsResponse, ListInstrumentsRequest, ListInstrumentsResponse, LookupInstrumentRequest, LookupInstrumentResponse, RankInstrumentsRequest, RankInstrumentsResponse, SearchInstrumentsRequest, SearchInstrumentsResponse, StarInstrumentRequest, StarInstrumentResponse, StreamInstrumentCatalogRequest, SyncInstrumentCatalogRequest, SyncInstrumentCatalogResponse } from "./instrument_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.InstrumentService
 */
export declare const InstrumentService: {
  readonly typeName: "v1.InstrumentService",
  readonly methods: {
    /**
     * @generated from rpc v1.InstrumentService.ListInstruments
     */
    readonly listInstruments: {
      readonly name: "ListInstruments",
      readonly I: typeof ListInstrumentsRequest,
      readonly O: typeof ListInstrumentsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.SearchInstruments
     */
    readonly searchInstruments: {
      readonly name: "SearchInstruments",
      readonly I: typeof SearchInstrumentsRequest,
      readonly O: typeof SearchInstrumentsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.SyncInstrumentCatalog
     */
    readonly syncInstrumentCatalog: {
      readonly name: "SyncInstrumentCatalog",
      readonly I: typeof SyncInstrumentCatalogRequest,
      readonly O: typeof SyncInstrumentCatalogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.EnrichInstrumentCatalog
     */
    readonly enrichInstrumentCatalog: {
      readonly name: "EnrichInstrumentCatalog",
      readonly I: typeof EnrichInstrumentCatalogRequest,
      readonly O: typeof EnrichInstrumentCatalogResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.StreamInstrumentCatalog
     */
    readonly streamInstrumentCatalog: {
      readonly name: "StreamInstrumentCatalog",
      readonly I: typeof StreamInstrumentCatalogRequest,
      readonly O: typeof EnrichmentProgress,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc v1.InstrumentService.CreateInstrument
     */
    readonly createInstrument: {
      readonly name: "CreateInstrument",
      readonly I: typeof CreateInstrumentRequest,
      readonly O: typeof CreateInstrumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.LookupInstrument
     */
    readonly lookupInstrument: {
      readonly name: "LookupInstrument",
      readonly I: typeof LookupInstrumentRequest,
      readonly O: typeof LookupInstrumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.ImportInstruments
     */
    readonly importInstruments: {
      readonly name: "ImportInstruments",
      readonly I: typeof ImportInstrumentsRequest,
      readonly O: typeof ImportInstrumentsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.DeleteInstrument
     */
    readonly deleteInstrument: {
      readonly name: "DeleteInstrument",
      readonly I: typeof DeleteInstrumentRequest,
      readonly O: typeof DeleteInstrumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.StarInstrument
     */
    readonly starInstrument: {
      readonly name: "StarInstrument",
      readonly I: typeof StarInstrumentRequest,
      readonly O: typeof StarInstrumentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.GetInstrumentAlternatives
     */
    readonly getInstrumentAlternatives: {
      readonly name: "GetInstrumentAlternatives",
      readonly I: typeof GetInstrumentAlternativesRequest,
      readonly O: typeof GetInstrumentAlternativesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.InstrumentService.RankInstruments
     */
    readonly rankInstruments: {
      readonly name: "RankInstruments",
      readonly I: typeof RankInstrumentsRequest,
      readonly O: typeof RankInstrumentsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

