// @generated by protoc-gen-es v2.16.0
// @generated from file v1/instrument.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/instrument.proto.
 */
export declare const file_v1_instrument: GenFile;

/**
 * Instrument represents a tradeable security (ETF, ETC, ETN, stock, bond) from the 4,000+ ETF catalog.
 *
 * @generated from message v1.Instrument
 */
export declare type Instrument = Message<"v1.Instrument"> & {
  /**
   * Unique instrument ID.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * ISIN security identifier (e.g. "IE00B4L5Y983").
   *
   * @generated from field: string isin = 2;
   */
  isin: string;

  /**
   * Full security name (e.g. "iShares Core MSCI World UCITS ETF USD (Acc)").
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Ticker symbol (e.g. "SWDA", "EUNL").
   *
   * @generated from field: optional string ticker = 4;
   */
  ticker?: string | undefined;

  /**
   * Instrument type: "etf", "etc", "etn", "etp", "fund", "stock", "bond", "crypto", "commodity", "real_estate".
   *
   * @generated from field: string instrument_type = 5;
   */
  instrumentType: string;

  /**
   * Fund provider or manager (e.g. "iShares", "Vanguard", "Xtrackers", "Amundi", "Invesco").
   *
   * @generated from field: optional string provider = 6;
   */
  provider?: string | undefined;

  /**
   * Tracked benchmark index name (e.g. "MSCI World", "S&P 500", "FTSE All-World").
   *
   * @generated from field: optional string index_name = 7;
   */
  indexName?: string | undefined;

  /**
   * Primary investment focus (e.g. "Equity", "Bonds", "Precious Metals").
   *
   * @generated from field: optional string investment_focus = 8;
   */
  investmentFocus?: string | undefined;

  /**
   * Broad asset class: "equity", "bond", "commodity", "real_estate", "monetary", "crypto", "mixed", "other".
   *
   * @generated from field: optional string asset_class = 9;
   */
  assetClass?: string | undefined;

  /**
   * Fund strategy or style (e.g. "Blend", "Value", "Growth", "Dividend").
   *
   * @generated from field: optional string strategy = 10;
   */
  strategy?: string | undefined;

  /**
   * Whether the fund is currency-hedged to the fund currency.
   *
   * @generated from field: bool currency_hedged = 11;
   */
  currencyHedged: boolean;

  /**
   * Whether the user starred this instrument for quick tracking.
   *
   * @generated from field: bool starred = 12;
   */
  starred: boolean;

  /**
   * Catalog enrichment status: "catalog", "enriched", "failed".
   *
   * @generated from field: string data_status = 13;
   */
  dataStatus: string;

  /**
   * Fund dividend distribution policy: "accumulating" or "distributing".
   *
   * @generated from field: string distribution = 14;
   */
  distribution: string;

  /**
   * Index replication method: "physical_full", "physical_sampled", or "synthetic_unfunded".
   *
   * @generated from field: string replication = 15;
   */
  replication: string;

  /**
   * Country of fund domicile (e.g. "Ireland", "Luxembourg").
   *
   * @generated from field: optional string domicile = 16;
   */
  domicile?: string | undefined;

  /**
   * Fund base currency (e.g. "EUR", "USD", "GBP").
   *
   * @generated from field: string fund_currency = 17;
   */
  fundCurrency: string;

  /**
   * Total Expense Ratio (TER) in basis points (e.g. 20 bps = 0.20%, 15 bps = 0.15%).
   *
   * @generated from field: int64 ter_bps = 18;
   */
  terBps: bigint;

  /**
   * Total fund size / Assets Under Management (AUM) in millions of EUR.
   *
   * @generated from field: int64 fund_size_million = 19;
   */
  fundSizeMillion: bigint;

  /**
   * Inception date in YYYY-MM-DD format.
   *
   * @generated from field: optional string inception_date = 20;
   */
  inceptionDate?: string | undefined;

  /**
   * 1-year tracking difference vs benchmark in basis points (negative means outperformance).
   *
   * @generated from field: optional int64 tracking_difference_bps = 21;
   */
  trackingDifferenceBps?: bigint | undefined;

  /**
   * 1-year tracking error / volatility vs benchmark in basis points.
   *
   * @generated from field: optional int64 tracking_error_bps = 22;
   */
  trackingErrorBps?: bigint | undefined;

  /**
   * Whether the fund is a UCITS-compliant European regulated fund.
   *
   * @generated from field: bool ucits = 23;
   */
  ucits: boolean;

  /**
   * Source URL for the instrument profile.
   *
   * @generated from field: optional string source_url = 24;
   */
  sourceUrl?: string | undefined;

  /**
   * ISO timestamp of last catalog refresh.
   *
   * @generated from field: optional string refreshed_at = 25;
   */
  refreshedAt?: string | undefined;
};

/**
 * Describes the message v1.Instrument.
 * Use `create(InstrumentSchema)` to create a new message.
 */
export declare const InstrumentSchema: GenMessage<Instrument>;

/**
 * InstrumentAlternative suggests cheaper or better-performing ETFs matching the same index exposure.
 *
 * @generated from message v1.InstrumentAlternative
 */
export declare type InstrumentAlternative = Message<"v1.InstrumentAlternative"> & {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument | undefined;

  /**
   * Match quality: "exact_index" or "same_exposure".
   *
   * @generated from field: string match = 2;
   */
  match: string;

  /**
   * Whether this alternative has lower TER or better tracking metrics than the query instrument.
   *
   * @generated from field: bool better = 3;
   */
  better: boolean;

  /**
   * Overall composite rank score (0.0 to 100.0).
   *
   * @generated from field: double score = 4;
   */
  score: number;

  /**
   * Explanatory reasons why this alternative is recommended (e.g. "0.08% lower TER", "€2,500m larger AUM").
   *
   * @generated from field: repeated string reasons = 5;
   */
  reasons: string[];
};

/**
 * Describes the message v1.InstrumentAlternative.
 * Use `create(InstrumentAlternativeSchema)` to create a new message.
 */
export declare const InstrumentAlternativeSchema: GenMessage<InstrumentAlternative>;

/**
 * RankWeights defines customization weights for instrument ranking.
 *
 * @generated from message v1.RankWeights
 */
export declare type RankWeights = Message<"v1.RankWeights"> & {
  /**
   * @generated from field: double cost = 1;
   */
  cost: number;

  /**
   * @generated from field: double tracking_difference = 2;
   */
  trackingDifference: number;

  /**
   * @generated from field: double tracking_error = 3;
   */
  trackingError: number;

  /**
   * @generated from field: double size = 4;
   */
  size: number;

  /**
   * @generated from field: double age = 5;
   */
  age: number;
};

/**
 * Describes the message v1.RankWeights.
 * Use `create(RankWeightsSchema)` to create a new message.
 */
export declare const RankWeightsSchema: GenMessage<RankWeights>;

/**
 * RankCriteria specifies filtering and ranking parameters for ETF comparison.
 *
 * @generated from message v1.RankCriteria
 */
export declare type RankCriteria = Message<"v1.RankCriteria"> & {
  /**
   * Target index or exposure query (e.g. "MSCI World", "S&P 500").
   *
   * @generated from field: string index_query = 1;
   */
  indexQuery: string;

  /**
   * Filter by distribution policy: "accumulating", "distributing", or "" for any.
   *
   * @generated from field: string distribution = 2;
   */
  distribution: string;

  /**
   * Filter by replication methods e.g. ["physical_full", "physical_sampled"].
   *
   * @generated from field: repeated string replications = 3;
   */
  replications: string[];

  /**
   * Filter by domiciles e.g. ["Ireland", "Luxembourg"].
   *
   * @generated from field: repeated string domiciles = 4;
   */
  domiciles: string[];

  /**
   * Maximum TER in basis points (e.g. 20 bps = 0.20%).
   *
   * @generated from field: optional int64 max_ter_bps = 5;
   */
  maxTerBps?: bigint | undefined;

  /**
   * Minimum AUM / fund size in millions of EUR.
   *
   * @generated from field: int64 min_fund_size_million = 6;
   */
  minFundSizeMillion: bigint;

  /**
   * Minimum fund age in years.
   *
   * @generated from field: double min_age_years = 7;
   */
  minAgeYears: number;

  /**
   * Scoring weights customization.
   *
   * @generated from field: v1.RankWeights weights = 8;
   */
  weights?: RankWeights | undefined;

  /**
   * Filter by asset classes e.g. ["equity", "bond", "commodity"].
   *
   * @generated from field: repeated string asset_classes = 9;
   */
  assetClasses: string[];

  /**
   * Filter by multiple distribution policies e.g. ["accumulating"], ["distributing"].
   *
   * @generated from field: repeated string distributions = 10;
   */
  distributions: string[];

  /**
   * Filter by fund currencies e.g. ["EUR", "USD"].
   *
   * @generated from field: repeated string fund_currencies = 11;
   */
  fundCurrencies: string[];

  /**
   * Filter by providers / issuers e.g. ["iShares", "Vanguard"].
   *
   * @generated from field: repeated string providers = 12;
   */
  providers: string[];

  /**
   * Filter by currency hedging status.
   *
   * @generated from field: optional bool currency_hedged = 13;
   */
  currencyHedged?: boolean | undefined;
};

/**
 * Describes the message v1.RankCriteria.
 * Use `create(RankCriteriaSchema)` to create a new message.
 */
export declare const RankCriteriaSchema: GenMessage<RankCriteria>;

/**
 * RankedInstrument represents an ETF evaluated and scored against ranking criteria.
 *
 * @generated from message v1.RankedInstrument
 */
export declare type RankedInstrument = Message<"v1.RankedInstrument"> & {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument | undefined;

  /**
   * Overall composite score.
   *
   * @generated from field: double total = 2;
   */
  total: number;

  /**
   * Sub-scores.
   *
   * @generated from field: double cost = 3;
   */
  cost: number;

  /**
   * @generated from field: double tracking_difference = 4;
   */
  trackingDifference: number;

  /**
   * @generated from field: double tracking_error = 5;
   */
  trackingError: number;

  /**
   * @generated from field: double size = 6;
   */
  size: number;

  /**
   * @generated from field: double age = 7;
   */
  age: number;
};

/**
 * Describes the message v1.RankedInstrument.
 * Use `create(RankedInstrumentSchema)` to create a new message.
 */
export declare const RankedInstrumentSchema: GenMessage<RankedInstrument>;

/**
 * @generated from message v1.EnrichmentProgress
 */
export declare type EnrichmentProgress = Message<"v1.EnrichmentProgress"> & {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;

  /**
   * @generated from field: string phase = 2;
   */
  phase: string;

  /**
   * @generated from field: optional string current = 3;
   */
  current?: string | undefined;

  /**
   * @generated from field: int32 processed = 4;
   */
  processed: number;

  /**
   * @generated from field: int32 total = 5;
   */
  total: number;

  /**
   * @generated from field: optional int32 available = 6;
   */
  available?: number | undefined;

  /**
   * @generated from field: int32 enriched = 7;
   */
  enriched: number;

  /**
   * @generated from field: int32 skipped = 8;
   */
  skipped: number;

  /**
   * @generated from field: int32 failed = 9;
   */
  failed: number;

  /**
   * @generated from field: bool done = 10;
   */
  done: boolean;

  /**
   * @generated from field: optional string error = 11;
   */
  error?: string | undefined;
};

/**
 * Describes the message v1.EnrichmentProgress.
 * Use `create(EnrichmentProgressSchema)` to create a new message.
 */
export declare const EnrichmentProgressSchema: GenMessage<EnrichmentProgress>;

/**
 * @generated from message v1.ListInstrumentsRequest
 */
export declare type ListInstrumentsRequest = Message<"v1.ListInstrumentsRequest"> & {
  /**
   * @generated from field: optional string sort = 1;
   */
  sort?: string | undefined;
};

/**
 * Describes the message v1.ListInstrumentsRequest.
 * Use `create(ListInstrumentsRequestSchema)` to create a new message.
 */
export declare const ListInstrumentsRequestSchema: GenMessage<ListInstrumentsRequest>;

/**
 * @generated from message v1.ListInstrumentsResponse
 */
export declare type ListInstrumentsResponse = Message<"v1.ListInstrumentsResponse"> & {
  /**
   * @generated from field: repeated v1.Instrument instruments = 1;
   */
  instruments: Instrument[];
};

/**
 * Describes the message v1.ListInstrumentsResponse.
 * Use `create(ListInstrumentsResponseSchema)` to create a new message.
 */
export declare const ListInstrumentsResponseSchema: GenMessage<ListInstrumentsResponse>;

/**
 * @generated from message v1.SearchInstrumentsRequest
 */
export declare type SearchInstrumentsRequest = Message<"v1.SearchInstrumentsRequest"> & {
  /**
   * Search term e.g. "MSCI World", "S&P 500", "Gold", "IE00B4L5Y983", "iShares".
   *
   * @generated from field: string query = 1;
   */
  query: string;
};

/**
 * Describes the message v1.SearchInstrumentsRequest.
 * Use `create(SearchInstrumentsRequestSchema)` to create a new message.
 */
export declare const SearchInstrumentsRequestSchema: GenMessage<SearchInstrumentsRequest>;

/**
 * @generated from message v1.SearchInstrumentsResponse
 */
export declare type SearchInstrumentsResponse = Message<"v1.SearchInstrumentsResponse"> & {
  /**
   * @generated from field: repeated v1.Instrument instruments = 1;
   */
  instruments: Instrument[];
};

/**
 * Describes the message v1.SearchInstrumentsResponse.
 * Use `create(SearchInstrumentsResponseSchema)` to create a new message.
 */
export declare const SearchInstrumentsResponseSchema: GenMessage<SearchInstrumentsResponse>;

/**
 * @generated from message v1.SyncInstrumentCatalogRequest
 */
export declare type SyncInstrumentCatalogRequest = Message<"v1.SyncInstrumentCatalogRequest"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;
};

/**
 * Describes the message v1.SyncInstrumentCatalogRequest.
 * Use `create(SyncInstrumentCatalogRequestSchema)` to create a new message.
 */
export declare const SyncInstrumentCatalogRequestSchema: GenMessage<SyncInstrumentCatalogRequest>;

/**
 * @generated from message v1.SyncInstrumentCatalogResponse
 */
export declare type SyncInstrumentCatalogResponse = Message<"v1.SyncInstrumentCatalogResponse"> & {
  /**
   * @generated from field: int32 saved = 1;
   */
  saved: number;

  /**
   * @generated from field: int32 available = 2;
   */
  available: number;
};

/**
 * Describes the message v1.SyncInstrumentCatalogResponse.
 * Use `create(SyncInstrumentCatalogResponseSchema)` to create a new message.
 */
export declare const SyncInstrumentCatalogResponseSchema: GenMessage<SyncInstrumentCatalogResponse>;

/**
 * @generated from message v1.EnrichInstrumentCatalogRequest
 */
export declare type EnrichInstrumentCatalogRequest = Message<"v1.EnrichInstrumentCatalogRequest"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;
};

/**
 * Describes the message v1.EnrichInstrumentCatalogRequest.
 * Use `create(EnrichInstrumentCatalogRequestSchema)` to create a new message.
 */
export declare const EnrichInstrumentCatalogRequestSchema: GenMessage<EnrichInstrumentCatalogRequest>;

/**
 * @generated from message v1.EnrichInstrumentCatalogResponse
 */
export declare type EnrichInstrumentCatalogResponse = Message<"v1.EnrichInstrumentCatalogResponse"> & {
  /**
   * @generated from field: int32 enriched = 1;
   */
  enriched: number;

  /**
   * @generated from field: int32 failed = 2;
   */
  failed: number;
};

/**
 * Describes the message v1.EnrichInstrumentCatalogResponse.
 * Use `create(EnrichInstrumentCatalogResponseSchema)` to create a new message.
 */
export declare const EnrichInstrumentCatalogResponseSchema: GenMessage<EnrichInstrumentCatalogResponse>;

/**
 * @generated from message v1.StreamInstrumentCatalogRequest
 */
export declare type StreamInstrumentCatalogRequest = Message<"v1.StreamInstrumentCatalogRequest"> & {
  /**
   * @generated from field: string mode = 1;
   */
  mode: string;
};

/**
 * Describes the message v1.StreamInstrumentCatalogRequest.
 * Use `create(StreamInstrumentCatalogRequestSchema)` to create a new message.
 */
export declare const StreamInstrumentCatalogRequestSchema: GenMessage<StreamInstrumentCatalogRequest>;

/**
 * @generated from message v1.WatchContinuousRefreshRequest
 */
export declare type WatchContinuousRefreshRequest = Message<"v1.WatchContinuousRefreshRequest"> & {
};

/**
 * Describes the message v1.WatchContinuousRefreshRequest.
 * Use `create(WatchContinuousRefreshRequestSchema)` to create a new message.
 */
export declare const WatchContinuousRefreshRequestSchema: GenMessage<WatchContinuousRefreshRequest>;

/**
 * @generated from message v1.RefreshTick
 */
export declare type RefreshTick = Message<"v1.RefreshTick"> & {
  /**
   * @generated from field: string ticker = 1;
   */
  ticker: string;

  /**
   * @generated from field: string isin = 2;
   */
  isin: string;

  /**
   * @generated from field: int32 refreshed_today = 3;
   */
  refreshedToday: number;

  /**
   * @generated from field: bool enabled = 4;
   */
  enabled: boolean;

  /**
   * idle | refreshing | waiting | error
   *
   * @generated from field: string phase = 5;
   */
  phase: string;

  /**
   * @generated from field: bool has_error = 6;
   */
  hasError: boolean;
};

/**
 * Describes the message v1.RefreshTick.
 * Use `create(RefreshTickSchema)` to create a new message.
 */
export declare const RefreshTickSchema: GenMessage<RefreshTick>;

/**
 * @generated from message v1.SetContinuousRefreshRequest
 */
export declare type SetContinuousRefreshRequest = Message<"v1.SetContinuousRefreshRequest"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;
};

/**
 * Describes the message v1.SetContinuousRefreshRequest.
 * Use `create(SetContinuousRefreshRequestSchema)` to create a new message.
 */
export declare const SetContinuousRefreshRequestSchema: GenMessage<SetContinuousRefreshRequest>;

/**
 * @generated from message v1.SetContinuousRefreshResponse
 */
export declare type SetContinuousRefreshResponse = Message<"v1.SetContinuousRefreshResponse"> & {
};

/**
 * Describes the message v1.SetContinuousRefreshResponse.
 * Use `create(SetContinuousRefreshResponseSchema)` to create a new message.
 */
export declare const SetContinuousRefreshResponseSchema: GenMessage<SetContinuousRefreshResponse>;

/**
 * @generated from message v1.CreateInstrumentRequest
 */
export declare type CreateInstrumentRequest = Message<"v1.CreateInstrumentRequest"> & {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument | undefined;
};

/**
 * Describes the message v1.CreateInstrumentRequest.
 * Use `create(CreateInstrumentRequestSchema)` to create a new message.
 */
export declare const CreateInstrumentRequestSchema: GenMessage<CreateInstrumentRequest>;

/**
 * @generated from message v1.CreateInstrumentResponse
 */
export declare type CreateInstrumentResponse = Message<"v1.CreateInstrumentResponse"> & {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument | undefined;
};

/**
 * Describes the message v1.CreateInstrumentResponse.
 * Use `create(CreateInstrumentResponseSchema)` to create a new message.
 */
export declare const CreateInstrumentResponseSchema: GenMessage<CreateInstrumentResponse>;

/**
 * @generated from message v1.LookupInstrumentRequest
 */
export declare type LookupInstrumentRequest = Message<"v1.LookupInstrumentRequest"> & {
  /**
   * @generated from field: string query = 1;
   */
  query: string;
};

/**
 * Describes the message v1.LookupInstrumentRequest.
 * Use `create(LookupInstrumentRequestSchema)` to create a new message.
 */
export declare const LookupInstrumentRequestSchema: GenMessage<LookupInstrumentRequest>;

/**
 * @generated from message v1.LookupInstrumentResponse
 */
export declare type LookupInstrumentResponse = Message<"v1.LookupInstrumentResponse"> & {
  /**
   * @generated from field: v1.Instrument instrument = 1;
   */
  instrument?: Instrument | undefined;
};

/**
 * Describes the message v1.LookupInstrumentResponse.
 * Use `create(LookupInstrumentResponseSchema)` to create a new message.
 */
export declare const LookupInstrumentResponseSchema: GenMessage<LookupInstrumentResponse>;

/**
 * @generated from message v1.ImportInstrumentsRequest
 */
export declare type ImportInstrumentsRequest = Message<"v1.ImportInstrumentsRequest"> & {
  /**
   * @generated from field: repeated string isins = 1;
   */
  isins: string[];
};

/**
 * Describes the message v1.ImportInstrumentsRequest.
 * Use `create(ImportInstrumentsRequestSchema)` to create a new message.
 */
export declare const ImportInstrumentsRequestSchema: GenMessage<ImportInstrumentsRequest>;

/**
 * @generated from message v1.ImportInstrumentsResponse
 */
export declare type ImportInstrumentsResponse = Message<"v1.ImportInstrumentsResponse"> & {
  /**
   * @generated from field: repeated v1.Instrument instruments = 1;
   */
  instruments: Instrument[];
};

/**
 * Describes the message v1.ImportInstrumentsResponse.
 * Use `create(ImportInstrumentsResponseSchema)` to create a new message.
 */
export declare const ImportInstrumentsResponseSchema: GenMessage<ImportInstrumentsResponse>;

/**
 * @generated from message v1.PerformancePoint
 */
export declare type PerformancePoint = Message<"v1.PerformancePoint"> & {
  /**
   * @generated from field: string date = 1;
   */
  date: string;

  /**
   * @generated from field: int64 change_bps = 2;
   */
  changeBps: bigint;
};

/**
 * Describes the message v1.PerformancePoint.
 * Use `create(PerformancePointSchema)` to create a new message.
 */
export declare const PerformancePointSchema: GenMessage<PerformancePoint>;

/**
 * @generated from message v1.GetInstrumentPerformanceRequest
 */
export declare type GetInstrumentPerformanceRequest = Message<"v1.GetInstrumentPerformanceRequest"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;
};

/**
 * Describes the message v1.GetInstrumentPerformanceRequest.
 * Use `create(GetInstrumentPerformanceRequestSchema)` to create a new message.
 */
export declare const GetInstrumentPerformanceRequestSchema: GenMessage<GetInstrumentPerformanceRequest>;

/**
 * @generated from message v1.GetInstrumentPerformanceResponse
 */
export declare type GetInstrumentPerformanceResponse = Message<"v1.GetInstrumentPerformanceResponse"> & {
  /**
   * @generated from field: repeated v1.PerformancePoint series = 1;
   */
  series: PerformancePoint[];

  /**
   * @generated from field: string fetched_at = 2;
   */
  fetchedAt: string;

  /**
   * @generated from field: int32 point_count = 3;
   */
  pointCount: number;
};

/**
 * Describes the message v1.GetInstrumentPerformanceResponse.
 * Use `create(GetInstrumentPerformanceResponseSchema)` to create a new message.
 */
export declare const GetInstrumentPerformanceResponseSchema: GenMessage<GetInstrumentPerformanceResponse>;

/**
 * @generated from message v1.RefreshInstrumentPerformanceRequest
 */
export declare type RefreshInstrumentPerformanceRequest = Message<"v1.RefreshInstrumentPerformanceRequest"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;
};

/**
 * Describes the message v1.RefreshInstrumentPerformanceRequest.
 * Use `create(RefreshInstrumentPerformanceRequestSchema)` to create a new message.
 */
export declare const RefreshInstrumentPerformanceRequestSchema: GenMessage<RefreshInstrumentPerformanceRequest>;

/**
 * @generated from message v1.RefreshInstrumentPerformanceResponse
 */
export declare type RefreshInstrumentPerformanceResponse = Message<"v1.RefreshInstrumentPerformanceResponse"> & {
  /**
   * @generated from field: repeated v1.PerformancePoint series = 1;
   */
  series: PerformancePoint[];

  /**
   * @generated from field: string fetched_at = 2;
   */
  fetchedAt: string;

  /**
   * @generated from field: int32 point_count = 3;
   */
  pointCount: number;
};

/**
 * Describes the message v1.RefreshInstrumentPerformanceResponse.
 * Use `create(RefreshInstrumentPerformanceResponseSchema)` to create a new message.
 */
export declare const RefreshInstrumentPerformanceResponseSchema: GenMessage<RefreshInstrumentPerformanceResponse>;

/**
 * @generated from message v1.DeleteInstrumentRequest
 */
export declare type DeleteInstrumentRequest = Message<"v1.DeleteInstrumentRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message v1.DeleteInstrumentRequest.
 * Use `create(DeleteInstrumentRequestSchema)` to create a new message.
 */
export declare const DeleteInstrumentRequestSchema: GenMessage<DeleteInstrumentRequest>;

/**
 * @generated from message v1.DeleteInstrumentResponse
 */
export declare type DeleteInstrumentResponse = Message<"v1.DeleteInstrumentResponse"> & {
};

/**
 * Describes the message v1.DeleteInstrumentResponse.
 * Use `create(DeleteInstrumentResponseSchema)` to create a new message.
 */
export declare const DeleteInstrumentResponseSchema: GenMessage<DeleteInstrumentResponse>;

/**
 * @generated from message v1.StarInstrumentRequest
 */
export declare type StarInstrumentRequest = Message<"v1.StarInstrumentRequest"> & {
  /**
   * @generated from field: string isin = 1;
   */
  isin: string;

  /**
   * @generated from field: bool starred = 2;
   */
  starred: boolean;
};

/**
 * Describes the message v1.StarInstrumentRequest.
 * Use `create(StarInstrumentRequestSchema)` to create a new message.
 */
export declare const StarInstrumentRequestSchema: GenMessage<StarInstrumentRequest>;

/**
 * @generated from message v1.StarInstrumentResponse
 */
export declare type StarInstrumentResponse = Message<"v1.StarInstrumentResponse"> & {
};

/**
 * Describes the message v1.StarInstrumentResponse.
 * Use `create(StarInstrumentResponseSchema)` to create a new message.
 */
export declare const StarInstrumentResponseSchema: GenMessage<StarInstrumentResponse>;

/**
 * @generated from message v1.GetInstrumentAlternativesRequest
 */
export declare type GetInstrumentAlternativesRequest = Message<"v1.GetInstrumentAlternativesRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message v1.GetInstrumentAlternativesRequest.
 * Use `create(GetInstrumentAlternativesRequestSchema)` to create a new message.
 */
export declare const GetInstrumentAlternativesRequestSchema: GenMessage<GetInstrumentAlternativesRequest>;

/**
 * @generated from message v1.GetInstrumentAlternativesResponse
 */
export declare type GetInstrumentAlternativesResponse = Message<"v1.GetInstrumentAlternativesResponse"> & {
  /**
   * @generated from field: repeated v1.InstrumentAlternative alternatives = 1;
   */
  alternatives: InstrumentAlternative[];
};

/**
 * Describes the message v1.GetInstrumentAlternativesResponse.
 * Use `create(GetInstrumentAlternativesResponseSchema)` to create a new message.
 */
export declare const GetInstrumentAlternativesResponseSchema: GenMessage<GetInstrumentAlternativesResponse>;

/**
 * @generated from message v1.RankInstrumentsRequest
 */
export declare type RankInstrumentsRequest = Message<"v1.RankInstrumentsRequest"> & {
  /**
   * @generated from field: v1.RankCriteria criteria = 1;
   */
  criteria?: RankCriteria | undefined;
};

/**
 * Describes the message v1.RankInstrumentsRequest.
 * Use `create(RankInstrumentsRequestSchema)` to create a new message.
 */
export declare const RankInstrumentsRequestSchema: GenMessage<RankInstrumentsRequest>;

/**
 * @generated from message v1.RankInstrumentsResponse
 */
export declare type RankInstrumentsResponse = Message<"v1.RankInstrumentsResponse"> & {
  /**
   * @generated from field: repeated v1.RankedInstrument ranked_instruments = 1;
   */
  rankedInstruments: RankedInstrument[];
};

/**
 * Describes the message v1.RankInstrumentsResponse.
 * Use `create(RankInstrumentsResponseSchema)` to create a new message.
 */
export declare const RankInstrumentsResponseSchema: GenMessage<RankInstrumentsResponse>;

/**
 * @generated from message v1.ReclassifyInstrumentsRequest
 */
export declare type ReclassifyInstrumentsRequest = Message<"v1.ReclassifyInstrumentsRequest"> & {
};

/**
 * Describes the message v1.ReclassifyInstrumentsRequest.
 * Use `create(ReclassifyInstrumentsRequestSchema)` to create a new message.
 */
export declare const ReclassifyInstrumentsRequestSchema: GenMessage<ReclassifyInstrumentsRequest>;

/**
 * @generated from message v1.ReclassifyInstrumentsResponse
 */
export declare type ReclassifyInstrumentsResponse = Message<"v1.ReclassifyInstrumentsResponse"> & {
  /**
   * @generated from field: int32 updated = 1;
   */
  updated: number;

  /**
   * @generated from field: int32 total = 2;
   */
  total: number;
};

/**
 * Describes the message v1.ReclassifyInstrumentsResponse.
 * Use `create(ReclassifyInstrumentsResponseSchema)` to create a new message.
 */
export declare const ReclassifyInstrumentsResponseSchema: GenMessage<ReclassifyInstrumentsResponse>;

/**
 * InstrumentService provides access to the 4,000+ ETF catalog, searching, enrichment, and ETF alternative ranking.
 *
 * @generated from service v1.InstrumentService
 */
export declare const InstrumentService: GenService<{
  /**
   * List saved instruments in the user catalog.
   *
   * @generated from rpc v1.InstrumentService.ListInstruments
   */
  listInstruments: {
    methodKind: "unary";
    input: typeof ListInstrumentsRequestSchema;
    output: typeof ListInstrumentsResponseSchema;
  },
  /**
   * Search the 4,000+ ETF catalog by ISIN, ticker, name, or index.
   *
   * @generated from rpc v1.InstrumentService.SearchInstruments
   */
  searchInstruments: {
    methodKind: "unary";
    input: typeof SearchInstrumentsRequestSchema;
    output: typeof SearchInstrumentsResponseSchema;
  },
  /**
   * Sync the latest instrument catalog list.
   *
   * @generated from rpc v1.InstrumentService.SyncInstrumentCatalog
   */
  syncInstrumentCatalog: {
    methodKind: "unary";
    input: typeof SyncInstrumentCatalogRequestSchema;
    output: typeof SyncInstrumentCatalogResponseSchema;
  },
  /**
   * Enrich catalog items with TER, AUM, tracking error, and replication profile data.
   *
   * @generated from rpc v1.InstrumentService.EnrichInstrumentCatalog
   */
  enrichInstrumentCatalog: {
    methodKind: "unary";
    input: typeof EnrichInstrumentCatalogRequestSchema;
    output: typeof EnrichInstrumentCatalogResponseSchema;
  },
  /**
   * Stream catalog enrichment progress events over gRPC server streaming.
   *
   * @generated from rpc v1.InstrumentService.StreamInstrumentCatalog
   */
  streamInstrumentCatalog: {
    methodKind: "server_streaming";
    input: typeof StreamInstrumentCatalogRequestSchema;
    output: typeof EnrichmentProgressSchema;
  },
  /**
   * Manually add a custom instrument.
   *
   * @generated from rpc v1.InstrumentService.CreateInstrument
   */
  createInstrument: {
    methodKind: "unary";
    input: typeof CreateInstrumentRequestSchema;
    output: typeof CreateInstrumentResponseSchema;
  },
  /**
   * Lookup security details by ISIN or query.
   *
   * @generated from rpc v1.InstrumentService.LookupInstrument
   */
  lookupInstrument: {
    methodKind: "unary";
    input: typeof LookupInstrumentRequestSchema;
    output: typeof LookupInstrumentResponseSchema;
  },
  /**
   * Batch import securities by ISIN list.
   *
   * @generated from rpc v1.InstrumentService.ImportInstruments
   */
  importInstruments: {
    methodKind: "unary";
    input: typeof ImportInstrumentsRequestSchema;
    output: typeof ImportInstrumentsResponseSchema;
  },
  /**
   * Delete an instrument from the catalog.
   *
   * @generated from rpc v1.InstrumentService.DeleteInstrument
   */
  deleteInstrument: {
    methodKind: "unary";
    input: typeof DeleteInstrumentRequestSchema;
    output: typeof DeleteInstrumentResponseSchema;
  },
  /**
   * Star or unstar an instrument for quick tracking.
   *
   * @generated from rpc v1.InstrumentService.StarInstrument
   */
  starInstrument: {
    methodKind: "unary";
    input: typeof StarInstrumentRequestSchema;
    output: typeof StarInstrumentResponseSchema;
  },
  /**
   * Find cheaper or better-performing alternative ETFs for a target instrument.
   *
   * @generated from rpc v1.InstrumentService.GetInstrumentAlternatives
   */
  getInstrumentAlternatives: {
    methodKind: "unary";
    input: typeof GetInstrumentAlternativesRequestSchema;
    output: typeof GetInstrumentAlternativesResponseSchema;
  },
  /**
   * Rank ETF candidates according to TER cost, tracking metrics, AUM size, and fund age.
   *
   * @generated from rpc v1.InstrumentService.RankInstruments
   */
  rankInstruments: {
    methodKind: "unary";
    input: typeof RankInstrumentsRequestSchema;
    output: typeof RankInstrumentsResponseSchema;
  },
  /**
   * Enable or disable the background continuous ETF refresh loop.
   *
   * @generated from rpc v1.InstrumentService.SetContinuousRefresh
   */
  setContinuousRefresh: {
    methodKind: "unary";
    input: typeof SetContinuousRefreshRequestSchema;
    output: typeof SetContinuousRefreshResponseSchema;
  },
  /**
   * Stream real-time ticks from the continuous background ETF refresh loop.
   *
   * @generated from rpc v1.InstrumentService.WatchContinuousRefresh
   */
  watchContinuousRefresh: {
    methodKind: "server_streaming";
    input: typeof WatchContinuousRefreshRequestSchema;
    output: typeof RefreshTickSchema;
  },
  /**
   * Get historical daily performance series for an instrument (fetches from justETF on first call).
   *
   * @generated from rpc v1.InstrumentService.GetInstrumentPerformance
   */
  getInstrumentPerformance: {
    methodKind: "unary";
    input: typeof GetInstrumentPerformanceRequestSchema;
    output: typeof GetInstrumentPerformanceResponseSchema;
  },
  /**
   * Re-fetch and replace performance data from justETF for an instrument.
   *
   * @generated from rpc v1.InstrumentService.RefreshInstrumentPerformance
   */
  refreshInstrumentPerformance: {
    methodKind: "unary";
    input: typeof RefreshInstrumentPerformanceRequestSchema;
    output: typeof RefreshInstrumentPerformanceResponseSchema;
  },
  /**
   * Re-classify all instruments locally in the database (updates strategy, asset class, provider).
   *
   * @generated from rpc v1.InstrumentService.ReclassifyInstruments
   */
  reclassifyInstruments: {
    methodKind: "unary";
    input: typeof ReclassifyInstrumentsRequestSchema;
    output: typeof ReclassifyInstrumentsResponseSchema;
  },
}>;

