// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/profile.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetProfileRequest, GetProfileResponse, UpdateProfileRequest, UpdateProfileResponse } from "./profile_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ProfileService manages per-user application preferences.
 *
 * @generated from service v1.ProfileService
 */
export const ProfileService = {
  typeName: "v1.ProfileService",
  methods: {
    /**
     * Get the authenticated user's profile and preferences.
     *
     * @generated from rpc v1.ProfileService.GetProfile
     */
    getProfile: {
      name: "GetProfile",
      I: GetProfileRequest,
      O: GetProfileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Update the authenticated user's profile preferences.
     *
     * @generated from rpc v1.ProfileService.UpdateProfile
     */
    updateProfile: {
      name: "UpdateProfile",
      I: UpdateProfileRequest,
      O: UpdateProfileResponse,
      kind: MethodKind.Unary,
    },
  }
};

