// @generated by protoc-gen-es v2.16.0
// @generated from file v1/profile.proto (package v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file v1/profile.proto.
 */
export const file_v1_profile = /*@__PURE__*/
  fileDesc("ChB2MS9wcm9maWxlLnByb3RvEgJ2MSKqBgoLVXNlclByb2ZpbGUSEgoFdGhlbWUYASABKAlIAIgBARIfChJwcmVmZXJyZWRfY3VycmVuY3kYAiABKAlIAYgBARIjChZtb250aGx5X2V4cGVuc2VzX21pbm9yGAMgASgDSAKIAQESGwoOcmVzZXJ2ZV9tb250aHMYBCABKAVIA4gBARIaCg1oaWRlX2JhbGFuY2VzGAUgASgISASIAQESIQoUZW1lcmdlbmN5X2dvYWxfbWlub3IYBiABKANIBYgBARIgChNmaXJlX2V4cGVuc2VzX21pbm9yGAcgASgDSAaIAQESJAoXaW5zdHJ1bWVudF9jb2x1bW5zX2pzb24YCCABKAlIB4gBARIhChRzaG93X2ZpcmVfY2FsY3VsYXRvchgJIAEoCEgIiAEBEh0KEGVuYWJsZV9idHBfcmFua3MYCiABKAhICYgBARIXCgphY3RpdmVfdGFiGAsgASgJSAqIAQESHQoQYWlfc2V0dGluZ3NfanNvbhgMIAEoCUgLiAEBEiIKFWRyYWZ0X3BvcnRmb2xpb3NfanNvbhgNIAEoCUgMiAEBEh0KEHVzZXJfZGVzY3JpcHRpb24YDiABKAlIDYgBARIbChNzdGFycmVkX2luc3RydW1lbnRzGA8gAygJEhQKDHN0YXJyZWRfYnRwcxgQIAMoCUIICgZfdGhlbWVCFQoTX3ByZWZlcnJlZF9jdXJyZW5jeUIZChdfbW9udGhseV9leHBlbnNlc19taW5vckIRCg9fcmVzZXJ2ZV9tb250aHNCEAoOX2hpZGVfYmFsYW5jZXNCFwoVX2VtZXJnZW5jeV9nb2FsX21pbm9yQhYKFF9maXJlX2V4cGVuc2VzX21pbm9yQhoKGF9pbnN0cnVtZW50X2NvbHVtbnNfanNvbkIXChVfc2hvd19maXJlX2NhbGN1bGF0b3JCEwoRX2VuYWJsZV9idHBfcmFua3NCDQoLX2FjdGl2ZV90YWJCEwoRX2FpX3NldHRpbmdzX2pzb25CGAoWX2RyYWZ0X3BvcnRmb2xpb3NfanNvbkITChFfdXNlcl9kZXNjcmlwdGlvbiITChFHZXRQcm9maWxlUmVxdWVzdCI2ChJHZXRQcm9maWxlUmVzcG9uc2USIAoHcHJvZmlsZRgBIAEoCzIPLnYxLlVzZXJQcm9maWxlIjgKFFVwZGF0ZVByb2ZpbGVSZXF1ZXN0EiAKB3Byb2ZpbGUYASABKAsyDy52MS5Vc2VyUHJvZmlsZSI5ChVVcGRhdGVQcm9maWxlUmVzcG9uc2USIAoHcHJvZmlsZRgBIAEoCzIPLnYxLlVzZXJQcm9maWxlMpMBCg5Qcm9maWxlU2VydmljZRI7CgpHZXRQcm9maWxlEhUudjEuR2V0UHJvZmlsZVJlcXVlc3QaFi52MS5HZXRQcm9maWxlUmVzcG9uc2USRAoNVXBkYXRlUHJvZmlsZRIYLnYxLlVwZGF0ZVByb2ZpbGVSZXF1ZXN0GhkudjEuVXBkYXRlUHJvZmlsZVJlc3BvbnNlQjNaMWdpdGh1Yi5jb20vcm9hcmMwL3NxdWlycmVsL3Byb3RvL2dlbi9nby92MTtwb3J0djFiBnByb3RvMw");

/**
 * Describes the message v1.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export const UserProfileSchema = /*@__PURE__*/
  messageDesc(file_v1_profile, 0);

/**
 * Describes the message v1.GetProfileRequest.
 * Use `create(GetProfileRequestSchema)` to create a new message.
 */
export const GetProfileRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_profile, 1);

/**
 * Describes the message v1.GetProfileResponse.
 * Use `create(GetProfileResponseSchema)` to create a new message.
 */
export const GetProfileResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_profile, 2);

/**
 * Describes the message v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export const UpdateProfileRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_profile, 3);

/**
 * Describes the message v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export const UpdateProfileResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_profile, 4);

/**
 * ProfileService manages per-user application preferences.
 *
 * @generated from service v1.ProfileService
 */
export const ProfileService = /*@__PURE__*/
  serviceDesc(file_v1_profile, 0);

