// @generated by protoc-gen-es v2.16.0
// @generated from file v1/profile.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/profile.proto.
 */
export declare const file_v1_profile: GenFile;

/**
 * UserProfile stores per-user application preferences.
 *
 * @generated from message v1.UserProfile
 */
export declare type UserProfile = Message<"v1.UserProfile"> & {
  /**
   * UI color scheme: "light", "dark", or "" for system default.
   *
   * @generated from field: optional string theme = 1;
   */
  theme?: string | undefined;

  /**
   * Preferred display currency code e.g. "EUR", "USD".
   *
   * @generated from field: optional string preferred_currency = 2;
   */
  preferredCurrency?: string | undefined;

  /**
   * Monthly living expenses in minor units (cents) for emergency reserve calculation.
   *
   * @generated from field: optional int64 monthly_expenses_minor = 3;
   */
  monthlyExpensesMinor?: bigint | undefined;

  /**
   * Number of months of expenses to target as emergency reserve (default 6).
   *
   * @generated from field: optional int32 reserve_months = 4;
   */
  reserveMonths?: number | undefined;

  /**
   * Whether to hide monetary balances in the UI.
   *
   * @generated from field: optional bool hide_balances = 5;
   */
  hideBalances?: boolean | undefined;

  /**
   * Target emergency cash reserve in minor units (cents).
   *
   * @generated from field: optional int64 emergency_goal_minor = 6;
   */
  emergencyGoalMinor?: bigint | undefined;

  /**
   * Annual expenses for FIRE calculation in minor units (cents).
   *
   * @generated from field: optional int64 fire_expenses_minor = 7;
   */
  fireExpensesMinor?: bigint | undefined;

  /**
   * JSON string of visible instrument column IDs for the instrument finder.
   *
   * @generated from field: optional string instrument_columns_json = 8;
   */
  instrumentColumnsJson?: string | undefined;

  /**
   * Whether to show the FIRE / financial independence calculator on the Overview.
   *
   * @generated from field: optional bool show_fire_calculator = 9;
   */
  showFireCalculator?: boolean | undefined;

  /**
   * Whether to enable the BTP Rank plugin section.
   *
   * @generated from field: optional bool enable_btp_ranks = 10;
   */
  enableBtpRanks?: boolean | undefined;

  /**
   * Currently active navigation tab e.g. "overview", "investments", "btp".
   *
   * @generated from field: optional string active_tab = 11;
   */
  activeTab?: string | undefined;

  /**
   * JSON string of AI Assistant configuration settings.
   *
   * @generated from field: optional string ai_settings_json = 12;
   */
  aiSettingsJson?: string | undefined;

  /**
   * JSON string of custom draft portfolios.
   *
   * @generated from field: optional string draft_portfolios_json = 13;
   */
  draftPortfoliosJson?: string | undefined;

  /**
   * User description detailing investment objectives, risk exposure/tolerance, age, sex/gender, time horizon, etc.
   *
   * @generated from field: optional string user_description = 14;
   */
  userDescription?: string | undefined;
};

/**
 * Describes the message v1.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export declare const UserProfileSchema: GenMessage<UserProfile>;

/**
 * @generated from message v1.GetProfileRequest
 */
export declare type GetProfileRequest = Message<"v1.GetProfileRequest"> & {
};

/**
 * Describes the message v1.GetProfileRequest.
 * Use `create(GetProfileRequestSchema)` to create a new message.
 */
export declare const GetProfileRequestSchema: GenMessage<GetProfileRequest>;

/**
 * @generated from message v1.GetProfileResponse
 */
export declare type GetProfileResponse = Message<"v1.GetProfileResponse"> & {
  /**
   * @generated from field: v1.UserProfile profile = 1;
   */
  profile?: UserProfile | undefined;
};

/**
 * Describes the message v1.GetProfileResponse.
 * Use `create(GetProfileResponseSchema)` to create a new message.
 */
export declare const GetProfileResponseSchema: GenMessage<GetProfileResponse>;

/**
 * @generated from message v1.UpdateProfileRequest
 */
export declare type UpdateProfileRequest = Message<"v1.UpdateProfileRequest"> & {
  /**
   * @generated from field: v1.UserProfile profile = 1;
   */
  profile?: UserProfile | undefined;
};

/**
 * Describes the message v1.UpdateProfileRequest.
 * Use `create(UpdateProfileRequestSchema)` to create a new message.
 */
export declare const UpdateProfileRequestSchema: GenMessage<UpdateProfileRequest>;

/**
 * @generated from message v1.UpdateProfileResponse
 */
export declare type UpdateProfileResponse = Message<"v1.UpdateProfileResponse"> & {
  /**
   * @generated from field: v1.UserProfile profile = 1;
   */
  profile?: UserProfile | undefined;
};

/**
 * Describes the message v1.UpdateProfileResponse.
 * Use `create(UpdateProfileResponseSchema)` to create a new message.
 */
export declare const UpdateProfileResponseSchema: GenMessage<UpdateProfileResponse>;

/**
 * ProfileService manages per-user application preferences.
 *
 * @generated from service v1.ProfileService
 */
export declare const ProfileService: GenService<{
  /**
   * Get the authenticated user's profile and preferences.
   *
   * @generated from rpc v1.ProfileService.GetProfile
   */
  getProfile: {
    methodKind: "unary";
    input: typeof GetProfileRequestSchema;
    output: typeof GetProfileResponseSchema;
  },
  /**
   * Update the authenticated user's profile preferences.
   *
   * @generated from rpc v1.ProfileService.UpdateProfile
   */
  updateProfile: {
    methodKind: "unary";
    input: typeof UpdateProfileRequestSchema;
    output: typeof UpdateProfileResponseSchema;
  },
}>;

