// @generated by protoc-gen-es v1.10.0
// @generated from file v1/profile.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * UserProfile stores per-user application preferences.
 *
 * @generated from message v1.UserProfile
 */
export declare class UserProfile extends Message<UserProfile> {
  /**
   * UI color scheme: "light", "dark", or "" for system default.
   *
   * @generated from field: string theme = 1;
   */
  theme: string;

  /**
   * Preferred display currency code e.g. "EUR", "USD".
   *
   * @generated from field: string preferred_currency = 2;
   */
  preferredCurrency: string;

  /**
   * Monthly living expenses in minor units (cents) for emergency reserve calculation.
   *
   * @generated from field: int64 monthly_expenses_minor = 3;
   */
  monthlyExpensesMinor: bigint;

  /**
   * Number of months of expenses to target as emergency reserve (default 6).
   *
   * @generated from field: int32 reserve_months = 4;
   */
  reserveMonths: number;

  /**
   * Whether to hide monetary balances in the UI.
   *
   * @generated from field: bool hide_balances = 5;
   */
  hideBalances: boolean;

  /**
   * Target emergency cash reserve in minor units (cents).
   *
   * @generated from field: int64 emergency_goal_minor = 6;
   */
  emergencyGoalMinor: bigint;

  /**
   * Annual expenses for FIRE calculation in minor units (cents).
   *
   * @generated from field: int64 fire_expenses_minor = 7;
   */
  fireExpensesMinor: bigint;

  /**
   * JSON string of visible instrument column IDs for the instrument finder.
   *
   * @generated from field: string instrument_columns_json = 8;
   */
  instrumentColumnsJson: string;

  /**
   * Whether to show the FIRE / financial independence calculator on the Overview.
   *
   * @generated from field: bool show_fire_calculator = 9;
   */
  showFireCalculator: boolean;

  /**
   * Whether to enable the BTP Rank plugin section.
   *
   * @generated from field: bool enable_btp_ranks = 10;
   */
  enableBtpRanks: boolean;

  constructor(data?: PartialMessage<UserProfile>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UserProfile";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UserProfile;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UserProfile;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UserProfile;

  static equals(a: UserProfile | PlainMessage<UserProfile> | undefined, b: UserProfile | PlainMessage<UserProfile> | undefined): boolean;
}

/**
 * @generated from message v1.GetProfileRequest
 */
export declare class GetProfileRequest extends Message<GetProfileRequest> {
  constructor(data?: PartialMessage<GetProfileRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetProfileRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProfileRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProfileRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProfileRequest;

  static equals(a: GetProfileRequest | PlainMessage<GetProfileRequest> | undefined, b: GetProfileRequest | PlainMessage<GetProfileRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GetProfileResponse
 */
export declare class GetProfileResponse extends Message<GetProfileResponse> {
  /**
   * @generated from field: v1.UserProfile profile = 1;
   */
  profile?: UserProfile;

  constructor(data?: PartialMessage<GetProfileResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetProfileResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetProfileResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetProfileResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetProfileResponse;

  static equals(a: GetProfileResponse | PlainMessage<GetProfileResponse> | undefined, b: GetProfileResponse | PlainMessage<GetProfileResponse> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateProfileRequest
 */
export declare class UpdateProfileRequest extends Message<UpdateProfileRequest> {
  /**
   * @generated from field: v1.UserProfile profile = 1;
   */
  profile?: UserProfile;

  constructor(data?: PartialMessage<UpdateProfileRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateProfileRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateProfileRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateProfileRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateProfileRequest;

  static equals(a: UpdateProfileRequest | PlainMessage<UpdateProfileRequest> | undefined, b: UpdateProfileRequest | PlainMessage<UpdateProfileRequest> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateProfileResponse
 */
export declare class UpdateProfileResponse extends Message<UpdateProfileResponse> {
  /**
   * @generated from field: v1.UserProfile profile = 1;
   */
  profile?: UserProfile;

  constructor(data?: PartialMessage<UpdateProfileResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateProfileResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateProfileResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateProfileResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateProfileResponse;

  static equals(a: UpdateProfileResponse | PlainMessage<UpdateProfileResponse> | undefined, b: UpdateProfileResponse | PlainMessage<UpdateProfileResponse> | undefined): boolean;
}

