// @generated by protoc-gen-es v1.10.0
// @generated from file v1/rate.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * ReferenceRate defines central bank benchmark rates (e.g., €STR, ECB Deposit Facility Rate).
 *
 * @generated from message v1.ReferenceRate
 */
export declare class ReferenceRate extends Message<ReferenceRate> {
  /**
   * Rate code identifier e.g. "ESTR", "DFR".
   *
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * Human-readable label e.g. "Euro Short-Term Rate (€STR)".
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * Interest rate in basis points (e.g. 366 bps = 3.66%).
   *
   * @generated from field: int64 rate_bps = 3;
   */
  rateBps: bigint;

  /**
   * Date rate was observed (YYYY-MM-DD).
   *
   * @generated from field: string observed_on = 4;
   */
  observedOn: string;

  /**
   * Timestamp of last rate update.
   *
   * @generated from field: optional string updated_at = 5;
   */
  updatedAt?: string;

  constructor(data?: PartialMessage<ReferenceRate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ReferenceRate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReferenceRate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReferenceRate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReferenceRate;

  static equals(a: ReferenceRate | PlainMessage<ReferenceRate> | undefined, b: ReferenceRate | PlainMessage<ReferenceRate> | undefined): boolean;
}

/**
 * TaxRate defines jurisdiction tax rates on interest or capital gains.
 *
 * @generated from message v1.TaxRate
 */
export declare class TaxRate extends Message<TaxRate> {
  /**
   * Tax code e.g. "IT_STANDARD", "DE_ABG".
   *
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * Tax label e.g. "Italy Standard Interest Tax (26.00%)".
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * Tax rate in basis points (e.g. 2600 bps = 26.00%).
   *
   * @generated from field: int64 rate_bps = 3;
   */
  rateBps: bigint;

  constructor(data?: PartialMessage<TaxRate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.TaxRate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaxRate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaxRate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaxRate;

  static equals(a: TaxRate | PlainMessage<TaxRate> | undefined, b: TaxRate | PlainMessage<TaxRate> | undefined): boolean;
}

/**
 * @generated from message v1.ListReferenceRatesRequest
 */
export declare class ListReferenceRatesRequest extends Message<ListReferenceRatesRequest> {
  constructor(data?: PartialMessage<ListReferenceRatesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListReferenceRatesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListReferenceRatesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListReferenceRatesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListReferenceRatesRequest;

  static equals(a: ListReferenceRatesRequest | PlainMessage<ListReferenceRatesRequest> | undefined, b: ListReferenceRatesRequest | PlainMessage<ListReferenceRatesRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListReferenceRatesResponse
 */
export declare class ListReferenceRatesResponse extends Message<ListReferenceRatesResponse> {
  /**
   * @generated from field: repeated v1.ReferenceRate rates = 1;
   */
  rates: ReferenceRate[];

  constructor(data?: PartialMessage<ListReferenceRatesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListReferenceRatesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListReferenceRatesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListReferenceRatesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListReferenceRatesResponse;

  static equals(a: ListReferenceRatesResponse | PlainMessage<ListReferenceRatesResponse> | undefined, b: ListReferenceRatesResponse | PlainMessage<ListReferenceRatesResponse> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateReferenceRateRequest
 */
export declare class UpdateReferenceRateRequest extends Message<UpdateReferenceRateRequest> {
  /**
   * @generated from field: v1.ReferenceRate rate = 1;
   */
  rate?: ReferenceRate;

  constructor(data?: PartialMessage<UpdateReferenceRateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateReferenceRateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateReferenceRateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateReferenceRateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateReferenceRateRequest;

  static equals(a: UpdateReferenceRateRequest | PlainMessage<UpdateReferenceRateRequest> | undefined, b: UpdateReferenceRateRequest | PlainMessage<UpdateReferenceRateRequest> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateReferenceRateResponse
 */
export declare class UpdateReferenceRateResponse extends Message<UpdateReferenceRateResponse> {
  constructor(data?: PartialMessage<UpdateReferenceRateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateReferenceRateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateReferenceRateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateReferenceRateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateReferenceRateResponse;

  static equals(a: UpdateReferenceRateResponse | PlainMessage<UpdateReferenceRateResponse> | undefined, b: UpdateReferenceRateResponse | PlainMessage<UpdateReferenceRateResponse> | undefined): boolean;
}

/**
 * @generated from message v1.RefreshReferenceRatesRequest
 */
export declare class RefreshReferenceRatesRequest extends Message<RefreshReferenceRatesRequest> {
  constructor(data?: PartialMessage<RefreshReferenceRatesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RefreshReferenceRatesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshReferenceRatesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshReferenceRatesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshReferenceRatesRequest;

  static equals(a: RefreshReferenceRatesRequest | PlainMessage<RefreshReferenceRatesRequest> | undefined, b: RefreshReferenceRatesRequest | PlainMessage<RefreshReferenceRatesRequest> | undefined): boolean;
}

/**
 * @generated from message v1.RefreshReferenceRatesResponse
 */
export declare class RefreshReferenceRatesResponse extends Message<RefreshReferenceRatesResponse> {
  /**
   * @generated from field: repeated v1.ReferenceRate rates = 1;
   */
  rates: ReferenceRate[];

  constructor(data?: PartialMessage<RefreshReferenceRatesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RefreshReferenceRatesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RefreshReferenceRatesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RefreshReferenceRatesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RefreshReferenceRatesResponse;

  static equals(a: RefreshReferenceRatesResponse | PlainMessage<RefreshReferenceRatesResponse> | undefined, b: RefreshReferenceRatesResponse | PlainMessage<RefreshReferenceRatesResponse> | undefined): boolean;
}

/**
 * @generated from message v1.MarketMetric
 */
export declare class MarketMetric extends Message<MarketMetric> {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: string category = 3;
   */
  category: string;

  /**
   * @generated from field: double value = 4;
   */
  value: number;

  /**
   * @generated from field: string unit = 5;
   */
  unit: string;

  /**
   * @generated from field: string observed_on = 6;
   */
  observedOn: string;

  /**
   * @generated from field: string source_url = 7;
   */
  sourceUrl: string;

  /**
   * @generated from field: optional double change_1y = 8;
   */
  change1y?: number;

  /**
   * @generated from field: optional double distance_52w_high = 9;
   */
  distance52wHigh?: number;

  /**
   * @generated from field: optional double sma_200 = 10;
   */
  sma200?: number;

  constructor(data?: PartialMessage<MarketMetric>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.MarketMetric";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarketMetric;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarketMetric;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarketMetric;

  static equals(a: MarketMetric | PlainMessage<MarketMetric> | undefined, b: MarketMetric | PlainMessage<MarketMetric> | undefined): boolean;
}

/**
 * @generated from message v1.MarketObservation
 */
export declare class MarketObservation extends Message<MarketObservation> {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string observed_on = 2;
   */
  observedOn: string;

  /**
   * @generated from field: double value = 3;
   */
  value: number;

  constructor(data?: PartialMessage<MarketObservation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.MarketObservation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarketObservation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarketObservation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarketObservation;

  static equals(a: MarketObservation | PlainMessage<MarketObservation> | undefined, b: MarketObservation | PlainMessage<MarketObservation> | undefined): boolean;
}

/**
 * @generated from message v1.GetMarketContextRequest
 */
export declare class GetMarketContextRequest extends Message<GetMarketContextRequest> {
  /**
   * Inflation history to return: "1y", "3y", "5y", or "max". Defaults to "1y".
   *
   * @generated from field: string inflation_range = 1;
   */
  inflationRange: string;

  /**
   * @generated from field: optional bool force_refresh = 2;
   */
  forceRefresh?: boolean;

  constructor(data?: PartialMessage<GetMarketContextRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetMarketContextRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMarketContextRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMarketContextRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMarketContextRequest;

  static equals(a: GetMarketContextRequest | PlainMessage<GetMarketContextRequest> | undefined, b: GetMarketContextRequest | PlainMessage<GetMarketContextRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GetMarketContextResponse
 */
export declare class GetMarketContextResponse extends Message<GetMarketContextResponse> {
  /**
   * @generated from field: repeated v1.MarketMetric metrics = 1;
   */
  metrics: MarketMetric[];

  /**
   * @generated from field: repeated string warnings = 2;
   */
  warnings: string[];

  /**
   * @generated from field: repeated v1.MarketObservation observations = 3;
   */
  observations: MarketObservation[];

  constructor(data?: PartialMessage<GetMarketContextResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetMarketContextResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMarketContextResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMarketContextResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMarketContextResponse;

  static equals(a: GetMarketContextResponse | PlainMessage<GetMarketContextResponse> | undefined, b: GetMarketContextResponse | PlainMessage<GetMarketContextResponse> | undefined): boolean;
}

/**
 * @generated from message v1.ListTaxRatesRequest
 */
export declare class ListTaxRatesRequest extends Message<ListTaxRatesRequest> {
  constructor(data?: PartialMessage<ListTaxRatesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListTaxRatesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTaxRatesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTaxRatesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTaxRatesRequest;

  static equals(a: ListTaxRatesRequest | PlainMessage<ListTaxRatesRequest> | undefined, b: ListTaxRatesRequest | PlainMessage<ListTaxRatesRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListTaxRatesResponse
 */
export declare class ListTaxRatesResponse extends Message<ListTaxRatesResponse> {
  /**
   * @generated from field: repeated v1.TaxRate rates = 1;
   */
  rates: TaxRate[];

  constructor(data?: PartialMessage<ListTaxRatesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListTaxRatesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTaxRatesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTaxRatesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTaxRatesResponse;

  static equals(a: ListTaxRatesResponse | PlainMessage<ListTaxRatesResponse> | undefined, b: ListTaxRatesResponse | PlainMessage<ListTaxRatesResponse> | undefined): boolean;
}

