// @generated by protoc-gen-es v1.10.0
// @generated from file v1/rate.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.ReferenceRate
 */
export const ReferenceRate = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ReferenceRate",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "rate_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "observed_on", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "updated_at", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message v1.TaxRate
 */
export const TaxRate = /*@__PURE__*/ proto3.makeMessageType(
  "v1.TaxRate",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "rate_bps", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.ListReferenceRatesRequest
 */
export const ListReferenceRatesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListReferenceRatesRequest",
  [],
);

/**
 * @generated from message v1.ListReferenceRatesResponse
 */
export const ListReferenceRatesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListReferenceRatesResponse",
  () => [
    { no: 1, name: "rates", kind: "message", T: ReferenceRate, repeated: true },
  ],
);

/**
 * @generated from message v1.UpdateReferenceRateRequest
 */
export const UpdateReferenceRateRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.UpdateReferenceRateRequest",
  () => [
    { no: 1, name: "rate", kind: "message", T: ReferenceRate },
  ],
);

/**
 * @generated from message v1.UpdateReferenceRateResponse
 */
export const UpdateReferenceRateResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.UpdateReferenceRateResponse",
  [],
);

/**
 * @generated from message v1.ListTaxRatesRequest
 */
export const ListTaxRatesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListTaxRatesRequest",
  [],
);

/**
 * @generated from message v1.ListTaxRatesResponse
 */
export const ListTaxRatesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListTaxRatesResponse",
  () => [
    { no: 1, name: "rates", kind: "message", T: TaxRate, repeated: true },
  ],
);

