// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/rate.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListReferenceRatesRequest, ListReferenceRatesResponse, ListTaxRatesRequest, ListTaxRatesResponse, UpdateReferenceRateRequest, UpdateReferenceRateResponse } from "./rate_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.RateService
 */
export const RateService = {
  typeName: "v1.RateService",
  methods: {
    /**
     * @generated from rpc v1.RateService.ListReferenceRates
     */
    listReferenceRates: {
      name: "ListReferenceRates",
      I: ListReferenceRatesRequest,
      O: ListReferenceRatesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.RateService.UpdateReferenceRate
     */
    updateReferenceRate: {
      name: "UpdateReferenceRate",
      I: UpdateReferenceRateRequest,
      O: UpdateReferenceRateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.RateService.ListTaxRates
     */
    listTaxRates: {
      name: "ListTaxRates",
      I: ListTaxRatesRequest,
      O: ListTaxRatesResponse,
      kind: MethodKind.Unary,
    },
  }
};

