// @generated by protoc-gen-es v2.16.0
// @generated from file v1/rate.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/rate.proto.
 */
export declare const file_v1_rate: GenFile;

/**
 * ReferenceRate defines central bank benchmark rates (e.g., €STR, ECB Deposit Facility Rate).
 *
 * @generated from message v1.ReferenceRate
 */
export declare type ReferenceRate = Message<"v1.ReferenceRate"> & {
  /**
   * Rate code identifier e.g. "ESTR", "DFR".
   *
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * Human-readable label e.g. "Euro Short-Term Rate (€STR)".
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * Interest rate in basis points (e.g. 366 bps = 3.66%).
   *
   * @generated from field: int64 rate_bps = 3;
   */
  rateBps: bigint;

  /**
   * Date rate was observed (YYYY-MM-DD).
   *
   * @generated from field: string observed_on = 4;
   */
  observedOn: string;

  /**
   * Timestamp of last rate update.
   *
   * @generated from field: optional string updated_at = 5;
   */
  updatedAt?: string | undefined;
};

/**
 * Describes the message v1.ReferenceRate.
 * Use `create(ReferenceRateSchema)` to create a new message.
 */
export declare const ReferenceRateSchema: GenMessage<ReferenceRate>;

/**
 * TaxRate defines jurisdiction tax rates on interest or capital gains.
 *
 * @generated from message v1.TaxRate
 */
export declare type TaxRate = Message<"v1.TaxRate"> & {
  /**
   * Tax code e.g. "IT_STANDARD", "DE_ABG".
   *
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * Tax label e.g. "Italy Standard Interest Tax (26.00%)".
   *
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * Tax rate in basis points (e.g. 2600 bps = 26.00%).
   *
   * @generated from field: int64 rate_bps = 3;
   */
  rateBps: bigint;
};

/**
 * Describes the message v1.TaxRate.
 * Use `create(TaxRateSchema)` to create a new message.
 */
export declare const TaxRateSchema: GenMessage<TaxRate>;

/**
 * @generated from message v1.ListReferenceRatesRequest
 */
export declare type ListReferenceRatesRequest = Message<"v1.ListReferenceRatesRequest"> & {
};

/**
 * Describes the message v1.ListReferenceRatesRequest.
 * Use `create(ListReferenceRatesRequestSchema)` to create a new message.
 */
export declare const ListReferenceRatesRequestSchema: GenMessage<ListReferenceRatesRequest>;

/**
 * @generated from message v1.ListReferenceRatesResponse
 */
export declare type ListReferenceRatesResponse = Message<"v1.ListReferenceRatesResponse"> & {
  /**
   * @generated from field: repeated v1.ReferenceRate rates = 1;
   */
  rates: ReferenceRate[];
};

/**
 * Describes the message v1.ListReferenceRatesResponse.
 * Use `create(ListReferenceRatesResponseSchema)` to create a new message.
 */
export declare const ListReferenceRatesResponseSchema: GenMessage<ListReferenceRatesResponse>;

/**
 * @generated from message v1.UpdateReferenceRateRequest
 */
export declare type UpdateReferenceRateRequest = Message<"v1.UpdateReferenceRateRequest"> & {
  /**
   * @generated from field: v1.ReferenceRate rate = 1;
   */
  rate?: ReferenceRate | undefined;
};

/**
 * Describes the message v1.UpdateReferenceRateRequest.
 * Use `create(UpdateReferenceRateRequestSchema)` to create a new message.
 */
export declare const UpdateReferenceRateRequestSchema: GenMessage<UpdateReferenceRateRequest>;

/**
 * @generated from message v1.UpdateReferenceRateResponse
 */
export declare type UpdateReferenceRateResponse = Message<"v1.UpdateReferenceRateResponse"> & {
};

/**
 * Describes the message v1.UpdateReferenceRateResponse.
 * Use `create(UpdateReferenceRateResponseSchema)` to create a new message.
 */
export declare const UpdateReferenceRateResponseSchema: GenMessage<UpdateReferenceRateResponse>;

/**
 * @generated from message v1.RefreshReferenceRatesRequest
 */
export declare type RefreshReferenceRatesRequest = Message<"v1.RefreshReferenceRatesRequest"> & {
};

/**
 * Describes the message v1.RefreshReferenceRatesRequest.
 * Use `create(RefreshReferenceRatesRequestSchema)` to create a new message.
 */
export declare const RefreshReferenceRatesRequestSchema: GenMessage<RefreshReferenceRatesRequest>;

/**
 * @generated from message v1.RefreshReferenceRatesResponse
 */
export declare type RefreshReferenceRatesResponse = Message<"v1.RefreshReferenceRatesResponse"> & {
  /**
   * @generated from field: repeated v1.ReferenceRate rates = 1;
   */
  rates: ReferenceRate[];
};

/**
 * Describes the message v1.RefreshReferenceRatesResponse.
 * Use `create(RefreshReferenceRatesResponseSchema)` to create a new message.
 */
export declare const RefreshReferenceRatesResponseSchema: GenMessage<RefreshReferenceRatesResponse>;

/**
 * @generated from message v1.MarketMetric
 */
export declare type MarketMetric = Message<"v1.MarketMetric"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: string category = 3;
   */
  category: string;

  /**
   * @generated from field: double value = 4;
   */
  value: number;

  /**
   * @generated from field: string unit = 5;
   */
  unit: string;

  /**
   * @generated from field: string observed_on = 6;
   */
  observedOn: string;

  /**
   * @generated from field: string source_url = 7;
   */
  sourceUrl: string;

  /**
   * @generated from field: optional double change_1y = 8;
   */
  change1y?: number | undefined;

  /**
   * @generated from field: optional double distance_52w_high = 9;
   */
  distance52wHigh?: number | undefined;

  /**
   * @generated from field: optional double sma_200 = 10;
   */
  sma200?: number | undefined;
};

/**
 * Describes the message v1.MarketMetric.
 * Use `create(MarketMetricSchema)` to create a new message.
 */
export declare const MarketMetricSchema: GenMessage<MarketMetric>;

/**
 * @generated from message v1.MarketObservation
 */
export declare type MarketObservation = Message<"v1.MarketObservation"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string observed_on = 2;
   */
  observedOn: string;

  /**
   * @generated from field: double value = 3;
   */
  value: number;
};

/**
 * Describes the message v1.MarketObservation.
 * Use `create(MarketObservationSchema)` to create a new message.
 */
export declare const MarketObservationSchema: GenMessage<MarketObservation>;

/**
 * @generated from message v1.GetMarketContextRequest
 */
export declare type GetMarketContextRequest = Message<"v1.GetMarketContextRequest"> & {
  /**
   * Inflation history to return: "1y", "3y", "5y", or "max". Defaults to "1y".
   *
   * @generated from field: string inflation_range = 1;
   */
  inflationRange: string;

  /**
   * @generated from field: optional bool force_refresh = 2;
   */
  forceRefresh?: boolean | undefined;
};

/**
 * Describes the message v1.GetMarketContextRequest.
 * Use `create(GetMarketContextRequestSchema)` to create a new message.
 */
export declare const GetMarketContextRequestSchema: GenMessage<GetMarketContextRequest>;

/**
 * @generated from message v1.GetMarketContextResponse
 */
export declare type GetMarketContextResponse = Message<"v1.GetMarketContextResponse"> & {
  /**
   * @generated from field: repeated v1.MarketMetric metrics = 1;
   */
  metrics: MarketMetric[];

  /**
   * @generated from field: repeated string warnings = 2;
   */
  warnings: string[];

  /**
   * @generated from field: repeated v1.MarketObservation observations = 3;
   */
  observations: MarketObservation[];
};

/**
 * Describes the message v1.GetMarketContextResponse.
 * Use `create(GetMarketContextResponseSchema)` to create a new message.
 */
export declare const GetMarketContextResponseSchema: GenMessage<GetMarketContextResponse>;

/**
 * @generated from message v1.ListTaxRatesRequest
 */
export declare type ListTaxRatesRequest = Message<"v1.ListTaxRatesRequest"> & {
};

/**
 * Describes the message v1.ListTaxRatesRequest.
 * Use `create(ListTaxRatesRequestSchema)` to create a new message.
 */
export declare const ListTaxRatesRequestSchema: GenMessage<ListTaxRatesRequest>;

/**
 * @generated from message v1.ListTaxRatesResponse
 */
export declare type ListTaxRatesResponse = Message<"v1.ListTaxRatesResponse"> & {
  /**
   * @generated from field: repeated v1.TaxRate rates = 1;
   */
  rates: TaxRate[];
};

/**
 * Describes the message v1.ListTaxRatesResponse.
 * Use `create(ListTaxRatesResponseSchema)` to create a new message.
 */
export declare const ListTaxRatesResponseSchema: GenMessage<ListTaxRatesResponse>;

/**
 * RateService manages central bank benchmark interest rates and tax presets.
 *
 * @generated from service v1.RateService
 */
export declare const RateService: GenService<{
  /**
   * List configured central bank reference rates.
   *
   * @generated from rpc v1.RateService.ListReferenceRates
   */
  listReferenceRates: {
    methodKind: "unary";
    input: typeof ListReferenceRatesRequestSchema;
    output: typeof ListReferenceRatesResponseSchema;
  },
  /**
   * Update a central bank reference rate value.
   *
   * @generated from rpc v1.RateService.UpdateReferenceRate
   */
  updateReferenceRate: {
    methodKind: "unary";
    input: typeof UpdateReferenceRateRequestSchema;
    output: typeof UpdateReferenceRateResponseSchema;
  },
  /**
   * Fetch the latest official key interest rates from the ECB.
   *
   * @generated from rpc v1.RateService.RefreshReferenceRates
   */
  refreshReferenceRates: {
    methodKind: "unary";
    input: typeof RefreshReferenceRatesRequestSchema;
    output: typeof RefreshReferenceRatesResponseSchema;
  },
  /**
   * Fetch current public market and economic benchmarks from the ECB.
   *
   * @generated from rpc v1.RateService.GetMarketContext
   */
  getMarketContext: {
    methodKind: "unary";
    input: typeof GetMarketContextRequestSchema;
    output: typeof GetMarketContextResponseSchema;
  },
  /**
   * List default jurisdiction tax rates.
   *
   * @generated from rpc v1.RateService.ListTaxRates
   */
  listTaxRates: {
    methodKind: "unary";
    input: typeof ListTaxRatesRequestSchema;
    output: typeof ListTaxRatesResponseSchema;
  },
}>;

