// @generated by protoc-gen-es v1.10.0
// @generated from file v1/rate.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.ReferenceRate
 */
export declare class ReferenceRate extends Message<ReferenceRate> {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: int64 rate_bps = 3;
   */
  rateBps: bigint;

  /**
   * @generated from field: string observed_on = 4;
   */
  observedOn: string;

  /**
   * @generated from field: optional string updated_at = 5;
   */
  updatedAt?: string;

  constructor(data?: PartialMessage<ReferenceRate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ReferenceRate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReferenceRate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReferenceRate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReferenceRate;

  static equals(a: ReferenceRate | PlainMessage<ReferenceRate> | undefined, b: ReferenceRate | PlainMessage<ReferenceRate> | undefined): boolean;
}

/**
 * @generated from message v1.TaxRate
 */
export declare class TaxRate extends Message<TaxRate> {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: int64 rate_bps = 3;
   */
  rateBps: bigint;

  constructor(data?: PartialMessage<TaxRate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.TaxRate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TaxRate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TaxRate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TaxRate;

  static equals(a: TaxRate | PlainMessage<TaxRate> | undefined, b: TaxRate | PlainMessage<TaxRate> | undefined): boolean;
}

/**
 * @generated from message v1.ListReferenceRatesRequest
 */
export declare class ListReferenceRatesRequest extends Message<ListReferenceRatesRequest> {
  constructor(data?: PartialMessage<ListReferenceRatesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListReferenceRatesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListReferenceRatesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListReferenceRatesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListReferenceRatesRequest;

  static equals(a: ListReferenceRatesRequest | PlainMessage<ListReferenceRatesRequest> | undefined, b: ListReferenceRatesRequest | PlainMessage<ListReferenceRatesRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListReferenceRatesResponse
 */
export declare class ListReferenceRatesResponse extends Message<ListReferenceRatesResponse> {
  /**
   * @generated from field: repeated v1.ReferenceRate rates = 1;
   */
  rates: ReferenceRate[];

  constructor(data?: PartialMessage<ListReferenceRatesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListReferenceRatesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListReferenceRatesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListReferenceRatesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListReferenceRatesResponse;

  static equals(a: ListReferenceRatesResponse | PlainMessage<ListReferenceRatesResponse> | undefined, b: ListReferenceRatesResponse | PlainMessage<ListReferenceRatesResponse> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateReferenceRateRequest
 */
export declare class UpdateReferenceRateRequest extends Message<UpdateReferenceRateRequest> {
  /**
   * @generated from field: v1.ReferenceRate rate = 1;
   */
  rate?: ReferenceRate;

  constructor(data?: PartialMessage<UpdateReferenceRateRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateReferenceRateRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateReferenceRateRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateReferenceRateRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateReferenceRateRequest;

  static equals(a: UpdateReferenceRateRequest | PlainMessage<UpdateReferenceRateRequest> | undefined, b: UpdateReferenceRateRequest | PlainMessage<UpdateReferenceRateRequest> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateReferenceRateResponse
 */
export declare class UpdateReferenceRateResponse extends Message<UpdateReferenceRateResponse> {
  constructor(data?: PartialMessage<UpdateReferenceRateResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateReferenceRateResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateReferenceRateResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateReferenceRateResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateReferenceRateResponse;

  static equals(a: UpdateReferenceRateResponse | PlainMessage<UpdateReferenceRateResponse> | undefined, b: UpdateReferenceRateResponse | PlainMessage<UpdateReferenceRateResponse> | undefined): boolean;
}

/**
 * @generated from message v1.ListTaxRatesRequest
 */
export declare class ListTaxRatesRequest extends Message<ListTaxRatesRequest> {
  constructor(data?: PartialMessage<ListTaxRatesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListTaxRatesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTaxRatesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTaxRatesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTaxRatesRequest;

  static equals(a: ListTaxRatesRequest | PlainMessage<ListTaxRatesRequest> | undefined, b: ListTaxRatesRequest | PlainMessage<ListTaxRatesRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListTaxRatesResponse
 */
export declare class ListTaxRatesResponse extends Message<ListTaxRatesResponse> {
  /**
   * @generated from field: repeated v1.TaxRate rates = 1;
   */
  rates: TaxRate[];

  constructor(data?: PartialMessage<ListTaxRatesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListTaxRatesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTaxRatesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTaxRatesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTaxRatesResponse;

  static equals(a: ListTaxRatesResponse | PlainMessage<ListTaxRatesResponse> | undefined, b: ListTaxRatesResponse | PlainMessage<ListTaxRatesResponse> | undefined): boolean;
}

