// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/rate.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListReferenceRatesRequest, ListReferenceRatesResponse, ListTaxRatesRequest, ListTaxRatesResponse, UpdateReferenceRateRequest, UpdateReferenceRateResponse } from "./rate_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * RateService manages central bank benchmark interest rates and tax presets.
 *
 * @generated from service v1.RateService
 */
export declare const RateService: {
  readonly typeName: "v1.RateService",
  readonly methods: {
    /**
     * List configured central bank reference rates.
     *
     * @generated from rpc v1.RateService.ListReferenceRates
     */
    readonly listReferenceRates: {
      readonly name: "ListReferenceRates",
      readonly I: typeof ListReferenceRatesRequest,
      readonly O: typeof ListReferenceRatesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Update a central bank reference rate value.
     *
     * @generated from rpc v1.RateService.UpdateReferenceRate
     */
    readonly updateReferenceRate: {
      readonly name: "UpdateReferenceRate",
      readonly I: typeof UpdateReferenceRateRequest,
      readonly O: typeof UpdateReferenceRateResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * List default jurisdiction tax rates.
     *
     * @generated from rpc v1.RateService.ListTaxRates
     */
    readonly listTaxRates: {
      readonly name: "ListTaxRates",
      readonly I: typeof ListTaxRatesRequest,
      readonly O: typeof ListTaxRatesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

