// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/snapshot.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSnapshotRequest, CreateSnapshotResponse, DeleteSnapshotRequest, DeleteSnapshotResponse, ListSnapshotsRequest, ListSnapshotsResponse, UpdateSituationRequest, UpdateSituationResponse, UpdateSnapshotRequest, UpdateSnapshotResponse } from "./snapshot_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.SnapshotService
 */
export declare const SnapshotService: {
  readonly typeName: "v1.SnapshotService",
  readonly methods: {
    /**
     * @generated from rpc v1.SnapshotService.ListSnapshots
     */
    readonly listSnapshots: {
      readonly name: "ListSnapshots",
      readonly I: typeof ListSnapshotsRequest,
      readonly O: typeof ListSnapshotsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.CreateSnapshot
     */
    readonly createSnapshot: {
      readonly name: "CreateSnapshot",
      readonly I: typeof CreateSnapshotRequest,
      readonly O: typeof CreateSnapshotResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.UpdateSnapshot
     */
    readonly updateSnapshot: {
      readonly name: "UpdateSnapshot",
      readonly I: typeof UpdateSnapshotRequest,
      readonly O: typeof UpdateSnapshotResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.DeleteSnapshot
     */
    readonly deleteSnapshot: {
      readonly name: "DeleteSnapshot",
      readonly I: typeof DeleteSnapshotRequest,
      readonly O: typeof DeleteSnapshotResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.UpdateSituation
     */
    readonly updateSituation: {
      readonly name: "UpdateSituation",
      readonly I: typeof UpdateSituationRequest,
      readonly O: typeof UpdateSituationResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

