// @generated by protoc-gen-es v1.10.0
// @generated from file v1/snapshot.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.Snapshot
 */
export const Snapshot = /*@__PURE__*/ proto3.makeMessageType(
  "v1.Snapshot",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "observed_on", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cash_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "invested_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "portfolio_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "total_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.ListSnapshotsRequest
 */
export const ListSnapshotsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListSnapshotsRequest",
  () => [
    { no: 1, name: "sort", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message v1.ListSnapshotsResponse
 */
export const ListSnapshotsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListSnapshotsResponse",
  () => [
    { no: 1, name: "snapshots", kind: "message", T: Snapshot, repeated: true },
  ],
);

/**
 * @generated from message v1.CreateSnapshotRequest
 */
export const CreateSnapshotRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CreateSnapshotRequest",
  () => [
    { no: 1, name: "observed_on", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.CreateSnapshotResponse
 */
export const CreateSnapshotResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CreateSnapshotResponse",
  [],
);

/**
 * @generated from message v1.UpdateSnapshotRequest
 */
export const UpdateSnapshotRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.UpdateSnapshotRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "observed_on", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "cash_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "invested_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "portfolio_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.UpdateSnapshotResponse
 */
export const UpdateSnapshotResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.UpdateSnapshotResponse",
  () => [
    { no: 1, name: "snapshot", kind: "message", T: Snapshot },
  ],
);

/**
 * @generated from message v1.DeleteSnapshotRequest
 */
export const DeleteSnapshotRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DeleteSnapshotRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.DeleteSnapshotResponse
 */
export const DeleteSnapshotResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DeleteSnapshotResponse",
  [],
);

