// @generated by protoc-gen-es v2.16.0
// @generated from file v1/snapshot.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/snapshot.proto.
 */
export declare const file_v1_snapshot: GenFile;

/**
 * Snapshot represents a historical point-in-time wealth snapshot.
 *
 * @generated from message v1.Snapshot
 */
export declare type Snapshot = Message<"v1.Snapshot"> & {
  /**
   * Snapshot record ID.
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * Observation date in YYYY-MM-DD format.
   *
   * @generated from field: string observed_on = 2;
   */
  observedOn: string;

  /**
   * Currency code e.g. "EUR".
   *
   * @generated from field: string currency = 3;
   */
  currency: string;

  /**
   * Cash balance total in minor units (cents).
   *
   * @generated from field: int64 cash_minor = 4;
   */
  cashMinor: bigint;

  /**
   * Total cost basis invested in minor units (cents).
   *
   * @generated from field: int64 invested_minor = 5;
   */
  investedMinor: bigint;

  /**
   * Total portfolio investments market value in minor units (cents).
   *
   * @generated from field: int64 portfolio_minor = 6;
   */
  portfolioMinor: bigint;

  /**
   * Total net worth (cash + portfolio market value) in minor units (cents).
   *
   * @generated from field: int64 total_minor = 7;
   */
  totalMinor: bigint;
};

/**
 * Describes the message v1.Snapshot.
 * Use `create(SnapshotSchema)` to create a new message.
 */
export declare const SnapshotSchema: GenMessage<Snapshot>;

/**
 * @generated from message v1.ListSnapshotsRequest
 */
export declare type ListSnapshotsRequest = Message<"v1.ListSnapshotsRequest"> & {
  /**
   * @generated from field: optional string sort = 1;
   */
  sort?: string | undefined;
};

/**
 * Describes the message v1.ListSnapshotsRequest.
 * Use `create(ListSnapshotsRequestSchema)` to create a new message.
 */
export declare const ListSnapshotsRequestSchema: GenMessage<ListSnapshotsRequest>;

/**
 * @generated from message v1.ListSnapshotsResponse
 */
export declare type ListSnapshotsResponse = Message<"v1.ListSnapshotsResponse"> & {
  /**
   * @generated from field: repeated v1.Snapshot snapshots = 1;
   */
  snapshots: Snapshot[];
};

/**
 * Describes the message v1.ListSnapshotsResponse.
 * Use `create(ListSnapshotsResponseSchema)` to create a new message.
 */
export declare const ListSnapshotsResponseSchema: GenMessage<ListSnapshotsResponse>;

/**
 * @generated from message v1.CreateSnapshotRequest
 */
export declare type CreateSnapshotRequest = Message<"v1.CreateSnapshotRequest"> & {
  /**
   * Observation date in YYYY-MM-DD format.
   *
   * @generated from field: string observed_on = 1;
   */
  observedOn: string;
};

/**
 * Describes the message v1.CreateSnapshotRequest.
 * Use `create(CreateSnapshotRequestSchema)` to create a new message.
 */
export declare const CreateSnapshotRequestSchema: GenMessage<CreateSnapshotRequest>;

/**
 * @generated from message v1.CreateSnapshotResponse
 */
export declare type CreateSnapshotResponse = Message<"v1.CreateSnapshotResponse"> & {
};

/**
 * Describes the message v1.CreateSnapshotResponse.
 * Use `create(CreateSnapshotResponseSchema)` to create a new message.
 */
export declare const CreateSnapshotResponseSchema: GenMessage<CreateSnapshotResponse>;

/**
 * @generated from message v1.UpdateSnapshotRequest
 */
export declare type UpdateSnapshotRequest = Message<"v1.UpdateSnapshotRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string observed_on = 2;
   */
  observedOn: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency: string;

  /**
   * @generated from field: int64 cash_minor = 4;
   */
  cashMinor: bigint;

  /**
   * @generated from field: int64 invested_minor = 5;
   */
  investedMinor: bigint;

  /**
   * @generated from field: int64 portfolio_minor = 6;
   */
  portfolioMinor: bigint;
};

/**
 * Describes the message v1.UpdateSnapshotRequest.
 * Use `create(UpdateSnapshotRequestSchema)` to create a new message.
 */
export declare const UpdateSnapshotRequestSchema: GenMessage<UpdateSnapshotRequest>;

/**
 * @generated from message v1.UpdateSnapshotResponse
 */
export declare type UpdateSnapshotResponse = Message<"v1.UpdateSnapshotResponse"> & {
  /**
   * @generated from field: v1.Snapshot snapshot = 1;
   */
  snapshot?: Snapshot | undefined;
};

/**
 * Describes the message v1.UpdateSnapshotResponse.
 * Use `create(UpdateSnapshotResponseSchema)` to create a new message.
 */
export declare const UpdateSnapshotResponseSchema: GenMessage<UpdateSnapshotResponse>;

/**
 * @generated from message v1.DeleteSnapshotRequest
 */
export declare type DeleteSnapshotRequest = Message<"v1.DeleteSnapshotRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message v1.DeleteSnapshotRequest.
 * Use `create(DeleteSnapshotRequestSchema)` to create a new message.
 */
export declare const DeleteSnapshotRequestSchema: GenMessage<DeleteSnapshotRequest>;

/**
 * @generated from message v1.DeleteSnapshotResponse
 */
export declare type DeleteSnapshotResponse = Message<"v1.DeleteSnapshotResponse"> & {
};

/**
 * Describes the message v1.DeleteSnapshotResponse.
 * Use `create(DeleteSnapshotResponseSchema)` to create a new message.
 */
export declare const DeleteSnapshotResponseSchema: GenMessage<DeleteSnapshotResponse>;

/**
 * @generated from message v1.AccountCashUpdate
 */
export declare type AccountCashUpdate = Message<"v1.AccountCashUpdate"> & {
  /**
   * @generated from field: int64 account_id = 1;
   */
  accountId: bigint;

  /**
   * @generated from field: int64 balance_minor = 2;
   */
  balanceMinor: bigint;
};

/**
 * Describes the message v1.AccountCashUpdate.
 * Use `create(AccountCashUpdateSchema)` to create a new message.
 */
export declare const AccountCashUpdateSchema: GenMessage<AccountCashUpdate>;

/**
 * @generated from message v1.HoldingValueUpdate
 */
export declare type HoldingValueUpdate = Message<"v1.HoldingValueUpdate"> & {
  /**
   * @generated from field: int64 holding_id = 1;
   */
  holdingId: bigint;

  /**
   * @generated from field: int64 value_minor = 2;
   */
  valueMinor: bigint;

  /**
   * @generated from field: optional int64 invested_minor = 3;
   */
  investedMinor?: bigint | undefined;
};

/**
 * Describes the message v1.HoldingValueUpdate.
 * Use `create(HoldingValueUpdateSchema)` to create a new message.
 */
export declare const HoldingValueUpdateSchema: GenMessage<HoldingValueUpdate>;

/**
 * @generated from message v1.UpdateSituationRequest
 */
export declare type UpdateSituationRequest = Message<"v1.UpdateSituationRequest"> & {
  /**
   * @generated from field: repeated v1.AccountCashUpdate account_updates = 1;
   */
  accountUpdates: AccountCashUpdate[];

  /**
   * @generated from field: repeated v1.HoldingValueUpdate holding_updates = 2;
   */
  holdingUpdates: HoldingValueUpdate[];

  /**
   * @generated from field: bool save_snapshot = 3;
   */
  saveSnapshot: boolean;

  /**
   * @generated from field: optional string observed_on = 4;
   */
  observedOn?: string | undefined;
};

/**
 * Describes the message v1.UpdateSituationRequest.
 * Use `create(UpdateSituationRequestSchema)` to create a new message.
 */
export declare const UpdateSituationRequestSchema: GenMessage<UpdateSituationRequest>;

/**
 * @generated from message v1.UpdateSituationResponse
 */
export declare type UpdateSituationResponse = Message<"v1.UpdateSituationResponse"> & {
  /**
   * @generated from field: bool snapshot_saved = 1;
   */
  snapshotSaved: boolean;
};

/**
 * Describes the message v1.UpdateSituationResponse.
 * Use `create(UpdateSituationResponseSchema)` to create a new message.
 */
export declare const UpdateSituationResponseSchema: GenMessage<UpdateSituationResponse>;

/**
 * SnapshotService manages historical net worth snapshots and portfolio situation updates.
 *
 * @generated from service v1.SnapshotService
 */
export declare const SnapshotService: GenService<{
  /**
   * List historical net worth snapshots for trend analysis.
   *
   * @generated from rpc v1.SnapshotService.ListSnapshots
   */
  listSnapshots: {
    methodKind: "unary";
    input: typeof ListSnapshotsRequestSchema;
    output: typeof ListSnapshotsResponseSchema;
  },
  /**
   * Create a snapshot record from current account and holding totals.
   *
   * @generated from rpc v1.SnapshotService.CreateSnapshot
   */
  createSnapshot: {
    methodKind: "unary";
    input: typeof CreateSnapshotRequestSchema;
    output: typeof CreateSnapshotResponseSchema;
  },
  /**
   * Update a historical snapshot record.
   *
   * @generated from rpc v1.SnapshotService.UpdateSnapshot
   */
  updateSnapshot: {
    methodKind: "unary";
    input: typeof UpdateSnapshotRequestSchema;
    output: typeof UpdateSnapshotResponseSchema;
  },
  /**
   * Delete a historical snapshot record.
   *
   * @generated from rpc v1.SnapshotService.DeleteSnapshot
   */
  deleteSnapshot: {
    methodKind: "unary";
    input: typeof DeleteSnapshotRequestSchema;
    output: typeof DeleteSnapshotResponseSchema;
  },
  /**
   * Bulk update current account cash balances and holding market values with optional snapshot recording.
   *
   * @generated from rpc v1.SnapshotService.UpdateSituation
   */
  updateSituation: {
    methodKind: "unary";
    input: typeof UpdateSituationRequestSchema;
    output: typeof UpdateSituationResponseSchema;
  },
}>;

