// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/snapshot.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSnapshotRequest, CreateSnapshotResponse, DeleteSnapshotRequest, DeleteSnapshotResponse, ListSnapshotsRequest, ListSnapshotsResponse, UpdateSituationRequest, UpdateSituationResponse, UpdateSnapshotRequest, UpdateSnapshotResponse } from "./snapshot_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.SnapshotService
 */
export const SnapshotService = {
  typeName: "v1.SnapshotService",
  methods: {
    /**
     * @generated from rpc v1.SnapshotService.ListSnapshots
     */
    listSnapshots: {
      name: "ListSnapshots",
      I: ListSnapshotsRequest,
      O: ListSnapshotsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.CreateSnapshot
     */
    createSnapshot: {
      name: "CreateSnapshot",
      I: CreateSnapshotRequest,
      O: CreateSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.UpdateSnapshot
     */
    updateSnapshot: {
      name: "UpdateSnapshot",
      I: UpdateSnapshotRequest,
      O: UpdateSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.DeleteSnapshot
     */
    deleteSnapshot: {
      name: "DeleteSnapshot",
      I: DeleteSnapshotRequest,
      O: DeleteSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SnapshotService.UpdateSituation
     */
    updateSituation: {
      name: "UpdateSituation",
      I: UpdateSituationRequest,
      O: UpdateSituationResponse,
      kind: MethodKind.Unary,
    },
  }
};

