// @generated by protoc-gen-es v1.10.0
// @generated from file v1/snapshot.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.Snapshot
 */
export declare class Snapshot extends Message<Snapshot> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string observed_on = 2;
   */
  observedOn: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency: string;

  /**
   * @generated from field: int64 cash_minor = 4;
   */
  cashMinor: bigint;

  /**
   * @generated from field: int64 invested_minor = 5;
   */
  investedMinor: bigint;

  /**
   * @generated from field: int64 portfolio_minor = 6;
   */
  portfolioMinor: bigint;

  /**
   * @generated from field: int64 total_minor = 7;
   */
  totalMinor: bigint;

  constructor(data?: PartialMessage<Snapshot>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Snapshot";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Snapshot;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Snapshot;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Snapshot;

  static equals(a: Snapshot | PlainMessage<Snapshot> | undefined, b: Snapshot | PlainMessage<Snapshot> | undefined): boolean;
}

/**
 * @generated from message v1.ListSnapshotsRequest
 */
export declare class ListSnapshotsRequest extends Message<ListSnapshotsRequest> {
  /**
   * @generated from field: optional string sort = 1;
   */
  sort?: string;

  constructor(data?: PartialMessage<ListSnapshotsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListSnapshotsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSnapshotsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSnapshotsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSnapshotsRequest;

  static equals(a: ListSnapshotsRequest | PlainMessage<ListSnapshotsRequest> | undefined, b: ListSnapshotsRequest | PlainMessage<ListSnapshotsRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ListSnapshotsResponse
 */
export declare class ListSnapshotsResponse extends Message<ListSnapshotsResponse> {
  /**
   * @generated from field: repeated v1.Snapshot snapshots = 1;
   */
  snapshots: Snapshot[];

  constructor(data?: PartialMessage<ListSnapshotsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListSnapshotsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListSnapshotsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListSnapshotsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListSnapshotsResponse;

  static equals(a: ListSnapshotsResponse | PlainMessage<ListSnapshotsResponse> | undefined, b: ListSnapshotsResponse | PlainMessage<ListSnapshotsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.CreateSnapshotRequest
 */
export declare class CreateSnapshotRequest extends Message<CreateSnapshotRequest> {
  /**
   * @generated from field: string observed_on = 1;
   */
  observedOn: string;

  constructor(data?: PartialMessage<CreateSnapshotRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CreateSnapshotRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSnapshotRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSnapshotRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSnapshotRequest;

  static equals(a: CreateSnapshotRequest | PlainMessage<CreateSnapshotRequest> | undefined, b: CreateSnapshotRequest | PlainMessage<CreateSnapshotRequest> | undefined): boolean;
}

/**
 * @generated from message v1.CreateSnapshotResponse
 */
export declare class CreateSnapshotResponse extends Message<CreateSnapshotResponse> {
  constructor(data?: PartialMessage<CreateSnapshotResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CreateSnapshotResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSnapshotResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSnapshotResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSnapshotResponse;

  static equals(a: CreateSnapshotResponse | PlainMessage<CreateSnapshotResponse> | undefined, b: CreateSnapshotResponse | PlainMessage<CreateSnapshotResponse> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateSnapshotRequest
 */
export declare class UpdateSnapshotRequest extends Message<UpdateSnapshotRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string observed_on = 2;
   */
  observedOn: string;

  /**
   * @generated from field: string currency = 3;
   */
  currency: string;

  /**
   * @generated from field: int64 cash_minor = 4;
   */
  cashMinor: bigint;

  /**
   * @generated from field: int64 invested_minor = 5;
   */
  investedMinor: bigint;

  /**
   * @generated from field: int64 portfolio_minor = 6;
   */
  portfolioMinor: bigint;

  constructor(data?: PartialMessage<UpdateSnapshotRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateSnapshotRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSnapshotRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSnapshotRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSnapshotRequest;

  static equals(a: UpdateSnapshotRequest | PlainMessage<UpdateSnapshotRequest> | undefined, b: UpdateSnapshotRequest | PlainMessage<UpdateSnapshotRequest> | undefined): boolean;
}

/**
 * @generated from message v1.UpdateSnapshotResponse
 */
export declare class UpdateSnapshotResponse extends Message<UpdateSnapshotResponse> {
  /**
   * @generated from field: v1.Snapshot snapshot = 1;
   */
  snapshot?: Snapshot;

  constructor(data?: PartialMessage<UpdateSnapshotResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.UpdateSnapshotResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateSnapshotResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateSnapshotResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateSnapshotResponse;

  static equals(a: UpdateSnapshotResponse | PlainMessage<UpdateSnapshotResponse> | undefined, b: UpdateSnapshotResponse | PlainMessage<UpdateSnapshotResponse> | undefined): boolean;
}

/**
 * @generated from message v1.DeleteSnapshotRequest
 */
export declare class DeleteSnapshotRequest extends Message<DeleteSnapshotRequest> {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  constructor(data?: PartialMessage<DeleteSnapshotRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DeleteSnapshotRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSnapshotRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSnapshotRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSnapshotRequest;

  static equals(a: DeleteSnapshotRequest | PlainMessage<DeleteSnapshotRequest> | undefined, b: DeleteSnapshotRequest | PlainMessage<DeleteSnapshotRequest> | undefined): boolean;
}

/**
 * @generated from message v1.DeleteSnapshotResponse
 */
export declare class DeleteSnapshotResponse extends Message<DeleteSnapshotResponse> {
  constructor(data?: PartialMessage<DeleteSnapshotResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DeleteSnapshotResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteSnapshotResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteSnapshotResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteSnapshotResponse;

  static equals(a: DeleteSnapshotResponse | PlainMessage<DeleteSnapshotResponse> | undefined, b: DeleteSnapshotResponse | PlainMessage<DeleteSnapshotResponse> | undefined): boolean;
}

