// @generated by protoc-gen-es v2.16.0
// @generated from file v1/snapshot.proto (package v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file v1/snapshot.proto.
 */
export const file_v1_snapshot = /*@__PURE__*/
  fileDesc("ChF2MS9zbmFwc2hvdC5wcm90bxICdjEilwEKCFNuYXBzaG90EgoKAmlkGAEgASgDEhMKC29ic2VydmVkX29uGAIgASgJEhAKCGN1cnJlbmN5GAMgASgJEhIKCmNhc2hfbWlub3IYBCABKAMSFgoOaW52ZXN0ZWRfbWlub3IYBSABKAMSFwoPcG9ydGZvbGlvX21pbm9yGAYgASgDEhMKC3RvdGFsX21pbm9yGAcgASgDIjIKFExpc3RTbmFwc2hvdHNSZXF1ZXN0EhEKBHNvcnQYASABKAlIAIgBAUIHCgVfc29ydCI4ChVMaXN0U25hcHNob3RzUmVzcG9uc2USHwoJc25hcHNob3RzGAEgAygLMgwudjEuU25hcHNob3QiLAoVQ3JlYXRlU25hcHNob3RSZXF1ZXN0EhMKC29ic2VydmVkX29uGAEgASgJIhgKFkNyZWF0ZVNuYXBzaG90UmVzcG9uc2UijwEKFVVwZGF0ZVNuYXBzaG90UmVxdWVzdBIKCgJpZBgBIAEoAxITCgtvYnNlcnZlZF9vbhgCIAEoCRIQCghjdXJyZW5jeRgDIAEoCRISCgpjYXNoX21pbm9yGAQgASgDEhYKDmludmVzdGVkX21pbm9yGAUgASgDEhcKD3BvcnRmb2xpb19taW5vchgGIAEoAyI4ChZVcGRhdGVTbmFwc2hvdFJlc3BvbnNlEh4KCHNuYXBzaG90GAEgASgLMgwudjEuU25hcHNob3QiIwoVRGVsZXRlU25hcHNob3RSZXF1ZXN0EgoKAmlkGAEgASgDIhgKFkRlbGV0ZVNuYXBzaG90UmVzcG9uc2UiPgoRQWNjb3VudENhc2hVcGRhdGUSEgoKYWNjb3VudF9pZBgBIAEoAxIVCg1iYWxhbmNlX21pbm9yGAIgASgDIm0KEkhvbGRpbmdWYWx1ZVVwZGF0ZRISCgpob2xkaW5nX2lkGAEgASgDEhMKC3ZhbHVlX21pbm9yGAIgASgDEhsKDmludmVzdGVkX21pbm9yGAMgASgDSACIAQFCEQoPX2ludmVzdGVkX21pbm9yIroBChZVcGRhdGVTaXR1YXRpb25SZXF1ZXN0Ei4KD2FjY291bnRfdXBkYXRlcxgBIAMoCzIVLnYxLkFjY291bnRDYXNoVXBkYXRlEi8KD2hvbGRpbmdfdXBkYXRlcxgCIAMoCzIWLnYxLkhvbGRpbmdWYWx1ZVVwZGF0ZRIVCg1zYXZlX3NuYXBzaG90GAMgASgIEhgKC29ic2VydmVkX29uGAQgASgJSACIAQFCDgoMX29ic2VydmVkX29uIjEKF1VwZGF0ZVNpdHVhdGlvblJlc3BvbnNlEhYKDnNuYXBzaG90X3NhdmVkGAEgASgIMv4CCg9TbmFwc2hvdFNlcnZpY2USRAoNTGlzdFNuYXBzaG90cxIYLnYxLkxpc3RTbmFwc2hvdHNSZXF1ZXN0GhkudjEuTGlzdFNuYXBzaG90c1Jlc3BvbnNlEkcKDkNyZWF0ZVNuYXBzaG90EhkudjEuQ3JlYXRlU25hcHNob3RSZXF1ZXN0GhoudjEuQ3JlYXRlU25hcHNob3RSZXNwb25zZRJHCg5VcGRhdGVTbmFwc2hvdBIZLnYxLlVwZGF0ZVNuYXBzaG90UmVxdWVzdBoaLnYxLlVwZGF0ZVNuYXBzaG90UmVzcG9uc2USRwoORGVsZXRlU25hcHNob3QSGS52MS5EZWxldGVTbmFwc2hvdFJlcXVlc3QaGi52MS5EZWxldGVTbmFwc2hvdFJlc3BvbnNlEkoKD1VwZGF0ZVNpdHVhdGlvbhIaLnYxLlVwZGF0ZVNpdHVhdGlvblJlcXVlc3QaGy52MS5VcGRhdGVTaXR1YXRpb25SZXNwb25zZUIzWjFnaXRodWIuY29tL3JvYXJjMC9zcXVpcnJlbC9wcm90by9nZW4vZ28vdjE7cG9ydHYxYgZwcm90bzM");

/**
 * Describes the message v1.Snapshot.
 * Use `create(SnapshotSchema)` to create a new message.
 */
export const SnapshotSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 0);

/**
 * Describes the message v1.ListSnapshotsRequest.
 * Use `create(ListSnapshotsRequestSchema)` to create a new message.
 */
export const ListSnapshotsRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 1);

/**
 * Describes the message v1.ListSnapshotsResponse.
 * Use `create(ListSnapshotsResponseSchema)` to create a new message.
 */
export const ListSnapshotsResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 2);

/**
 * Describes the message v1.CreateSnapshotRequest.
 * Use `create(CreateSnapshotRequestSchema)` to create a new message.
 */
export const CreateSnapshotRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 3);

/**
 * Describes the message v1.CreateSnapshotResponse.
 * Use `create(CreateSnapshotResponseSchema)` to create a new message.
 */
export const CreateSnapshotResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 4);

/**
 * Describes the message v1.UpdateSnapshotRequest.
 * Use `create(UpdateSnapshotRequestSchema)` to create a new message.
 */
export const UpdateSnapshotRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 5);

/**
 * Describes the message v1.UpdateSnapshotResponse.
 * Use `create(UpdateSnapshotResponseSchema)` to create a new message.
 */
export const UpdateSnapshotResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 6);

/**
 * Describes the message v1.DeleteSnapshotRequest.
 * Use `create(DeleteSnapshotRequestSchema)` to create a new message.
 */
export const DeleteSnapshotRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 7);

/**
 * Describes the message v1.DeleteSnapshotResponse.
 * Use `create(DeleteSnapshotResponseSchema)` to create a new message.
 */
export const DeleteSnapshotResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 8);

/**
 * Describes the message v1.AccountCashUpdate.
 * Use `create(AccountCashUpdateSchema)` to create a new message.
 */
export const AccountCashUpdateSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 9);

/**
 * Describes the message v1.HoldingValueUpdate.
 * Use `create(HoldingValueUpdateSchema)` to create a new message.
 */
export const HoldingValueUpdateSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 10);

/**
 * Describes the message v1.UpdateSituationRequest.
 * Use `create(UpdateSituationRequestSchema)` to create a new message.
 */
export const UpdateSituationRequestSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 11);

/**
 * Describes the message v1.UpdateSituationResponse.
 * Use `create(UpdateSituationResponseSchema)` to create a new message.
 */
export const UpdateSituationResponseSchema = /*@__PURE__*/
  messageDesc(file_v1_snapshot, 12);

/**
 * SnapshotService manages historical net worth snapshots and portfolio situation updates.
 *
 * @generated from service v1.SnapshotService
 */
export const SnapshotService = /*@__PURE__*/
  serviceDesc(file_v1_snapshot, 0);

