// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetGeoRadarRequest, GetGeoRadarResponse, GetSummaryRequest, GetSummaryResponse } from "./summary_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SummaryService provides aggregated wealth totals, currency summaries, portfolio health diagnostics, and geographic risk exposure.
 *
 * @generated from service v1.SummaryService
 */
export declare const SummaryService: {
  readonly typeName: "v1.SummaryService",
  readonly methods: {
    /**
     * Get aggregated portfolio wealth summary, net worth, interest yields, and active health diagnostics.
     *
     * @generated from rpc v1.SummaryService.GetSummary
     */
    readonly getSummary: {
      readonly name: "GetSummary",
      readonly I: typeof GetSummaryRequest,
      readonly O: typeof GetSummaryResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Get geographic country breakdown, underlying currency exposure, and FX sensitivity analysis.
     *
     * @generated from rpc v1.SummaryService.GetGeoRadar
     */
    readonly getGeoRadar: {
      readonly name: "GetGeoRadar",
      readonly I: typeof GetGeoRadarRequest,
      readonly O: typeof GetGeoRadarResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

