// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSummaryRequest, GetSummaryResponse } from "./summary_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.SummaryService
 */
export const SummaryService = {
  typeName: "v1.SummaryService",
  methods: {
    /**
     * @generated from rpc v1.SummaryService.GetSummary
     */
    getSummary: {
      name: "GetSummary",
      I: GetSummaryRequest,
      O: GetSummaryResponse,
      kind: MethodKind.Unary,
    },
  }
};

