// @generated by protoc-gen-es v1.10.0
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * InstrumentAllocation represents portfolio allocation breakdown per asset class.
 *
 * @generated from message v1.InstrumentAllocation
 */
export declare class InstrumentAllocation extends Message<InstrumentAllocation> {
  /**
   * Asset class name e.g. "equity", "bond", "commodity", "cash".
   *
   * @generated from field: string asset_class = 1;
   */
  assetClass: string;

  /**
   * Total market value in minor units (cents).
   *
   * @generated from field: int64 value_minor = 2;
   */
  valueMinor: bigint;

  constructor(data?: PartialMessage<InstrumentAllocation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.InstrumentAllocation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InstrumentAllocation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InstrumentAllocation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InstrumentAllocation;

  static equals(a: InstrumentAllocation | PlainMessage<InstrumentAllocation> | undefined, b: InstrumentAllocation | PlainMessage<InstrumentAllocation> | undefined): boolean;
}

/**
 * CurrencySummary provides aggregated total wealth, cash balances, yields, and allocation breakdown per currency.
 *
 * @generated from message v1.CurrencySummary
 */
export declare class CurrencySummary extends Message<CurrencySummary> {
  /**
   * Currency code e.g. "EUR", "USD".
   *
   * @generated from field: string currency = 1;
   */
  currency: string;

  /**
   * Total cash balance across accounts in minor units (cents).
   *
   * @generated from field: int64 balance_minor = 2;
   */
  balanceMinor: bigint;

  /**
   * Total gross interest revenue in minor units (cents).
   *
   * @generated from field: int64 gross_revenue_minor = 3;
   */
  grossRevenueMinor: bigint;

  /**
   * Total interest tax in minor units (cents).
   *
   * @generated from field: int64 tax_minor = 4;
   */
  taxMinor: bigint;

  /**
   * Total account annual fees in minor units (cents).
   *
   * @generated from field: int64 fees_minor = 5;
   */
  feesMinor: bigint;

  /**
   * Total net interest revenue in minor units (cents).
   *
   * @generated from field: int64 net_revenue_minor = 6;
   */
  netRevenueMinor: bigint;

  /**
   * Total invested cost basis in minor units (cents).
   *
   * @generated from field: int64 invested_minor = 7;
   */
  investedMinor: bigint;

  /**
   * Total portfolio investments market value in minor units (cents).
   *
   * @generated from field: int64 portfolio_minor = 8;
   */
  portfolioMinor: bigint;

  /**
   * Total net worth (cash balance + investments market value) in minor units (cents).
   *
   * @generated from field: int64 total_minor = 9;
   */
  totalMinor: bigint;

  /**
   * Asset class allocation breakdown.
   *
   * @generated from field: repeated v1.InstrumentAllocation allocations = 10;
   */
  allocations: InstrumentAllocation[];

  constructor(data?: PartialMessage<CurrencySummary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CurrencySummary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CurrencySummary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CurrencySummary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CurrencySummary;

  static equals(a: CurrencySummary | PlainMessage<CurrencySummary> | undefined, b: CurrencySummary | PlainMessage<CurrencySummary> | undefined): boolean;
}

/**
 * Diagnostic represents an active portfolio health warning, fee drag alert, or cash goal alert.
 *
 * @generated from message v1.Diagnostic
 */
export declare class Diagnostic extends Message<Diagnostic> {
  /**
   * Diagnostic alert ID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Category e.g. "allocation", "fee", "cash", "account".
   *
   * @generated from field: string category = 2;
   */
  category: string;

  /**
   * Severity level: "info", "warning", or "alert".
   *
   * @generated from field: string severity = 3;
   */
  severity: string;

  /**
   * Alert title e.g. "High TER Fee Drag Detected", "Cash Reserve Below Target Goal".
   *
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * Detailed diagnostic message and recommendation.
   *
   * @generated from field: string message = 5;
   */
  message: string;

  /**
   * @generated from field: int64 holding_id = 6;
   */
  holdingId: bigint;

  /**
   * @generated from field: int64 account_id = 7;
   */
  accountId: bigint;

  /**
   * @generated from field: string isin = 8;
   */
  isin: string;

  constructor(data?: PartialMessage<Diagnostic>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Diagnostic";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Diagnostic;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Diagnostic;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Diagnostic;

  static equals(a: Diagnostic | PlainMessage<Diagnostic> | undefined, b: Diagnostic | PlainMessage<Diagnostic> | undefined): boolean;
}

/**
 * Summary represents the comprehensive portfolio state and health diagnostics.
 *
 * @generated from message v1.Summary
 */
export declare class Summary extends Message<Summary> {
  /**
   * Primary base currency code.
   *
   * @generated from field: string base_currency = 1;
   */
  baseCurrency: string;

  /**
   * Aggregated totals per currency.
   *
   * @generated from field: repeated v1.CurrencySummary currencies = 2;
   */
  currencies: CurrencySummary[];

  /**
   * Active health warnings and allocation diagnostics.
   *
   * @generated from field: repeated v1.Diagnostic diagnostics = 3;
   */
  diagnostics: Diagnostic[];

  constructor(data?: PartialMessage<Summary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Summary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Summary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Summary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Summary;

  static equals(a: Summary | PlainMessage<Summary> | undefined, b: Summary | PlainMessage<Summary> | undefined): boolean;
}

/**
 * @generated from message v1.GetSummaryRequest
 */
export declare class GetSummaryRequest extends Message<GetSummaryRequest> {
  /**
   * Optional emergency cash reserve goal target in minor units (cents).
   *
   * @generated from field: optional int64 target_cash_minor = 1;
   */
  targetCashMinor?: bigint;

  constructor(data?: PartialMessage<GetSummaryRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetSummaryRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSummaryRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSummaryRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSummaryRequest;

  static equals(a: GetSummaryRequest | PlainMessage<GetSummaryRequest> | undefined, b: GetSummaryRequest | PlainMessage<GetSummaryRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GetSummaryResponse
 */
export declare class GetSummaryResponse extends Message<GetSummaryResponse> {
  /**
   * @generated from field: v1.Summary summary = 1;
   */
  summary?: Summary;

  constructor(data?: PartialMessage<GetSummaryResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetSummaryResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSummaryResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSummaryResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSummaryResponse;

  static equals(a: GetSummaryResponse | PlainMessage<GetSummaryResponse> | undefined, b: GetSummaryResponse | PlainMessage<GetSummaryResponse> | undefined): boolean;
}

/**
 * @generated from message v1.GetGeoRadarRequest
 */
export declare class GetGeoRadarRequest extends Message<GetGeoRadarRequest> {
  /**
   * @generated from field: optional bool include_cash = 1;
   */
  includeCash?: boolean;

  constructor(data?: PartialMessage<GetGeoRadarRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetGeoRadarRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGeoRadarRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGeoRadarRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGeoRadarRequest;

  static equals(a: GetGeoRadarRequest | PlainMessage<GetGeoRadarRequest> | undefined, b: GetGeoRadarRequest | PlainMessage<GetGeoRadarRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GeoExposure
 */
export declare class GeoExposure extends Message<GeoExposure> {
  /**
   * @generated from field: string region = 1;
   */
  region: string;

  /**
   * @generated from field: string country_code = 2;
   */
  countryCode: string;

  /**
   * @generated from field: string country_name = 3;
   */
  countryName: string;

  /**
   * @generated from field: int64 value_minor = 4;
   */
  valueMinor: bigint;

  /**
   * @generated from field: double percentage = 5;
   */
  percentage: number;

  constructor(data?: PartialMessage<GeoExposure>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GeoExposure";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeoExposure;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeoExposure;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeoExposure;

  static equals(a: GeoExposure | PlainMessage<GeoExposure> | undefined, b: GeoExposure | PlainMessage<GeoExposure> | undefined): boolean;
}

/**
 * @generated from message v1.CurrencyExposure
 */
export declare class CurrencyExposure extends Message<CurrencyExposure> {
  /**
   * @generated from field: string currency = 1;
   */
  currency: string;

  /**
   * @generated from field: bool is_hedged = 2;
   */
  isHedged: boolean;

  /**
   * @generated from field: int64 value_minor = 3;
   */
  valueMinor: bigint;

  /**
   * @generated from field: double percentage = 4;
   */
  percentage: number;

  /**
   * @generated from field: int64 fx_impact_5pct_minor = 5;
   */
  fxImpact5pctMinor: bigint;

  constructor(data?: PartialMessage<CurrencyExposure>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CurrencyExposure";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CurrencyExposure;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CurrencyExposure;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CurrencyExposure;

  static equals(a: CurrencyExposure | PlainMessage<CurrencyExposure> | undefined, b: CurrencyExposure | PlainMessage<CurrencyExposure> | undefined): boolean;
}

/**
 * @generated from message v1.GetGeoRadarResponse
 */
export declare class GetGeoRadarResponse extends Message<GetGeoRadarResponse> {
  /**
   * @generated from field: repeated v1.GeoExposure regions = 1;
   */
  regions: GeoExposure[];

  /**
   * @generated from field: repeated v1.GeoExposure countries = 2;
   */
  countries: GeoExposure[];

  /**
   * @generated from field: repeated v1.CurrencyExposure currencies = 3;
   */
  currencies: CurrencyExposure[];

  /**
   * @generated from field: repeated v1.Diagnostic diagnostics = 4;
   */
  diagnostics: Diagnostic[];

  /**
   * @generated from field: double current_eur_usd_rate = 5;
   */
  currentEurUsdRate: number;

  constructor(data?: PartialMessage<GetGeoRadarResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetGeoRadarResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetGeoRadarResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetGeoRadarResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetGeoRadarResponse;

  static equals(a: GetGeoRadarResponse | PlainMessage<GetGeoRadarResponse> | undefined, b: GetGeoRadarResponse | PlainMessage<GetGeoRadarResponse> | undefined): boolean;
}

