// @generated by protoc-gen-es v1.10.0
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.InstrumentAllocation
 */
export declare class InstrumentAllocation extends Message<InstrumentAllocation> {
  /**
   * @generated from field: string asset_class = 1;
   */
  assetClass: string;

  /**
   * @generated from field: int64 value_minor = 2;
   */
  valueMinor: bigint;

  constructor(data?: PartialMessage<InstrumentAllocation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.InstrumentAllocation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InstrumentAllocation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InstrumentAllocation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InstrumentAllocation;

  static equals(a: InstrumentAllocation | PlainMessage<InstrumentAllocation> | undefined, b: InstrumentAllocation | PlainMessage<InstrumentAllocation> | undefined): boolean;
}

/**
 * @generated from message v1.CurrencySummary
 */
export declare class CurrencySummary extends Message<CurrencySummary> {
  /**
   * @generated from field: string currency = 1;
   */
  currency: string;

  /**
   * @generated from field: int64 balance_minor = 2;
   */
  balanceMinor: bigint;

  /**
   * @generated from field: int64 gross_revenue_minor = 3;
   */
  grossRevenueMinor: bigint;

  /**
   * @generated from field: int64 tax_minor = 4;
   */
  taxMinor: bigint;

  /**
   * @generated from field: int64 fees_minor = 5;
   */
  feesMinor: bigint;

  /**
   * @generated from field: int64 net_revenue_minor = 6;
   */
  netRevenueMinor: bigint;

  /**
   * @generated from field: int64 invested_minor = 7;
   */
  investedMinor: bigint;

  /**
   * @generated from field: int64 portfolio_minor = 8;
   */
  portfolioMinor: bigint;

  /**
   * @generated from field: int64 total_minor = 9;
   */
  totalMinor: bigint;

  /**
   * @generated from field: repeated v1.InstrumentAllocation allocations = 10;
   */
  allocations: InstrumentAllocation[];

  constructor(data?: PartialMessage<CurrencySummary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.CurrencySummary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CurrencySummary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CurrencySummary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CurrencySummary;

  static equals(a: CurrencySummary | PlainMessage<CurrencySummary> | undefined, b: CurrencySummary | PlainMessage<CurrencySummary> | undefined): boolean;
}

/**
 * @generated from message v1.Diagnostic
 */
export declare class Diagnostic extends Message<Diagnostic> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string category = 2;
   */
  category: string;

  /**
   * @generated from field: string severity = 3;
   */
  severity: string;

  /**
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * @generated from field: string message = 5;
   */
  message: string;

  /**
   * @generated from field: int64 holding_id = 6;
   */
  holdingId: bigint;

  /**
   * @generated from field: int64 account_id = 7;
   */
  accountId: bigint;

  /**
   * @generated from field: string isin = 8;
   */
  isin: string;

  constructor(data?: PartialMessage<Diagnostic>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Diagnostic";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Diagnostic;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Diagnostic;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Diagnostic;

  static equals(a: Diagnostic | PlainMessage<Diagnostic> | undefined, b: Diagnostic | PlainMessage<Diagnostic> | undefined): boolean;
}

/**
 * @generated from message v1.Summary
 */
export declare class Summary extends Message<Summary> {
  /**
   * @generated from field: string base_currency = 1;
   */
  baseCurrency: string;

  /**
   * @generated from field: repeated v1.CurrencySummary currencies = 2;
   */
  currencies: CurrencySummary[];

  /**
   * @generated from field: repeated v1.Diagnostic diagnostics = 3;
   */
  diagnostics: Diagnostic[];

  constructor(data?: PartialMessage<Summary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.Summary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Summary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Summary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Summary;

  static equals(a: Summary | PlainMessage<Summary> | undefined, b: Summary | PlainMessage<Summary> | undefined): boolean;
}

/**
 * @generated from message v1.GetSummaryRequest
 */
export declare class GetSummaryRequest extends Message<GetSummaryRequest> {
  constructor(data?: PartialMessage<GetSummaryRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetSummaryRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSummaryRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSummaryRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSummaryRequest;

  static equals(a: GetSummaryRequest | PlainMessage<GetSummaryRequest> | undefined, b: GetSummaryRequest | PlainMessage<GetSummaryRequest> | undefined): boolean;
}

/**
 * @generated from message v1.GetSummaryResponse
 */
export declare class GetSummaryResponse extends Message<GetSummaryResponse> {
  /**
   * @generated from field: v1.Summary summary = 1;
   */
  summary?: Summary;

  constructor(data?: PartialMessage<GetSummaryResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.GetSummaryResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetSummaryResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetSummaryResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetSummaryResponse;

  static equals(a: GetSummaryResponse | PlainMessage<GetSummaryResponse> | undefined, b: GetSummaryResponse | PlainMessage<GetSummaryResponse> | undefined): boolean;
}

