// @generated by protoc-gen-es v2.16.0
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/summary.proto.
 */
export declare const file_v1_summary: GenFile;

/**
 * InstrumentAllocation represents portfolio allocation breakdown per asset class.
 *
 * @generated from message v1.InstrumentAllocation
 */
export declare type InstrumentAllocation = Message<"v1.InstrumentAllocation"> & {
  /**
   * Asset class name e.g. "equity", "bond", "commodity", "cash".
   *
   * @generated from field: string asset_class = 1;
   */
  assetClass: string;

  /**
   * Total market value in minor units (cents).
   *
   * @generated from field: int64 value_minor = 2;
   */
  valueMinor: bigint;
};

/**
 * Describes the message v1.InstrumentAllocation.
 * Use `create(InstrumentAllocationSchema)` to create a new message.
 */
export declare const InstrumentAllocationSchema: GenMessage<InstrumentAllocation>;

/**
 * CurrencySummary provides aggregated total wealth, cash balances, yields, and allocation breakdown per currency.
 *
 * @generated from message v1.CurrencySummary
 */
export declare type CurrencySummary = Message<"v1.CurrencySummary"> & {
  /**
   * Currency code e.g. "EUR", "USD".
   *
   * @generated from field: string currency = 1;
   */
  currency: string;

  /**
   * Total cash balance across accounts in minor units (cents).
   *
   * @generated from field: int64 balance_minor = 2;
   */
  balanceMinor: bigint;

  /**
   * Total gross interest revenue in minor units (cents).
   *
   * @generated from field: int64 gross_revenue_minor = 3;
   */
  grossRevenueMinor: bigint;

  /**
   * Total interest tax in minor units (cents).
   *
   * @generated from field: int64 tax_minor = 4;
   */
  taxMinor: bigint;

  /**
   * Total account annual fees in minor units (cents).
   *
   * @generated from field: int64 fees_minor = 5;
   */
  feesMinor: bigint;

  /**
   * Total net interest revenue in minor units (cents).
   *
   * @generated from field: int64 net_revenue_minor = 6;
   */
  netRevenueMinor: bigint;

  /**
   * Total invested cost basis in minor units (cents).
   *
   * @generated from field: int64 invested_minor = 7;
   */
  investedMinor: bigint;

  /**
   * Total portfolio investments market value in minor units (cents).
   *
   * @generated from field: int64 portfolio_minor = 8;
   */
  portfolioMinor: bigint;

  /**
   * Total net worth (cash balance + investments market value) in minor units (cents).
   *
   * @generated from field: int64 total_minor = 9;
   */
  totalMinor: bigint;

  /**
   * Asset class allocation breakdown.
   *
   * @generated from field: repeated v1.InstrumentAllocation allocations = 10;
   */
  allocations: InstrumentAllocation[];
};

/**
 * Describes the message v1.CurrencySummary.
 * Use `create(CurrencySummarySchema)` to create a new message.
 */
export declare const CurrencySummarySchema: GenMessage<CurrencySummary>;

/**
 * Diagnostic represents an active portfolio health warning, fee drag alert, or cash goal alert.
 *
 * @generated from message v1.Diagnostic
 */
export declare type Diagnostic = Message<"v1.Diagnostic"> & {
  /**
   * Diagnostic alert ID.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Category e.g. "allocation", "fee", "cash", "account".
   *
   * @generated from field: string category = 2;
   */
  category: string;

  /**
   * Severity level: "info", "warning", or "alert".
   *
   * @generated from field: string severity = 3;
   */
  severity: string;

  /**
   * Alert title e.g. "High TER Fee Drag Detected", "Cash Reserve Below Target Goal".
   *
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * Detailed diagnostic message and recommendation.
   *
   * @generated from field: string message = 5;
   */
  message: string;

  /**
   * @generated from field: int64 holding_id = 6;
   */
  holdingId: bigint;

  /**
   * @generated from field: int64 account_id = 7;
   */
  accountId: bigint;

  /**
   * @generated from field: string isin = 8;
   */
  isin: string;
};

/**
 * Describes the message v1.Diagnostic.
 * Use `create(DiagnosticSchema)` to create a new message.
 */
export declare const DiagnosticSchema: GenMessage<Diagnostic>;

/**
 * Summary represents the comprehensive portfolio state and health diagnostics.
 *
 * @generated from message v1.Summary
 */
export declare type Summary = Message<"v1.Summary"> & {
  /**
   * Primary base currency code.
   *
   * @generated from field: string base_currency = 1;
   */
  baseCurrency: string;

  /**
   * Aggregated totals per currency.
   *
   * @generated from field: repeated v1.CurrencySummary currencies = 2;
   */
  currencies: CurrencySummary[];

  /**
   * Active health warnings and allocation diagnostics.
   *
   * @generated from field: repeated v1.Diagnostic diagnostics = 3;
   */
  diagnostics: Diagnostic[];
};

/**
 * Describes the message v1.Summary.
 * Use `create(SummarySchema)` to create a new message.
 */
export declare const SummarySchema: GenMessage<Summary>;

/**
 * @generated from message v1.GetSummaryRequest
 */
export declare type GetSummaryRequest = Message<"v1.GetSummaryRequest"> & {
  /**
   * Optional emergency cash reserve goal target in minor units (cents).
   *
   * @generated from field: optional int64 target_cash_minor = 1;
   */
  targetCashMinor?: bigint | undefined;
};

/**
 * Describes the message v1.GetSummaryRequest.
 * Use `create(GetSummaryRequestSchema)` to create a new message.
 */
export declare const GetSummaryRequestSchema: GenMessage<GetSummaryRequest>;

/**
 * @generated from message v1.GetSummaryResponse
 */
export declare type GetSummaryResponse = Message<"v1.GetSummaryResponse"> & {
  /**
   * @generated from field: v1.Summary summary = 1;
   */
  summary?: Summary | undefined;
};

/**
 * Describes the message v1.GetSummaryResponse.
 * Use `create(GetSummaryResponseSchema)` to create a new message.
 */
export declare const GetSummaryResponseSchema: GenMessage<GetSummaryResponse>;

/**
 * @generated from message v1.GetGeoRadarRequest
 */
export declare type GetGeoRadarRequest = Message<"v1.GetGeoRadarRequest"> & {
  /**
   * @generated from field: optional bool include_cash = 1;
   */
  includeCash?: boolean | undefined;
};

/**
 * Describes the message v1.GetGeoRadarRequest.
 * Use `create(GetGeoRadarRequestSchema)` to create a new message.
 */
export declare const GetGeoRadarRequestSchema: GenMessage<GetGeoRadarRequest>;

/**
 * @generated from message v1.GeoExposure
 */
export declare type GeoExposure = Message<"v1.GeoExposure"> & {
  /**
   * @generated from field: string region = 1;
   */
  region: string;

  /**
   * @generated from field: string country_code = 2;
   */
  countryCode: string;

  /**
   * @generated from field: string country_name = 3;
   */
  countryName: string;

  /**
   * @generated from field: int64 value_minor = 4;
   */
  valueMinor: bigint;

  /**
   * @generated from field: double percentage = 5;
   */
  percentage: number;
};

/**
 * Describes the message v1.GeoExposure.
 * Use `create(GeoExposureSchema)` to create a new message.
 */
export declare const GeoExposureSchema: GenMessage<GeoExposure>;

/**
 * @generated from message v1.CurrencyExposure
 */
export declare type CurrencyExposure = Message<"v1.CurrencyExposure"> & {
  /**
   * @generated from field: string currency = 1;
   */
  currency: string;

  /**
   * @generated from field: bool is_hedged = 2;
   */
  isHedged: boolean;

  /**
   * @generated from field: int64 value_minor = 3;
   */
  valueMinor: bigint;

  /**
   * @generated from field: double percentage = 4;
   */
  percentage: number;

  /**
   * @generated from field: int64 fx_impact_5pct_minor = 5;
   */
  fxImpact5pctMinor: bigint;
};

/**
 * Describes the message v1.CurrencyExposure.
 * Use `create(CurrencyExposureSchema)` to create a new message.
 */
export declare const CurrencyExposureSchema: GenMessage<CurrencyExposure>;

/**
 * @generated from message v1.GetGeoRadarResponse
 */
export declare type GetGeoRadarResponse = Message<"v1.GetGeoRadarResponse"> & {
  /**
   * @generated from field: repeated v1.GeoExposure regions = 1;
   */
  regions: GeoExposure[];

  /**
   * @generated from field: repeated v1.GeoExposure countries = 2;
   */
  countries: GeoExposure[];

  /**
   * @generated from field: repeated v1.CurrencyExposure currencies = 3;
   */
  currencies: CurrencyExposure[];

  /**
   * @generated from field: repeated v1.Diagnostic diagnostics = 4;
   */
  diagnostics: Diagnostic[];

  /**
   * @generated from field: double current_eur_usd_rate = 5;
   */
  currentEurUsdRate: number;

  /**
   * @generated from field: string current_eur_usd_observed_on = 6;
   */
  currentEurUsdObservedOn: string;

  /**
   * @generated from field: string current_eur_usd_source_url = 7;
   */
  currentEurUsdSourceUrl: string;
};

/**
 * Describes the message v1.GetGeoRadarResponse.
 * Use `create(GetGeoRadarResponseSchema)` to create a new message.
 */
export declare const GetGeoRadarResponseSchema: GenMessage<GetGeoRadarResponse>;

/**
 * SummaryService provides aggregated wealth totals, currency summaries, portfolio health diagnostics, and geographic risk exposure.
 *
 * @generated from service v1.SummaryService
 */
export declare const SummaryService: GenService<{
  /**
   * Get aggregated portfolio wealth summary, net worth, interest yields, and active health diagnostics.
   *
   * @generated from rpc v1.SummaryService.GetSummary
   */
  getSummary: {
    methodKind: "unary";
    input: typeof GetSummaryRequestSchema;
    output: typeof GetSummaryResponseSchema;
  },
  /**
   * Get geographic country breakdown, underlying currency exposure, and FX sensitivity analysis.
   *
   * @generated from rpc v1.SummaryService.GetGeoRadar
   */
  getGeoRadar: {
    methodKind: "unary";
    input: typeof GetGeoRadarRequestSchema;
    output: typeof GetGeoRadarResponseSchema;
  },
}>;

