// @generated by protoc-gen-es v1.10.0
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * InstrumentAllocation represents portfolio allocation breakdown per asset class.
 *
 * @generated from message v1.InstrumentAllocation
 */
export const InstrumentAllocation = /*@__PURE__*/ proto3.makeMessageType(
  "v1.InstrumentAllocation",
  () => [
    { no: 1, name: "asset_class", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * CurrencySummary provides aggregated total wealth, cash balances, yields, and allocation breakdown per currency.
 *
 * @generated from message v1.CurrencySummary
 */
export const CurrencySummary = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CurrencySummary",
  () => [
    { no: 1, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "balance_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "gross_revenue_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "tax_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "fees_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "net_revenue_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "invested_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "portfolio_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 9, name: "total_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "allocations", kind: "message", T: InstrumentAllocation, repeated: true },
  ],
);

/**
 * Diagnostic represents an active portfolio health warning, fee drag alert, or cash goal alert.
 *
 * @generated from message v1.Diagnostic
 */
export const Diagnostic = /*@__PURE__*/ proto3.makeMessageType(
  "v1.Diagnostic",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "category", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "severity", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "holding_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 7, name: "account_id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 8, name: "isin", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Summary represents the comprehensive portfolio state and health diagnostics.
 *
 * @generated from message v1.Summary
 */
export const Summary = /*@__PURE__*/ proto3.makeMessageType(
  "v1.Summary",
  () => [
    { no: 1, name: "base_currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "currencies", kind: "message", T: CurrencySummary, repeated: true },
    { no: 3, name: "diagnostics", kind: "message", T: Diagnostic, repeated: true },
  ],
);

/**
 * @generated from message v1.GetSummaryRequest
 */
export const GetSummaryRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GetSummaryRequest",
  () => [
    { no: 1, name: "target_cash_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
  ],
);

/**
 * @generated from message v1.GetSummaryResponse
 */
export const GetSummaryResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GetSummaryResponse",
  () => [
    { no: 1, name: "summary", kind: "message", T: Summary },
  ],
);

/**
 * @generated from message v1.GetGeoRadarRequest
 */
export const GetGeoRadarRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GetGeoRadarRequest",
  () => [
    { no: 1, name: "include_cash", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
  ],
);

/**
 * @generated from message v1.GeoExposure
 */
export const GeoExposure = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GeoExposure",
  () => [
    { no: 1, name: "region", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "country_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "country_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "value_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "percentage", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message v1.CurrencyExposure
 */
export const CurrencyExposure = /*@__PURE__*/ proto3.makeMessageType(
  "v1.CurrencyExposure",
  () => [
    { no: 1, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_hedged", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "value_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "percentage", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "fx_impact_5pct_minor", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

/**
 * @generated from message v1.GetGeoRadarResponse
 */
export const GetGeoRadarResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.GetGeoRadarResponse",
  () => [
    { no: 1, name: "regions", kind: "message", T: GeoExposure, repeated: true },
    { no: 2, name: "countries", kind: "message", T: GeoExposure, repeated: true },
    { no: 3, name: "currencies", kind: "message", T: CurrencyExposure, repeated: true },
    { no: 4, name: "diagnostics", kind: "message", T: Diagnostic, repeated: true },
    { no: 5, name: "current_eur_usd_rate", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

