// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/summary.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetSummaryRequest, GetSummaryResponse } from "./summary_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.SummaryService
 */
export declare const SummaryService: {
  readonly typeName: "v1.SummaryService",
  readonly methods: {
    /**
     * @generated from rpc v1.SummaryService.GetSummary
     */
    readonly getSummary: {
      readonly name: "GetSummary",
      readonly I: typeof GetSummaryRequest,
      readonly O: typeof GetSummaryResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

