// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteChatSessionRequest, DeleteChatSessionResponse, DownloadAIModelRequest, DownloadAIModelResponse, ExportBackupRequest, ExportBackupResponse, GetChatSessionRequest, GetChatSessionResponse, GetChatStatusRequest, GetChatStatusResponse, ListAIModelsRequest, ListAIModelsResponse, ListChatSessionsRequest, ListChatSessionsResponse, ListOllamaModelsRequest, ListOllamaModelsResponse, LoadOllamaModelRequest, LoadOllamaModelResponse, RestartLocalServerRequest, RestartLocalServerResponse, RestoreBackupRequest, RestoreBackupResponse, SaveChatSessionRequest, SaveChatSessionResponse, StopChatSessionRequest, StopChatSessionResponse, StreamChatRequest, StreamChatResponse } from "./system_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SystemService manages database backups, system state, local AI models, and Connect Protobuf AI streaming.
 *
 * @generated from service v1.SystemService
 */
export const SystemService = {
  typeName: "v1.SystemService",
  methods: {
    /**
     * Export a portable plaintext JSON backup of the current user's data.
     *
     * @generated from rpc v1.SystemService.ExportBackup
     */
    exportBackup: {
      name: "ExportBackup",
      I: ExportBackupRequest,
      O: ExportBackupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the database state from a backup archive.
     *
     * @generated from rpc v1.SystemService.RestoreBackup
     */
    restoreBackup: {
      name: "RestoreBackup",
      I: RestoreBackupRequest,
      O: RestoreBackupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List available recommended and downloaded open-weights AI models in data/models/.
     *
     * @generated from rpc v1.SystemService.ListAIModels
     */
    listAIModels: {
      name: "ListAIModels",
      I: ListAIModelsRequest,
      O: ListAIModelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download an open-weights GGUF AI model into data/models/ given a name or Hugging Face repo.
     *
     * @generated from rpc v1.SystemService.DownloadAIModel
     */
    downloadAIModel: {
      name: "DownloadAIModel",
      I: DownloadAIModelRequest,
      O: DownloadAIModelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stream AI assistant chat tokens and MCP tool calls over Connect Protobuf server-streaming.
     *
     * @generated from rpc v1.SystemService.StreamChat
     */
    streamChat: {
      name: "StreamChat",
      I: StreamChatRequest,
      O: StreamChatResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * List models available in a running Ollama instance.
     *
     * @generated from rpc v1.SystemService.ListOllamaModels
     */
    listOllamaModels: {
      name: "ListOllamaModels",
      I: ListOllamaModelsRequest,
      O: ListOllamaModelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Load an Ollama model into memory with the specified context size.
     *
     * @generated from rpc v1.SystemService.LoadOllamaModel
     */
    loadOllamaModel: {
      name: "LoadOllamaModel",
      I: LoadOllamaModelRequest,
      O: LoadOllamaModelResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restart the managed local llama-server process with a new model and context size.
     *
     * @generated from rpc v1.SystemService.RestartLocalServer
     */
    restartLocalServer: {
      name: "RestartLocalServer",
      I: RestartLocalServerRequest,
      O: RestartLocalServerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List persistent AI Consultant chat sessions.
     *
     * @generated from rpc v1.SystemService.ListChatSessions
     */
    listChatSessions: {
      name: "ListChatSessions",
      I: ListChatSessionsRequest,
      O: ListChatSessionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get details and message history of a chat session.
     *
     * @generated from rpc v1.SystemService.GetChatSession
     */
    getChatSession: {
      name: "GetChatSession",
      I: GetChatSessionRequest,
      O: GetChatSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Save or update an AI Consultant chat session and its messages.
     *
     * @generated from rpc v1.SystemService.SaveChatSession
     */
    saveChatSession: {
      name: "SaveChatSession",
      I: SaveChatSessionRequest,
      O: SaveChatSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an AI Consultant chat session.
     *
     * @generated from rpc v1.SystemService.DeleteChatSession
     */
    deleteChatSession: {
      name: "DeleteChatSession",
      I: DeleteChatSessionRequest,
      O: DeleteChatSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Stop background generation for an active chat session.
     *
     * @generated from rpc v1.SystemService.StopChatSession
     */
    stopChatSession: {
      name: "StopChatSession",
      I: StopChatSessionRequest,
      O: StopChatSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Get current active generation status for a chat session.
     *
     * @generated from rpc v1.SystemService.GetChatStatus
     */
    getChatStatus: {
      name: "GetChatStatus",
      I: GetChatStatusRequest,
      O: GetChatStatusResponse,
      kind: MethodKind.Unary,
    },
  }
};

