// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ExportBackupRequest, ExportBackupResponse, RestoreBackupRequest, RestoreBackupResponse } from "./system_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.SystemService
 */
export const SystemService = {
  typeName: "v1.SystemService",
  methods: {
    /**
     * @generated from rpc v1.SystemService.ExportBackup
     */
    exportBackup: {
      name: "ExportBackup",
      I: ExportBackupRequest,
      O: ExportBackupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SystemService.RestoreBackup
     */
    restoreBackup: {
      name: "RestoreBackup",
      I: RestoreBackupRequest,
      O: RestoreBackupResponse,
      kind: MethodKind.Unary,
    },
  }
};

