// @generated by protoc-gen-es v2.16.0
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/system.proto.
 */
export declare const file_v1_system: GenFile;

/**
 * @generated from message v1.ExportBackupRequest
 */
export declare type ExportBackupRequest = Message<"v1.ExportBackupRequest"> & {
};

/**
 * Describes the message v1.ExportBackupRequest.
 * Use `create(ExportBackupRequestSchema)` to create a new message.
 */
export declare const ExportBackupRequestSchema: GenMessage<ExportBackupRequest>;

/**
 * @generated from message v1.ExportBackupResponse
 */
export declare type ExportBackupResponse = Message<"v1.ExportBackupResponse"> & {
  /**
   * JSON backup of the authenticated user's data.
   *
   * @generated from field: bytes backup_data = 1;
   */
  backupData: Uint8Array;

  /**
   * Suggested backup filename (e.g. squirrel-backup-2024-01-01.json).
   *
   * @generated from field: string filename = 2;
   */
  filename: string;
};

/**
 * Describes the message v1.ExportBackupResponse.
 * Use `create(ExportBackupResponseSchema)` to create a new message.
 */
export declare const ExportBackupResponseSchema: GenMessage<ExportBackupResponse>;

/**
 * @generated from message v1.RestoreBackupRequest
 */
export declare type RestoreBackupRequest = Message<"v1.RestoreBackupRequest"> & {
  /**
   * JSON backup payload as produced by ExportBackup.
   *
   * @generated from field: bytes backup_data = 1;
   */
  backupData: Uint8Array;
};

/**
 * Describes the message v1.RestoreBackupRequest.
 * Use `create(RestoreBackupRequestSchema)` to create a new message.
 */
export declare const RestoreBackupRequestSchema: GenMessage<RestoreBackupRequest>;

/**
 * @generated from message v1.RestoreBackupResponse
 */
export declare type RestoreBackupResponse = Message<"v1.RestoreBackupResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message v1.RestoreBackupResponse.
 * Use `create(RestoreBackupResponseSchema)` to create a new message.
 */
export declare const RestoreBackupResponseSchema: GenMessage<RestoreBackupResponse>;

/**
 * @generated from message v1.ListAIModelsRequest
 */
export declare type ListAIModelsRequest = Message<"v1.ListAIModelsRequest"> & {
};

/**
 * Describes the message v1.ListAIModelsRequest.
 * Use `create(ListAIModelsRequestSchema)` to create a new message.
 */
export declare const ListAIModelsRequestSchema: GenMessage<ListAIModelsRequest>;

/**
 * AIModelInfo represents an available or downloaded open-weights GGUF AI model.
 *
 * @generated from message v1.AIModelInfo
 */
export declare type AIModelInfo = Message<"v1.AIModelInfo"> & {
  /**
   * Model identifier e.g. "qwen2.5-3b-instruct".
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-readable model display name.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * File name in data/models/ directory e.g. "qwen2.5-3b-instruct-q4_k_m.gguf".
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * File size in bytes (0 if not yet downloaded).
   *
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  /**
   * Whether the model file is already saved in data/models/.
   *
   * @generated from field: bool is_downloaded = 5;
   */
  isDownloaded: boolean;

  /**
   * Direct download URL on Hugging Face.
   *
   * @generated from field: string source_url = 6;
   */
  sourceUrl: string;

  /**
   * Model description and specs.
   *
   * @generated from field: string description = 7;
   */
  description: string;

  /**
   * Current live download progress percentage (0 to 100).
   *
   * @generated from field: int32 download_percent = 8;
   */
  downloadPercent: number;

  /**
   * Whether this model is currently downloading in background.
   *
   * @generated from field: bool is_downloading = 9;
   */
  isDownloading: boolean;
};

/**
 * Describes the message v1.AIModelInfo.
 * Use `create(AIModelInfoSchema)` to create a new message.
 */
export declare const AIModelInfoSchema: GenMessage<AIModelInfo>;

/**
 * @generated from message v1.ListAIModelsResponse
 */
export declare type ListAIModelsResponse = Message<"v1.ListAIModelsResponse"> & {
  /**
   * @generated from field: repeated v1.AIModelInfo models = 1;
   */
  models: AIModelInfo[];
};

/**
 * Describes the message v1.ListAIModelsResponse.
 * Use `create(ListAIModelsResponseSchema)` to create a new message.
 */
export declare const ListAIModelsResponseSchema: GenMessage<ListAIModelsResponse>;

/**
 * @generated from message v1.DownloadAIModelRequest
 */
export declare type DownloadAIModelRequest = Message<"v1.DownloadAIModelRequest"> & {
  /**
   * Model ID or Hugging Face repository name (e.g. "Qwen/Qwen2.5-1.5B-Instruct-GGUF").
   *
   * @generated from field: string model_name = 1;
   */
  modelName: string;

  /**
   * Optional direct GGUF URL override.
   *
   * @generated from field: string url_override = 2;
   */
  urlOverride: string;
};

/**
 * Describes the message v1.DownloadAIModelRequest.
 * Use `create(DownloadAIModelRequestSchema)` to create a new message.
 */
export declare const DownloadAIModelRequestSchema: GenMessage<DownloadAIModelRequest>;

/**
 * @generated from message v1.DownloadAIModelResponse
 */
export declare type DownloadAIModelResponse = Message<"v1.DownloadAIModelResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string model_id = 3;
   */
  modelId: string;

  /**
   * @generated from field: string file_path = 4;
   */
  filePath: string;
};

/**
 * Describes the message v1.DownloadAIModelResponse.
 * Use `create(DownloadAIModelResponseSchema)` to create a new message.
 */
export declare const DownloadAIModelResponseSchema: GenMessage<DownloadAIModelResponse>;

/**
 * ChatMessagePayload represents a message turn in conversation history.
 *
 * @generated from message v1.ChatMessagePayload
 */
export declare type ChatMessagePayload = Message<"v1.ChatMessagePayload"> & {
  /**
   * @generated from field: string role = 1;
   */
  role: string;

  /**
   * @generated from field: string content = 2;
   */
  content: string;
};

/**
 * Describes the message v1.ChatMessagePayload.
 * Use `create(ChatMessagePayloadSchema)` to create a new message.
 */
export declare const ChatMessagePayloadSchema: GenMessage<ChatMessagePayload>;

/**
 * StreamChatRequest passes AI provider credentials, model selection, chat history, portfolio context, and max context window size.
 *
 * @generated from message v1.StreamChatRequest
 */
export declare type StreamChatRequest = Message<"v1.StreamChatRequest"> & {
  /**
   * @generated from field: string provider = 1;
   */
  provider: string;

  /**
   * @generated from field: string endpoint = 2;
   */
  endpoint: string;

  /**
   * @generated from field: string model = 3;
   */
  model: string;

  /**
   * @generated from field: string api_key = 4;
   */
  apiKey: string;

  /**
   * @generated from field: repeated v1.ChatMessagePayload messages = 5;
   */
  messages: ChatMessagePayload[];

  /**
   * @generated from field: string portfolio_context_json = 6;
   */
  portfolioContextJson: string;

  /**
   * @generated from field: int32 context_size = 7;
   */
  contextSize: number;

  /**
   * @generated from field: string session_id = 8;
   */
  sessionId: string;
};

/**
 * Describes the message v1.StreamChatRequest.
 * Use `create(StreamChatRequestSchema)` to create a new message.
 */
export declare const StreamChatRequestSchema: GenMessage<StreamChatRequest>;

/**
 * StreamChatResponse represents streaming token chunks or MCP tool execution events.
 *
 * @generated from message v1.StreamChatResponse
 */
export declare type StreamChatResponse = Message<"v1.StreamChatResponse"> & {
  /**
   * @generated from field: string delta_text = 1;
   */
  deltaText: string;

  /**
   * @generated from field: bool is_mcp_tool_call = 2;
   */
  isMcpToolCall: boolean;

  /**
   * @generated from field: string tool_name = 3;
   */
  toolName: string;

  /**
   * @generated from field: string tool_args_json = 4;
   */
  toolArgsJson: string;

  /**
   * @generated from field: string tool_result_json = 5;
   */
  toolResultJson: string;

  /**
   * @generated from field: bool done = 6;
   */
  done: boolean;

  /**
   * Actual server context window detected at request time (0 if unknown).
   *
   * @generated from field: int32 actual_n_ctx = 7;
   */
  actualNCtx: number;

  /**
   * Actionable provider or request error. A non-empty value terminates the stream.
   *
   * @generated from field: string error_message = 8;
   */
  errorMessage: string;
};

/**
 * Describes the message v1.StreamChatResponse.
 * Use `create(StreamChatResponseSchema)` to create a new message.
 */
export declare const StreamChatResponseSchema: GenMessage<StreamChatResponse>;

/**
 * @generated from message v1.RestartLocalServerRequest
 */
export declare type RestartLocalServerRequest = Message<"v1.RestartLocalServerRequest"> & {
  /**
   * @generated from field: string model_filename = 1;
   */
  modelFilename: string;

  /**
   * @generated from field: int32 context_size = 2;
   */
  contextSize: number;

  /**
   * @generated from field: int32 port = 3;
   */
  port: number;
};

/**
 * Describes the message v1.RestartLocalServerRequest.
 * Use `create(RestartLocalServerRequestSchema)` to create a new message.
 */
export declare const RestartLocalServerRequestSchema: GenMessage<RestartLocalServerRequest>;

/**
 * @generated from message v1.RestartLocalServerResponse
 */
export declare type RestartLocalServerResponse = Message<"v1.RestartLocalServerResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: int32 port = 3;
   */
  port: number;

  /**
   * @generated from field: int32 actual_n_ctx = 4;
   */
  actualNCtx: number;
};

/**
 * Describes the message v1.RestartLocalServerResponse.
 * Use `create(RestartLocalServerResponseSchema)` to create a new message.
 */
export declare const RestartLocalServerResponseSchema: GenMessage<RestartLocalServerResponse>;

/**
 * @generated from message v1.ListOllamaModelsRequest
 */
export declare type ListOllamaModelsRequest = Message<"v1.ListOllamaModelsRequest"> & {
  /**
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;
};

/**
 * Describes the message v1.ListOllamaModelsRequest.
 * Use `create(ListOllamaModelsRequestSchema)` to create a new message.
 */
export declare const ListOllamaModelsRequestSchema: GenMessage<ListOllamaModelsRequest>;

/**
 * @generated from message v1.OllamaModelInfo
 */
export declare type OllamaModelInfo = Message<"v1.OllamaModelInfo"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int64 size_bytes = 2;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: string modified_at = 3;
   */
  modifiedAt: string;
};

/**
 * Describes the message v1.OllamaModelInfo.
 * Use `create(OllamaModelInfoSchema)` to create a new message.
 */
export declare const OllamaModelInfoSchema: GenMessage<OllamaModelInfo>;

/**
 * @generated from message v1.ListOllamaModelsResponse
 */
export declare type ListOllamaModelsResponse = Message<"v1.ListOllamaModelsResponse"> & {
  /**
   * @generated from field: repeated v1.OllamaModelInfo models = 1;
   */
  models: OllamaModelInfo[];
};

/**
 * Describes the message v1.ListOllamaModelsResponse.
 * Use `create(ListOllamaModelsResponseSchema)` to create a new message.
 */
export declare const ListOllamaModelsResponseSchema: GenMessage<ListOllamaModelsResponse>;

/**
 * @generated from message v1.LoadOllamaModelRequest
 */
export declare type LoadOllamaModelRequest = Message<"v1.LoadOllamaModelRequest"> & {
  /**
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * @generated from field: string model = 2;
   */
  model: string;

  /**
   * @generated from field: int32 context_size = 3;
   */
  contextSize: number;
};

/**
 * Describes the message v1.LoadOllamaModelRequest.
 * Use `create(LoadOllamaModelRequestSchema)` to create a new message.
 */
export declare const LoadOllamaModelRequestSchema: GenMessage<LoadOllamaModelRequest>;

/**
 * @generated from message v1.LoadOllamaModelResponse
 */
export declare type LoadOllamaModelResponse = Message<"v1.LoadOllamaModelResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message v1.LoadOllamaModelResponse.
 * Use `create(LoadOllamaModelResponseSchema)` to create a new message.
 */
export declare const LoadOllamaModelResponseSchema: GenMessage<LoadOllamaModelResponse>;

/**
 * @generated from message v1.ChatMessageData
 */
export declare type ChatMessageData = Message<"v1.ChatMessageData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string role = 2;
   */
  role: string;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: string timestamp = 4;
   */
  timestamp: string;

  /**
   * @generated from field: string tool_calls_json = 5;
   */
  toolCallsJson: string;
};

/**
 * Describes the message v1.ChatMessageData.
 * Use `create(ChatMessageDataSchema)` to create a new message.
 */
export declare const ChatMessageDataSchema: GenMessage<ChatMessageData>;

/**
 * @generated from message v1.ChatSessionData
 */
export declare type ChatSessionData = Message<"v1.ChatSessionData"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string created_at = 3;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 4;
   */
  updatedAt: string;

  /**
   * @generated from field: repeated v1.ChatMessageData messages = 5;
   */
  messages: ChatMessageData[];

  /**
   * @generated from field: int32 message_count = 6;
   */
  messageCount: number;
};

/**
 * Describes the message v1.ChatSessionData.
 * Use `create(ChatSessionDataSchema)` to create a new message.
 */
export declare const ChatSessionDataSchema: GenMessage<ChatSessionData>;

/**
 * @generated from message v1.ListChatSessionsRequest
 */
export declare type ListChatSessionsRequest = Message<"v1.ListChatSessionsRequest"> & {
};

/**
 * Describes the message v1.ListChatSessionsRequest.
 * Use `create(ListChatSessionsRequestSchema)` to create a new message.
 */
export declare const ListChatSessionsRequestSchema: GenMessage<ListChatSessionsRequest>;

/**
 * @generated from message v1.ListChatSessionsResponse
 */
export declare type ListChatSessionsResponse = Message<"v1.ListChatSessionsResponse"> & {
  /**
   * @generated from field: repeated v1.ChatSessionData sessions = 1;
   */
  sessions: ChatSessionData[];
};

/**
 * Describes the message v1.ListChatSessionsResponse.
 * Use `create(ListChatSessionsResponseSchema)` to create a new message.
 */
export declare const ListChatSessionsResponseSchema: GenMessage<ListChatSessionsResponse>;

/**
 * @generated from message v1.GetChatSessionRequest
 */
export declare type GetChatSessionRequest = Message<"v1.GetChatSessionRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message v1.GetChatSessionRequest.
 * Use `create(GetChatSessionRequestSchema)` to create a new message.
 */
export declare const GetChatSessionRequestSchema: GenMessage<GetChatSessionRequest>;

/**
 * @generated from message v1.GetChatSessionResponse
 */
export declare type GetChatSessionResponse = Message<"v1.GetChatSessionResponse"> & {
  /**
   * @generated from field: v1.ChatSessionData session = 1;
   */
  session?: ChatSessionData | undefined;
};

/**
 * Describes the message v1.GetChatSessionResponse.
 * Use `create(GetChatSessionResponseSchema)` to create a new message.
 */
export declare const GetChatSessionResponseSchema: GenMessage<GetChatSessionResponse>;

/**
 * @generated from message v1.SaveChatSessionRequest
 */
export declare type SaveChatSessionRequest = Message<"v1.SaveChatSessionRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: repeated v1.ChatMessageData messages = 3;
   */
  messages: ChatMessageData[];
};

/**
 * Describes the message v1.SaveChatSessionRequest.
 * Use `create(SaveChatSessionRequestSchema)` to create a new message.
 */
export declare const SaveChatSessionRequestSchema: GenMessage<SaveChatSessionRequest>;

/**
 * @generated from message v1.SaveChatSessionResponse
 */
export declare type SaveChatSessionResponse = Message<"v1.SaveChatSessionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: v1.ChatSessionData session = 2;
   */
  session?: ChatSessionData | undefined;
};

/**
 * Describes the message v1.SaveChatSessionResponse.
 * Use `create(SaveChatSessionResponseSchema)` to create a new message.
 */
export declare const SaveChatSessionResponseSchema: GenMessage<SaveChatSessionResponse>;

/**
 * @generated from message v1.DeleteChatSessionRequest
 */
export declare type DeleteChatSessionRequest = Message<"v1.DeleteChatSessionRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message v1.DeleteChatSessionRequest.
 * Use `create(DeleteChatSessionRequestSchema)` to create a new message.
 */
export declare const DeleteChatSessionRequestSchema: GenMessage<DeleteChatSessionRequest>;

/**
 * @generated from message v1.DeleteChatSessionResponse
 */
export declare type DeleteChatSessionResponse = Message<"v1.DeleteChatSessionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message v1.DeleteChatSessionResponse.
 * Use `create(DeleteChatSessionResponseSchema)` to create a new message.
 */
export declare const DeleteChatSessionResponseSchema: GenMessage<DeleteChatSessionResponse>;

/**
 * @generated from message v1.StopChatSessionRequest
 */
export declare type StopChatSessionRequest = Message<"v1.StopChatSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message v1.StopChatSessionRequest.
 * Use `create(StopChatSessionRequestSchema)` to create a new message.
 */
export declare const StopChatSessionRequestSchema: GenMessage<StopChatSessionRequest>;

/**
 * @generated from message v1.StopChatSessionResponse
 */
export declare type StopChatSessionResponse = Message<"v1.StopChatSessionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message v1.StopChatSessionResponse.
 * Use `create(StopChatSessionResponseSchema)` to create a new message.
 */
export declare const StopChatSessionResponseSchema: GenMessage<StopChatSessionResponse>;

/**
 * @generated from message v1.GetChatStatusRequest
 */
export declare type GetChatStatusRequest = Message<"v1.GetChatStatusRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message v1.GetChatStatusRequest.
 * Use `create(GetChatStatusRequestSchema)` to create a new message.
 */
export declare const GetChatStatusRequestSchema: GenMessage<GetChatStatusRequest>;

/**
 * @generated from message v1.GetChatStatusResponse
 */
export declare type GetChatStatusResponse = Message<"v1.GetChatStatusResponse"> & {
  /**
   * @generated from field: bool is_generating = 1;
   */
  isGenerating: boolean;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: int32 actual_n_ctx = 3;
   */
  actualNCtx: number;
};

/**
 * Describes the message v1.GetChatStatusResponse.
 * Use `create(GetChatStatusResponseSchema)` to create a new message.
 */
export declare const GetChatStatusResponseSchema: GenMessage<GetChatStatusResponse>;

/**
 * SystemService manages database backups, system state, local AI models, and Connect Protobuf AI streaming.
 *
 * @generated from service v1.SystemService
 */
export declare const SystemService: GenService<{
  /**
   * Export a portable plaintext JSON backup of the current user's data.
   *
   * @generated from rpc v1.SystemService.ExportBackup
   */
  exportBackup: {
    methodKind: "unary";
    input: typeof ExportBackupRequestSchema;
    output: typeof ExportBackupResponseSchema;
  },
  /**
   * Restore the user's state from a versioned JSON backup.
   *
   * @generated from rpc v1.SystemService.RestoreBackup
   */
  restoreBackup: {
    methodKind: "unary";
    input: typeof RestoreBackupRequestSchema;
    output: typeof RestoreBackupResponseSchema;
  },
  /**
   * List available recommended and downloaded open-weights AI models in data/models/.
   *
   * @generated from rpc v1.SystemService.ListAIModels
   */
  listAIModels: {
    methodKind: "unary";
    input: typeof ListAIModelsRequestSchema;
    output: typeof ListAIModelsResponseSchema;
  },
  /**
   * Download an open-weights GGUF AI model into data/models/ given a name or Hugging Face repo.
   *
   * @generated from rpc v1.SystemService.DownloadAIModel
   */
  downloadAIModel: {
    methodKind: "unary";
    input: typeof DownloadAIModelRequestSchema;
    output: typeof DownloadAIModelResponseSchema;
  },
  /**
   * Stream AI assistant chat tokens and MCP tool calls over Connect Protobuf server-streaming.
   *
   * @generated from rpc v1.SystemService.StreamChat
   */
  streamChat: {
    methodKind: "server_streaming";
    input: typeof StreamChatRequestSchema;
    output: typeof StreamChatResponseSchema;
  },
  /**
   * List models available in a running Ollama instance.
   *
   * @generated from rpc v1.SystemService.ListOllamaModels
   */
  listOllamaModels: {
    methodKind: "unary";
    input: typeof ListOllamaModelsRequestSchema;
    output: typeof ListOllamaModelsResponseSchema;
  },
  /**
   * Load an Ollama model into memory with the specified context size.
   *
   * @generated from rpc v1.SystemService.LoadOllamaModel
   */
  loadOllamaModel: {
    methodKind: "unary";
    input: typeof LoadOllamaModelRequestSchema;
    output: typeof LoadOllamaModelResponseSchema;
  },
  /**
   * Restart the managed local llama-server process with a new model and context size.
   *
   * @generated from rpc v1.SystemService.RestartLocalServer
   */
  restartLocalServer: {
    methodKind: "unary";
    input: typeof RestartLocalServerRequestSchema;
    output: typeof RestartLocalServerResponseSchema;
  },
  /**
   * List persistent AI Consultant chat sessions.
   *
   * @generated from rpc v1.SystemService.ListChatSessions
   */
  listChatSessions: {
    methodKind: "unary";
    input: typeof ListChatSessionsRequestSchema;
    output: typeof ListChatSessionsResponseSchema;
  },
  /**
   * Get details and message history of a chat session.
   *
   * @generated from rpc v1.SystemService.GetChatSession
   */
  getChatSession: {
    methodKind: "unary";
    input: typeof GetChatSessionRequestSchema;
    output: typeof GetChatSessionResponseSchema;
  },
  /**
   * Save or update an AI Consultant chat session and its messages.
   *
   * @generated from rpc v1.SystemService.SaveChatSession
   */
  saveChatSession: {
    methodKind: "unary";
    input: typeof SaveChatSessionRequestSchema;
    output: typeof SaveChatSessionResponseSchema;
  },
  /**
   * Delete an AI Consultant chat session.
   *
   * @generated from rpc v1.SystemService.DeleteChatSession
   */
  deleteChatSession: {
    methodKind: "unary";
    input: typeof DeleteChatSessionRequestSchema;
    output: typeof DeleteChatSessionResponseSchema;
  },
  /**
   * Stop background generation for an active chat session.
   *
   * @generated from rpc v1.SystemService.StopChatSession
   */
  stopChatSession: {
    methodKind: "unary";
    input: typeof StopChatSessionRequestSchema;
    output: typeof StopChatSessionResponseSchema;
  },
  /**
   * Get current active generation status for a chat session.
   *
   * @generated from rpc v1.SystemService.GetChatStatus
   */
  getChatStatus: {
    methodKind: "unary";
    input: typeof GetChatStatusRequestSchema;
    output: typeof GetChatStatusResponseSchema;
  },
}>;

