// @generated by protoc-gen-es v1.10.0
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.ExportBackupRequest
 */
export const ExportBackupRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ExportBackupRequest",
  [],
);

/**
 * @generated from message v1.ExportBackupResponse
 */
export const ExportBackupResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ExportBackupResponse",
  () => [
    { no: 1, name: "backup_tar_gz", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.RestoreBackupRequest
 */
export const RestoreBackupRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RestoreBackupRequest",
  () => [
    { no: 1, name: "backup_tar_gz", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message v1.RestoreBackupResponse
 */
export const RestoreBackupResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RestoreBackupResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.ListAIModelsRequest
 */
export const ListAIModelsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListAIModelsRequest",
  [],
);

/**
 * AIModelInfo represents an available or downloaded open-weights GGUF AI model.
 *
 * @generated from message v1.AIModelInfo
 */
export const AIModelInfo = /*@__PURE__*/ proto3.makeMessageType(
  "v1.AIModelInfo",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "size_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "is_downloaded", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "source_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "download_percent", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "is_downloading", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message v1.ListAIModelsResponse
 */
export const ListAIModelsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListAIModelsResponse",
  () => [
    { no: 1, name: "models", kind: "message", T: AIModelInfo, repeated: true },
  ],
);

/**
 * @generated from message v1.DownloadAIModelRequest
 */
export const DownloadAIModelRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DownloadAIModelRequest",
  () => [
    { no: 1, name: "model_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "url_override", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.DownloadAIModelResponse
 */
export const DownloadAIModelResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.DownloadAIModelResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "model_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "file_path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ChatMessagePayload represents a message turn in conversation history.
 *
 * @generated from message v1.ChatMessagePayload
 */
export const ChatMessagePayload = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ChatMessagePayload",
  () => [
    { no: 1, name: "role", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * StreamChatRequest passes AI provider credentials, model selection, chat history, portfolio context, and max context window size.
 *
 * @generated from message v1.StreamChatRequest
 */
export const StreamChatRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StreamChatRequest",
  () => [
    { no: 1, name: "provider", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "api_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "messages", kind: "message", T: ChatMessagePayload, repeated: true },
    { no: 6, name: "portfolio_context_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "context_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * StreamChatResponse represents streaming token chunks or MCP tool execution events.
 *
 * @generated from message v1.StreamChatResponse
 */
export const StreamChatResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.StreamChatResponse",
  () => [
    { no: 1, name: "delta_text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_mcp_tool_call", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "tool_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "tool_args_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "tool_result_json", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "done", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 7, name: "actual_n_ctx", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.RestartLocalServerRequest
 */
export const RestartLocalServerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RestartLocalServerRequest",
  () => [
    { no: 1, name: "model_filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "context_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.RestartLocalServerResponse
 */
export const RestartLocalServerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.RestartLocalServerResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "actual_n_ctx", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.ListOllamaModelsRequest
 */
export const ListOllamaModelsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListOllamaModelsRequest",
  () => [
    { no: 1, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.OllamaModelInfo
 */
export const OllamaModelInfo = /*@__PURE__*/ proto3.makeMessageType(
  "v1.OllamaModelInfo",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "size_bytes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "modified_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message v1.ListOllamaModelsResponse
 */
export const ListOllamaModelsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.ListOllamaModelsResponse",
  () => [
    { no: 1, name: "models", kind: "message", T: OllamaModelInfo, repeated: true },
  ],
);

/**
 * @generated from message v1.LoadOllamaModelRequest
 */
export const LoadOllamaModelRequest = /*@__PURE__*/ proto3.makeMessageType(
  "v1.LoadOllamaModelRequest",
  () => [
    { no: 1, name: "endpoint", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "model", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "context_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message v1.LoadOllamaModelResponse
 */
export const LoadOllamaModelResponse = /*@__PURE__*/ proto3.makeMessageType(
  "v1.LoadOllamaModelResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

