// @generated by protoc-gen-es v1.10.0
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.ExportBackupRequest
 */
export declare class ExportBackupRequest extends Message<ExportBackupRequest> {
  constructor(data?: PartialMessage<ExportBackupRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ExportBackupRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportBackupRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportBackupRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportBackupRequest;

  static equals(a: ExportBackupRequest | PlainMessage<ExportBackupRequest> | undefined, b: ExportBackupRequest | PlainMessage<ExportBackupRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ExportBackupResponse
 */
export declare class ExportBackupResponse extends Message<ExportBackupResponse> {
  /**
   * @generated from field: bytes backup_tar_gz = 1;
   */
  backupTarGz: Uint8Array;

  /**
   * @generated from field: string filename = 2;
   */
  filename: string;

  constructor(data?: PartialMessage<ExportBackupResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ExportBackupResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportBackupResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportBackupResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportBackupResponse;

  static equals(a: ExportBackupResponse | PlainMessage<ExportBackupResponse> | undefined, b: ExportBackupResponse | PlainMessage<ExportBackupResponse> | undefined): boolean;
}

/**
 * @generated from message v1.RestoreBackupRequest
 */
export declare class RestoreBackupRequest extends Message<RestoreBackupRequest> {
  /**
   * @generated from field: bytes backup_tar_gz = 1;
   */
  backupTarGz: Uint8Array;

  constructor(data?: PartialMessage<RestoreBackupRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RestoreBackupRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RestoreBackupRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RestoreBackupRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RestoreBackupRequest;

  static equals(a: RestoreBackupRequest | PlainMessage<RestoreBackupRequest> | undefined, b: RestoreBackupRequest | PlainMessage<RestoreBackupRequest> | undefined): boolean;
}

/**
 * @generated from message v1.RestoreBackupResponse
 */
export declare class RestoreBackupResponse extends Message<RestoreBackupResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<RestoreBackupResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RestoreBackupResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RestoreBackupResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RestoreBackupResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RestoreBackupResponse;

  static equals(a: RestoreBackupResponse | PlainMessage<RestoreBackupResponse> | undefined, b: RestoreBackupResponse | PlainMessage<RestoreBackupResponse> | undefined): boolean;
}

