// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DownloadAIModelRequest, DownloadAIModelResponse, ExportBackupRequest, ExportBackupResponse, ListAIModelsRequest, ListAIModelsResponse, RestoreBackupRequest, RestoreBackupResponse } from "./system_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service v1.SystemService
 */
export declare const SystemService: {
  readonly typeName: "v1.SystemService",
  readonly methods: {
    /**
     * @generated from rpc v1.SystemService.ExportBackup
     */
    readonly exportBackup: {
      readonly name: "ExportBackup",
      readonly I: typeof ExportBackupRequest,
      readonly O: typeof ExportBackupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SystemService.RestoreBackup
     */
    readonly restoreBackup: {
      readonly name: "RestoreBackup",
      readonly I: typeof RestoreBackupRequest,
      readonly O: typeof RestoreBackupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SystemService.ListAIModels
     */
    readonly listAIModels: {
      readonly name: "ListAIModels",
      readonly I: typeof ListAIModelsRequest,
      readonly O: typeof ListAIModelsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc v1.SystemService.DownloadAIModel
     */
    readonly downloadAIModel: {
      readonly name: "DownloadAIModel",
      readonly I: typeof DownloadAIModelRequest,
      readonly O: typeof DownloadAIModelResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

