// @generated by protoc-gen-es v1.10.0
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message v1.ExportBackupRequest
 */
export declare class ExportBackupRequest extends Message<ExportBackupRequest> {
  constructor(data?: PartialMessage<ExportBackupRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ExportBackupRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportBackupRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportBackupRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportBackupRequest;

  static equals(a: ExportBackupRequest | PlainMessage<ExportBackupRequest> | undefined, b: ExportBackupRequest | PlainMessage<ExportBackupRequest> | undefined): boolean;
}

/**
 * @generated from message v1.ExportBackupResponse
 */
export declare class ExportBackupResponse extends Message<ExportBackupResponse> {
  /**
   * Gzipped tar archive containing database files.
   *
   * @generated from field: bytes backup_tar_gz = 1;
   */
  backupTarGz: Uint8Array;

  /**
   * Suggested backup filename.
   *
   * @generated from field: string filename = 2;
   */
  filename: string;

  constructor(data?: PartialMessage<ExportBackupResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ExportBackupResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExportBackupResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExportBackupResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExportBackupResponse;

  static equals(a: ExportBackupResponse | PlainMessage<ExportBackupResponse> | undefined, b: ExportBackupResponse | PlainMessage<ExportBackupResponse> | undefined): boolean;
}

/**
 * @generated from message v1.RestoreBackupRequest
 */
export declare class RestoreBackupRequest extends Message<RestoreBackupRequest> {
  /**
   * Gzipped tar archive payload.
   *
   * @generated from field: bytes backup_tar_gz = 1;
   */
  backupTarGz: Uint8Array;

  constructor(data?: PartialMessage<RestoreBackupRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RestoreBackupRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RestoreBackupRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RestoreBackupRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RestoreBackupRequest;

  static equals(a: RestoreBackupRequest | PlainMessage<RestoreBackupRequest> | undefined, b: RestoreBackupRequest | PlainMessage<RestoreBackupRequest> | undefined): boolean;
}

/**
 * @generated from message v1.RestoreBackupResponse
 */
export declare class RestoreBackupResponse extends Message<RestoreBackupResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<RestoreBackupResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.RestoreBackupResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RestoreBackupResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RestoreBackupResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RestoreBackupResponse;

  static equals(a: RestoreBackupResponse | PlainMessage<RestoreBackupResponse> | undefined, b: RestoreBackupResponse | PlainMessage<RestoreBackupResponse> | undefined): boolean;
}

/**
 * @generated from message v1.ListAIModelsRequest
 */
export declare class ListAIModelsRequest extends Message<ListAIModelsRequest> {
  constructor(data?: PartialMessage<ListAIModelsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListAIModelsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAIModelsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAIModelsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAIModelsRequest;

  static equals(a: ListAIModelsRequest | PlainMessage<ListAIModelsRequest> | undefined, b: ListAIModelsRequest | PlainMessage<ListAIModelsRequest> | undefined): boolean;
}

/**
 * AIModelInfo represents an available or downloaded open-weights GGUF AI model.
 *
 * @generated from message v1.AIModelInfo
 */
export declare class AIModelInfo extends Message<AIModelInfo> {
  /**
   * Model identifier e.g. "qwen2.5-3b-instruct".
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Human-readable model display name.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * File name in data/models/ directory e.g. "qwen2.5-3b-instruct-q4_k_m.gguf".
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * File size in bytes (0 if not yet downloaded).
   *
   * @generated from field: int64 size_bytes = 4;
   */
  sizeBytes: bigint;

  /**
   * Whether the model file is already saved in data/models/.
   *
   * @generated from field: bool is_downloaded = 5;
   */
  isDownloaded: boolean;

  /**
   * Direct download URL on Hugging Face.
   *
   * @generated from field: string source_url = 6;
   */
  sourceUrl: string;

  /**
   * Model description and specs.
   *
   * @generated from field: string description = 7;
   */
  description: string;

  constructor(data?: PartialMessage<AIModelInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.AIModelInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AIModelInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AIModelInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AIModelInfo;

  static equals(a: AIModelInfo | PlainMessage<AIModelInfo> | undefined, b: AIModelInfo | PlainMessage<AIModelInfo> | undefined): boolean;
}

/**
 * @generated from message v1.ListAIModelsResponse
 */
export declare class ListAIModelsResponse extends Message<ListAIModelsResponse> {
  /**
   * @generated from field: repeated v1.AIModelInfo models = 1;
   */
  models: AIModelInfo[];

  constructor(data?: PartialMessage<ListAIModelsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.ListAIModelsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListAIModelsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListAIModelsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListAIModelsResponse;

  static equals(a: ListAIModelsResponse | PlainMessage<ListAIModelsResponse> | undefined, b: ListAIModelsResponse | PlainMessage<ListAIModelsResponse> | undefined): boolean;
}

/**
 * @generated from message v1.DownloadAIModelRequest
 */
export declare class DownloadAIModelRequest extends Message<DownloadAIModelRequest> {
  /**
   * Model ID or Hugging Face repository name (e.g. "Qwen/Qwen2.5-1.5B-Instruct-GGUF").
   *
   * @generated from field: string model_name = 1;
   */
  modelName: string;

  /**
   * Optional direct GGUF URL override.
   *
   * @generated from field: string url_override = 2;
   */
  urlOverride: string;

  constructor(data?: PartialMessage<DownloadAIModelRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DownloadAIModelRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadAIModelRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadAIModelRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadAIModelRequest;

  static equals(a: DownloadAIModelRequest | PlainMessage<DownloadAIModelRequest> | undefined, b: DownloadAIModelRequest | PlainMessage<DownloadAIModelRequest> | undefined): boolean;
}

/**
 * @generated from message v1.DownloadAIModelResponse
 */
export declare class DownloadAIModelResponse extends Message<DownloadAIModelResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: string model_id = 3;
   */
  modelId: string;

  /**
   * @generated from field: string file_path = 4;
   */
  filePath: string;

  constructor(data?: PartialMessage<DownloadAIModelResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "v1.DownloadAIModelResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DownloadAIModelResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DownloadAIModelResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DownloadAIModelResponse;

  static equals(a: DownloadAIModelResponse | PlainMessage<DownloadAIModelResponse> | undefined, b: DownloadAIModelResponse | PlainMessage<DownloadAIModelResponse> | undefined): boolean;
}

