// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DownloadAIModelRequest, DownloadAIModelResponse, ExportBackupRequest, ExportBackupResponse, ListAIModelsRequest, ListAIModelsResponse, ListOllamaModelsRequest, ListOllamaModelsResponse, LoadOllamaModelRequest, LoadOllamaModelResponse, RestartLocalServerRequest, RestartLocalServerResponse, RestoreBackupRequest, RestoreBackupResponse, StreamChatRequest, StreamChatResponse } from "./system_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SystemService manages database backups, system state, local AI models, and Connect Protobuf AI streaming.
 *
 * @generated from service v1.SystemService
 */
export declare const SystemService: {
  readonly typeName: "v1.SystemService",
  readonly methods: {
    /**
     * Export a complete encrypted backup archive of the SQLite database.
     *
     * @generated from rpc v1.SystemService.ExportBackup
     */
    readonly exportBackup: {
      readonly name: "ExportBackup",
      readonly I: typeof ExportBackupRequest,
      readonly O: typeof ExportBackupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Restore the database state from a backup archive.
     *
     * @generated from rpc v1.SystemService.RestoreBackup
     */
    readonly restoreBackup: {
      readonly name: "RestoreBackup",
      readonly I: typeof RestoreBackupRequest,
      readonly O: typeof RestoreBackupResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * List available recommended and downloaded open-weights AI models in data/models/.
     *
     * @generated from rpc v1.SystemService.ListAIModels
     */
    readonly listAIModels: {
      readonly name: "ListAIModels",
      readonly I: typeof ListAIModelsRequest,
      readonly O: typeof ListAIModelsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Download an open-weights GGUF AI model into data/models/ given a name or Hugging Face repo.
     *
     * @generated from rpc v1.SystemService.DownloadAIModel
     */
    readonly downloadAIModel: {
      readonly name: "DownloadAIModel",
      readonly I: typeof DownloadAIModelRequest,
      readonly O: typeof DownloadAIModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Stream AI assistant chat tokens and MCP tool calls over Connect Protobuf server-streaming.
     *
     * @generated from rpc v1.SystemService.StreamChat
     */
    readonly streamChat: {
      readonly name: "StreamChat",
      readonly I: typeof StreamChatRequest,
      readonly O: typeof StreamChatResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * List models available in a running Ollama instance.
     *
     * @generated from rpc v1.SystemService.ListOllamaModels
     */
    readonly listOllamaModels: {
      readonly name: "ListOllamaModels",
      readonly I: typeof ListOllamaModelsRequest,
      readonly O: typeof ListOllamaModelsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Load an Ollama model into memory with the specified context size.
     *
     * @generated from rpc v1.SystemService.LoadOllamaModel
     */
    readonly loadOllamaModel: {
      readonly name: "LoadOllamaModel",
      readonly I: typeof LoadOllamaModelRequest,
      readonly O: typeof LoadOllamaModelResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Kill and restart the local llama-server process with a new model and context size.
     *
     * @generated from rpc v1.SystemService.RestartLocalServer
     */
    readonly restartLocalServer: {
      readonly name: "RestartLocalServer",
      readonly I: typeof RestartLocalServerRequest,
      readonly O: typeof RestartLocalServerResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

