// @generated by protoc-gen-connect-es v1.6.1
// @generated from file v1/system.proto (package v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DownloadAIModelRequest, DownloadAIModelResponse, ExportBackupRequest, ExportBackupResponse, ListAIModelsRequest, ListAIModelsResponse, RestoreBackupRequest, RestoreBackupResponse } from "./system_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SystemService manages database backups, system state, and local AI model management.
 *
 * @generated from service v1.SystemService
 */
export const SystemService = {
  typeName: "v1.SystemService",
  methods: {
    /**
     * Export a complete encrypted backup archive of the SQLite database.
     *
     * @generated from rpc v1.SystemService.ExportBackup
     */
    exportBackup: {
      name: "ExportBackup",
      I: ExportBackupRequest,
      O: ExportBackupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Restore the database state from a backup archive.
     *
     * @generated from rpc v1.SystemService.RestoreBackup
     */
    restoreBackup: {
      name: "RestoreBackup",
      I: RestoreBackupRequest,
      O: RestoreBackupResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List available recommended and downloaded open-weights AI models in data/models/.
     *
     * @generated from rpc v1.SystemService.ListAIModels
     */
    listAIModels: {
      name: "ListAIModels",
      I: ListAIModelsRequest,
      O: ListAIModelsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Download an open-weights GGUF AI model into data/models/ given a name or Hugging Face repo.
     *
     * @generated from rpc v1.SystemService.DownloadAIModel
     */
    downloadAIModel: {
      name: "DownloadAIModel",
      I: DownloadAIModelRequest,
      O: DownloadAIModelResponse,
      kind: MethodKind.Unary,
    },
  }
};

